### ISSUE TITLE
Pcmanfm-qt should not close on Alt-F4 ..

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#830] opened 2015-09-26 00:10 UTC
when painting the desktop. Noticed this behaviour with xfwm4, openbox and kwin are ok.
pcmanfm don't show this behaviour, so i would call this a regression.

**Comment by pmattern** [comment] 2015-09-26 09:20
But that's a dupe of lxde/pcmanfm-qt#194, isn't it?

**Comment by agaida** [comment] 2015-09-26 15:08
yes - forget that pcmanfm-qt has his own bug tracker - anyways, this is not the intended behaviour and should be fixed before the release.

**Comment by pmattern** [comment] 2015-09-26 22:23
Well, so I guess you don't mind as closing this one so as to avoid clutter, right?

**Closed by pmattern** 2015-09-26 22:23 UTC
Labels: pcmanfm-qt, regression
