### ISSUE TITLE
Kwin_x11 awfully slow when starting up lxqt

### ISSUE THREAD

**Issue by ms6676749** [lxde/lxqt#836] opened 2015-10-01 01:06 UTC
With Kwin 4.x it took about 10s to start after entering startx from a cold boot, instantaneously after a warm startup (kwin still in memory after kde session).  With Kwin 5.4, it takes 25s from either a cold boot or warm startup.  I since switched to Openbox and Compton-git as my WM and compositor respectively.

Setup:
Archlinux
lxqt-desktop-git (AUR)
Openbox
Compton-git
kwin 5.4.1

**Comment by pmattern** [comment] 2015-10-01 10:18
The LXQt project isn't developing its own window manager but relying on third-party solutions. This also applies to KWin that's developed by the KDE project and known to perform rather poor compared to other window managers.
To my knowledge there's nothing like code optimisations we can do about it so this is an upstream issue.

Btw. Xfwm is performing very well, too, besides it does comprise a compositor and provides themes that may look a bit more up-to-date than e. g. the ones from Openbox.

**Comment by paulolieuthier** [comment] 2015-10-01 11:08
@pmattern we shouldn't close it just because it's upstream. KWin is indeed slower, but 25 seconds is too much, and it doesn't happen in Plasma. I can reproduce it as well. It may be our fault.

**Comment by stefonarch** [comment] 2015-10-01 12:49
Cannot confirm this findings, on my testaccount with no applications in
autostart desktop is ready including kwin working in ~2 seconds, same with reboot or logout/login.
Arch + latest git packages. Kwin with default settings.

**Comment by mgraesslin** [comment] 2015-10-01 17:33
KWin maintainer speaking here: 25 sec is too long, that's not normal (1-2 sec at max!). Can you help to investigate where the problem is? E.g. can you try to do kwin_x11 --replace & from a konsole to check whether that takes also quite some time. If it does, you could enable the debug output to see whether it prints something useful.

**Comment by paulolieuthier** [comment] 2015-10-01 17:52
@ms6676749 can you help?

**Comment by pmattern** [comment] 2015-10-01 18:00
@mgraesslin 
Output from an up-to-date Arch Linux x86_64 system, hence KWin 5.4.1 and Openbox 3.6.1 (default), running in a KVM/QEMU VM, xf86-video-qxl driver and all LXQt components from recent VCS checkouts
```
$ kwin_x11 --replace & 
$ Could not find drkonqi at /usr/lib/drkonqi
Module 'org.kde.kwin.decoration' does not contain a module identifier directive - it cannot be protected from external registrations.
QDBusConnection: name 'org.kde.kglobalaccel' had owner '' but we thought it was ':1.71'
detected kglobalaccel restarting, re-registering all shortcut keys
Service started, version: 6.2.0
```
Window decorations change at once, same with output until line `QDBusConnection: [...]` but windows remain unresponsive for about twenty seconds. Then lines `detected [...]` come up and windows are responsive.

> you could enable the debug output 

That is?

**Comment by ms6676749** [comment] 2015-10-01 19:32
@mgraesslin 

Could not find drkonqi at /usr/lib/drkonqi
QXcbConnection: XCB error: 8 (BadMatch), sequence: 1563, resource id: 8388614, major code: 42 (SetInputFocus), minor code: 0
OpenGL vendor string:                   Intel Open Source Technology Center
OpenGL renderer string:                 Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL version string:                  3.0 Mesa 11.0.2
OpenGL shading language version string: 1.30
Driver:                                 Intel
GPU class:                              IvyBridge
OpenGL version:                         3.0
GLSL version:                           1.30
Mesa version:                           11.0.2
X server version:                       1.17.2
Linux kernel version:                   4.2.2
Requires strict binding:                yes
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no

**Comment by mgraesslin** [comment] 2015-10-02 05:49
ok can you please enable further debug output. It's in file ~/.config/QtProject/qtlogging.ini - if it doesn't exist create it. Add a group [Rules] if it doesn't exist and add:

kwin_core.debug=true
kwineffects.debug=true
libkwineffects.debug=true
libkwinglutils.debug=true
libkwinxrenderutils.debug=true
kwin_tabbox.debug=true
kwin_decorations.debug=true
kwin_scripting.debug=true
aurorae.debug=true

This should provide way more debug output and we may be able to see where the timeout happens.

**Comment by pmattern** [comment] 2015-10-02 11:23
Terminal output from system as described yesterday,  ~/.config/QtProject/qtlogging.ini like this
```
[Rules] 
kwin_core.debug=true
kwineffects.debug=true
libkwineffects.debug=true
libkwinglutils.debug=true
libkwinxrenderutils.debug=true
kwin_tabbox.debug=true
kwin_decorations.debug=true
kwin_scripting.debug=true
aurorae.debug=true
```
LXQt components from checkout this moning: [first LXQt session](https://gist.github.com/pmattern/b8704d2bac66453b5466) after reboot, [second session after reboot](https://gist.github.com/pmattern/e5016467f143e73726d5). String `[break]` added manually to mark period when system is frozen.

Also, in the meantime I saw it's not just the windows which are unresponsive but the panel is affected as well: no plugin can be used, seconds in clock are frozen.

**Comment by mgraesslin** [comment] 2015-10-02 11:56
Interesting the "break" happens at different point of times. Once before, once after initializing compositing. What I don't like are the two messages concerning kglobalccel. That could explain a freeze but shouldn't.

> Also, in the meantime I saw it's not just the windows which are unresponsive but the panel is affected as well: plugins cannot be used, seconds in clock are frozen.

That's not surprising: the compositor is frozen and thus the screen doesn't get updated.

In case you have another system to ssh in: please run kwin_x11 through a debugger, break during the freeze and get the backtrace. It's important to do that through ssh, otherwise you end up with a broken system (been there, done that, no fun). More info on that here: https://community.kde.org/KWin/Hacking#Debugging_KWin

**Comment by heliocastro** [comment] 2015-10-02 12:32
Moin guys

Just to add some light on the discussion, we have something similar on freezing issues on current plasma 5 on Fedora, and that was related not to KDE itself, but on X11 xcb. I not mentioned before because we thought was Fedora related, but now seens that is upstream then Fedora.
This can be a possible source of investigation in this related issue as well.
Here's the bugs related
https://bugreports.qt.io/browse/QTBUG-42738
https://bugs.freedesktop.org/show_bug.cgi?id=59361

We have our own bug here:
https://bugzilla.redhat.com/show_bug.cgi?id=1267976

I know is a shot in the dark, but when similar situations happens, maybe can lead to same issue and resolution.

[]'s Helio

**Comment by pmattern** [comment] 2015-10-02 14:02
So I made a backtrace as follows: Launch LXQt session and connect as same user via SSH. Launch GDB as `DISPLAY=:0 gdb kwin_x11`. In GDB shell invoke `run --replace`, `Ctrl+C` when the freeze takes place and `bt`.
Find the output on https://gist.github.com/pmattern/65e70ca108f371343370. Results were the same in first and second LXQt session after reboot this time.
What seems a bit odd to me is that message "Service started, version: 6.2.0" which comes up after KWin was halted.

> It's important to do that through ssh, otherwise you end up with a broken system

Besides the problem discussed here exists on the host as well I'm performing the tests in VMs making heavy use of snapshots. So all kinds of crashes or whatever don't matter.

**Comment by mgraesslin** [comment] 2015-10-02 14:08
It's starting of KActivities. Do you have those installed? I'll see the main developer next week and will ask him about the problem.

**Comment by pmattern** [comment] 2015-10-02 14:14
> KActivities. Do you have those installed?

→ [kactivities-frameworks](https://www.archlinux.org/packages/extra/x86_64/kactivities-frameworks/) is installed. That's all that can be done in terms of KActivities, no?

**Comment by mgraesslin** [comment] 2015-10-02 19:59
yep that looks like the package. I'll have to check with Ivan what could be the case for it. It looks like https://bugs.kde.org/show_bug.cgi?id=349992 which so far was to my knowledge only a problem on Wayland.

**Comment by Kf4btg** [comment] 2015-10-05 20:46
I'm also experiencing this and thought perhaps some output from a slightly different setup might be helpful.  I hope it will be, anyway.  Sorry for the noise if not.

__My system__:
Manjaro Linux
lxqt-desktop-git (AUR)
Openbox-git
kwin 5.4.1

And some info pulled from kwin's output:
```
OpenGL vendor string:                   Intel Open Source Technology Center
OpenGL renderer string:                 Mesa DRI Intel(R) Ivybridge Mobile
OpenGL version string:                  3.3 (Core Profile) Mesa 11.0.2
OpenGL shading language version string: 3.30
Driver:                                 Intel
GPU class:                              IvyBridge
OpenGL version:                         3.3
GLSL version:                           3.30
Mesa version:                           11.0.2
X server version:                       1.17.2
Linux kernel version:                   4.2.3
Requires strict binding:                yes
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no
```

I'm using OpenGL compositing on my setup; an additional issue I wanted to make sure to mention is that, immediately after boot or doing a kwin_x11 --replace, LXQt-panel and window titlebars flicker heavily, being most apparent when moving the mouse around.  I can easily resolve this by switching compositing off and then back on with Shift-alt-F12, thus making this a relatively minor issue, but since it may be related I thought I'd bring it up.

I followed the information given above for enabling debug output, and, starting from openbox, switched to kwin. [Here's the log.](https://gist.github.com/Kf4btg/d874e58ba3eec90c64d4) Following @pmattern's example, I added [break] to indicate when the pause occurred.  For full disclosure, I actually performed this test twice (the first time I had a lot of extraneous programs open which cluttered up the output, so I closed them and repeated the process), and, unlike pmattern's output, the delay occurred in the same place each time (immediately after the "initializing compositing" message). Additionally, in case it's useful, I included systemd's journal output from the moment of the command, showing an XCB error and some messages from kactivitymanagerd.

One last thing to note: when switching the WM _from_ kwin to something else (e.g. openbox), kactivitymanagerd always dumps its core. [The backtrace](https://gist.github.com/Kf4btg/773f95f2236e86707417) seems to indicate QXcbConnection is involved, and, going off @heliocastro's mention of a similar issue being xcb-related, perhaps this information is relevant. Also included there are two lines of journalctl output, the first being kactivitymanagerd reporting a QWidget error, followed by the core-dump notification.

 Hope at least some of this is useful.  Keep up the amazing work, guys!

**Comment by mir3x** [comment] 2015-10-06 18:05
I had such slow load with kwin_x11, but I checked my autostart and kicked redshift from it, and now it looks ok.

**Comment by jpsutton** [comment] 2015-11-12 04:14
For those interested in a possibly-dangerous work-around, you can try "disabling" kactivitymanagerd (which is causing a DBUS deadlock according to the upstream KDE bug report).  Try the following, as root:

cd /usr/bin
mv kactivitymanagerd kactivitymanagerd.real
ln -s true kactivitymanagerd

This causes kwin to start instantly for me when doing "kwin_x11 --replace &" from a shell.

**Comment by dglent** [comment] 2015-11-12 05:17
The above works for me, thanks.
In which case could be dangerous ?

**Comment by pmattern** [comment] 2015-11-12 09:20
>upstream KDE bug report

Mind posting a link?

**Comment by jpsutton** [comment] 2015-11-13 22:47
I made the statement about "possibly dangerous" because I just don't have the knowledge to understand what kactivitymanagerd is doing in the first place and what side-effects replacing it with a placebo executable might have.

**Comment by dglent** [comment] 2015-11-14 03:15
With the symlink i have a gain (10 - 15 seconds) only when i logout and login immediately.
After a fresh boot the login time remains at 25-30 seconds.

**Comment by paulolieuthier** [comment] 2015-12-23 03:22
Since a few days, I don't see this bug anymore.

**Comment by paulolieuthier** [comment] 2015-12-30 15:50
@pmattern can you confirm?

**Comment by YamashitaRen** [comment] 2015-12-31 11:55
@paulolieuthier Here it's now working very well :)

**Comment by paulolieuthier** [comment] 2015-12-31 12:54
Thanks.

**Closed by paulolieuthier** 2015-12-31 12:54 UTC
Labels: upstream
