### ISSUE TITLE
LXQt notificationd: when using i3 as WM the notification is not shown

### ISSUE THREAD

**Issue by somdoron** [lxde/lxqt#1345] opened 2017-09-02 13:42 UTC
Using i3 (gaps) as window manager. If I have any window open the notification is not shown.
If no windows are opened the notification is shown. I expect the notification to be shown on top of the window.

##### Expected Behavior
Notification is shown on top of the open window.

##### Current Behavior
The notification is not shown.

##### Steps to Reproduce (for bugs)
1. Install i3 (or i3-gaps)
2. Use i3 as window manager
3. open any window
4. send a notification using notify-send

##### Context
For now I'm using dunst instead.

##### System Information
* Distribution & Version: Fedora 26
* Kernel: 4.12.9-300.fc26.x86_6
* Qt Version: 
* liblxqt Version: liblxqt-0.11.1-5.fc26.x86_64 
* Package version: lxqt-notificationd-0.11.1-4.fc26.x86_64

**Comment by agaida** [comment] 2017-09-02 14:22
not a bug in LXQt i would guess - seems to be a problem with WM notification handling

**Comment by somdoron** [comment] 2017-09-02 20:31
Might be. However both dunst and xfce-notifyd works well.
Another use complain about this with different tiling WM (bspwm)

https://www.reddit.com/r/bspwm/comments/4op4fq/lxqt_bspwm_notifications_stuck_behind_windows/

**Comment by agaida** [comment] 2017-09-02 21:20
ok, a solution too - @tsujan - i don't know nothing (erm, not much) about the notification handling - is there anything what we could improve? Imho we take a notification and then the notification automagically appear on the screen? Is that idea to simple or just stupid?

**Comment by tsujan** [comment] 2017-09-03 03:24
@agaida The automagic part is `QDesktopWidget::availableGeometry()` and `QWWidget::setGeometry()`, which should be independent of the WM but who knows, an environment may not respect this. For example, I know that Enlightenment doesn't report the available geometry correctly. I don't think such cases are Qt's problem, let alone LXQt's. As for Enlightenment, I haven't reported that to its devs yet, mostly because it takes a very long time for them to pay attention to bug reports.

**Comment by tsujan** [comment] 2017-09-03 03:50
Tiling window managers may not respect `QWidget::setGeometry()` for obvious reasons, in which case, they should have a setting for ignoring position enforcement for specific windows. This bug should be reported to their developers, IMO.

**Comment by agaida** [comment] 2017-09-03 12:10
Full ACK.

**Comment by Airblader** [comment] 2018-03-01 06:17
As a window manager developer I don't see what geometry has to do with any of this, perhaps someone could explain. 

We've looked at the window opened by lxqt and it's an override_redirect window. That means any window manager in existence will not touch this window and it's in full control of lxqt. That's the tradeoff you make when bypassing the window manager: you'll have to manage it yourself. 

This strikes me as a simple issue of lxqt not ensuring to stack the window to the top. But it's clearly a lxqt issue.

**Comment by palinek** [comment] 2018-03-01 08:38
@somdoron Can you, please, check if the lxde/lxqt-notificationd#73 makes any difference?

**Comment by tsujan** [comment] 2018-03-01 09:57
>  I don't see what geometry has to do with any of this

That was a reply to another question.

> That's the tradeoff you make when bypassing the window manager: you'll have to manage it yourself.

And it seems managed correctly by Qt. Since, in addition, i3 is alone in this, I can't see how this can be "a simple issue of lxqt".

**Comment by tsujan** [comment] 2018-03-01 10:23
Replying to my comment above: it could also be said that lxqt notification is alone in this because it's Qt5 based.

I'd seen and reported weird things with Qt5 under Compiz too but Compiz developers fixed them. However, I won't be surprised if Qt5 has a problems with X11 -- at least, it menus had a bad problem for a long time but it's fixed now.

**Comment by Airblader** [comment] 2018-03-01 11:25
> Since, in addition, i3 is alone in this, I can't see how this can be "a simple issue of lxqt".

Likewise, other notification daemons like dunst work just fine in i3, so lxqt-notificationd is alone in this.

You have a choice[1] of how to create your notification windows. You made them override_redirect, which makes sense to me, but means you told the window manager not to manage the window. In i3[2] (and many other window managers[3][4]) this means that when a map request comes along, the window manager will not redirect requests and in most cases just completely forget about this window's existence the very moment it reads the flag.

It also means that the window manager ignores it for handling the stacking order. You cannot use EWMH hints to keep the window on top; you'll have to care for that yourself. My guess is that you need to a) raise the window explicitly when you map it (e.g., dunst calls `XMapRaised` instead of just `XMapWindow`) and b) perhaps listen for visibility change events and raise the window from those as well. I don't know how this translates to Qt as I don't know Qt. To draw a parallel, this is what i3lock does[5][6].

[1] https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.10
[2] https://github.com/i3/i3/blob/next/src/manage.c#L110
[3] https://github.com/awesomeWM/awesome/blob/master/event.c#L774
[4] https://github.com/danakj/openbox/blob/master/openbox/window.c#L207
[5] https://github.com/i3/i3lock/blob/master/xcb.c#L156
[6] https://github.com/i3/i3lock/blob/master/i3lock.c#L540

**Comment by tsujan** [comment] 2018-03-01 15:22
> Likewise, other notification daemons like dunst work just fine in i3...

As I mentioned before your comment.

> I don't know how this translates to Qt 

Nowadays -- because of Wayland -- it's preferable to rely on Qt and Qt based libraries by using X11 independent codes instead of dealing with X11 directly.

**Comment by Airblader** [comment] 2018-03-01 15:24
I understand the reasoning for using Qt, I'm just saying I don't know Qt and cannot tell you what the Qt APIs are called you need to use. I can only give you the X11 perspective of what I believe you'd have to do.

**Comment by tsujan** [comment] 2018-03-01 15:33
Don't get me wrong, this wayland vs. X11 situation is unfortunate to me. It would be good if we were able to use X11 freely when needed, as was done with older codes. However, (more) X11 would make an app unmanageable in the "near future" (that has been "coming" for a long time).

That being said, a Qt mistake is also possible, although I can't find any. If https://github.com/lxde/lxqt-notificationd/pull/73 works, it'll be only by chance.

**Comment by Airblader** [comment] 2018-03-01 15:38
If I had to randomly guess I would say that Qt certainly has some API (not specific to X11) which allows you to raise a window to the front as I'd imagine this is also a thing under Wayland. I just don't know what it's called.

The stay-on-top hint in the X11 world is an EWMH hint which will be ignored since they are evaluated by the window manager and the window manager ignores override-redirect windows. I don't imagine the pull request would fix anything for that reason. As I said, window hints are useless here, you'd need to actively raise the window.

**Comment by Airblader** [comment] 2018-03-01 15:47
They will abstract display server specific stuff, but you cannot expect Qt to know what you want to do exactly when you want to do it. You, as the client, need to tell Qt that you'd like to move your window to the front. Then it's Qt's job to make the correct X11/Wayland request.

I really feel like there is some big misunderstanding here.

**Comment by agaida** [comment] 2018-03-01 15:49
Long story short: We will accept patches ...

**Comment by tsujan** [comment] 2018-03-01 15:50
> Long story short: We will accept patches ...

Only Qt ones, of course ;)

**Comment by Airblader** [comment] 2018-03-01 15:52
That's fine; I won't be providing a patch since I don't use lxqt myself. I only came here to help clarify what the problem is because a user had come to us for support and linked to this (then closed) issue. I'll leave fixing it to someone who can actually verify the fix.

**Comment by tsujan** [comment] 2018-03-01 15:58
This question isn't answered yet: why does the window show up at the correct position with kwin, openbox, compiz... but not i3 (and ...)? The correct Qt way is setting the flag `Qt::WindowStaysOnTopHint` and showing/activating the window.

**Comment by Airblader** [comment] 2018-03-01 16:01
> why does the window show up at the correct position […] but not i3 […]?

It *is* at the correct position, it's just not stacked correctly.

> The correct Qt way is setting the flag Qt::WindowStaysOnTopHint and showing/activating the window.

For managed windows, certainly. For unmanaged windows I suspect that this isn't the case. There simply is no concept of the window manager keeping your window on top if you choose to bypass the window manager. Much like you cannot expect your doctor to treat you if you keep walking past his office.

**Comment by tsujan** [comment] 2018-03-01 16:06
Quoting Qt doc about `Qt::WindowStaysOnTopHint`:

"Informs the window system that the window should stay on top of all other windows. Note that on some window managers on X11 you also have to pass Qt::X11BypassWindowManagerHint for this flag to work correctly"

More than that doesn't seem acceptable to me. It would rather mean doing that doctor's job for him.

**Comment by Airblader** [comment] 2018-03-01 16:09
Interesting. Granted, the documentation suggests that it should work then. I don't know how Qt could fulfill that promise, but it's a promise they make.

**Comment by palinek** [comment] 2018-03-01 16:36
I was curious... installed the i3 an make a test -> notification is shown correctly:
![screenshot](https://user-images.githubusercontent.com/10990929/36856677-ddca9832-1d76-11e8-85c1-df2ad18a30a8.png)

... on debian testing:
```
Package: liblxqt0
Version: 0.12.1~6-g0c93a6d-1

Package: liblxqt0
Version: 0.12.1~6-g0c93a6d-1

Package: libqt5core5a
Version: 5.9.2+dfsg-12
```

**Comment by Airblader** [comment] 2018-03-01 16:40
The user who reported to us said that the issue went away after running compton as well; but it also went away after disabling compton again. So my assumption is that this cannot be reproduced 100%-reliably, which would make sense if it's a stacking order issue.

**Comment by palinek** [comment] 2018-03-01 16:43
> The user who reported to us said that the issue went away after running compton as well; but it also went away after disabling compton again.

I don't use compton and it wasn't on even before on the testing session.

> So my assumption is that this cannot be reproduced 100%-reliably, which would make sense if it's a stacking order issue.

Then it's even harder for us to find a solution w/o being able to reproduce the problem.

**Comment by Airblader** [comment] 2018-03-01 16:44
> Then it's even harder for us to find a solution w/o being able to reproduce the problem.

Unfortunately, yes.

**Comment by tsujan** [comment] 2018-03-01 17:24
Confirming @palinek's observation: installed i3wm from AUR and notifications were shown correctly under it: on the top of other windows, at the right bottom corner of the screen.

**Comment by somdoron** [comment] 2018-03-01 17:54
I'm now using fedora 27 and was not able to reproduce the issue, both with and without compton.

**Comment by somdoron** [comment] 2018-03-01 18:04
liblxqt-0.11.1-7
lxqt-notificationd-0.11.1-6

**Comment by agaida** [comment] 2018-03-01 18:05
upps - one should at least use not dead releases

**Comment by tsujan** [comment] 2018-03-01 18:06
> lxqt-notificationd-0.11.1-6

It's old but the issue doesn't happen with the latest git either.

Probably, it was an issue in Qt's X11 support that was fixed with an update. Reopen if it happens again.

**Closed by tsujan** 2018-03-01 18:06 UTC

**Comment by somdoron** [comment] 2018-03-01 18:17
> upps - one should at least use not dead releases

It is fedora 27 latest

**Comment by agaida** [comment] 2018-03-01 21:44
So fedora missed a release for a few month now ...
