### ISSUE TITLE
Impossible select single icon if other icons are too near

### ISSUE THREAD

**Issue by hifi25nl** [lxde/lxqt#768] opened 2015-07-28 14:54 UTC
Impossible select single icon if other icons are too near. If I click on an icon surrounded by other icons all are selected instead of the single one. Both with standard pcmanfm-qt and pcmanfm-qt git.

**Comment by pmattern** [comment] 2015-07-28 15:15
Valid issue. Regarding the code in question probably related to lxde/pcmanfm-qt#97, btw.

**Comment by bibo01** [comment] 2015-07-29 01:37
+1 on this issue

**Comment by pmattern** [comment] 2015-07-29 07:40
FWIW a workaround is to click the icon that was intended to get selected again when it's part of a group of selected icons.

**Comment by hifi25nl** [comment] 2015-09-22 09:12
Some news? i think this bug is very annoying, and maybe should have high priority.

**Comment by paulolieuthier** [comment] 2015-09-22 11:15
Agreed.

**Comment by paulolieuthier** [comment] 2015-10-31 15:37
@PCMan can you take a look at this one?

**Comment by jleclanche** [comment] 2015-11-01 06:51
Unless someone tells me this can be easily fixed, I'm going to start the release process today.

**Comment by hifi25nl** [comment] 2015-11-01 09:55
It would be not advisable to release Lxqt with such a bug.

**Comment by jleclanche** [comment] 2015-11-01 09:59
@hifi25nl I don't believe this is a regression, so it's in 0.9 as well. Releasing 0.10 with the bug would make no difference.

I think we will do a 0.9.1 release on select components though, so this could be fixed then. I don't want to rush a bugfix and have something worse crop up because we didn't look close enough.

**Comment by tsujan** [comment] 2015-11-05 16:55
This simple commit fixes the issue for me:

https://github.com/tsujan/pcmanfm-qt/commit/26a9a754e67602490fddc2e3c69bfdad7efa98f2

Please test it before I make a PR!

**Comment by paulolieuthier** [comment] 2015-11-05 17:41
@tsujan that's great news. Make the PR and we test, comment and discuss.

**Comment by pmattern** [comment] 2015-11-24 15:05
@hifi25nl 
This should be fixed in latest VCS code. Could you please verify? Also the discussion in lxde/pcmanfm-qt#252.

**Comment by palinek** [comment] 2016-01-05 23:09
Isn't this one already fixed?

**Comment by stefonarch** [comment] 2016-01-06 09:26
For me yes

Il 06/01/2016 00:10, palinek ha scritto:

**Comment by pmattern** [comment] 2016-01-07 01:13
Problem was indeed solved by lxde/pcmanfm-qt#252.

**Closed by pmattern** 2016-01-07 01:13 UTC
Labels: pcmanfm-qt
