### ISSUE TITLE
Launchers in Task Manager widget

### ISSUE THREAD

**Issue by goetzc** [lxde/lxqt#925] opened 2015-12-24 20:32 UTC
Having launchers in the task manager instead of being a separated widget would give the advantage of using less space by reusing the icon (transforming the launcher icon into the task), and provide the possibility to create a launcher for any running application by right clicking the task icon and selecting the option.

**Comment by intialonso** [comment] 2015-12-27 15:55
I agree. I guess i done like this for convenience and easiness, but in the future I think that it should work as you propose. Lets wait if someone can take the job.

**Comment by pmattern** [comment] 2016-04-07 11:23
Duplicate of #131.

**Closed by pmattern** 2016-04-07 11:23 UTC
Labels: idea/discussion, lxqt-panel
