### ISSUE TITLE
[Feature-Request] could you consider to support globalmenu?

### ISSUE THREAD

**Issue by hosxy** [lxde/lxqt#1408] opened 2017-11-16 05:13 UTC
As the title say，could you consider to support globalmenu like unity and kde plasma 5.9 ?
I think it can make screen used effectively for small screen computer especially.

**Comment by tsimonq2** [comment] 2017-11-16 05:16
I don't see why not, but who's going to volunteer to implement it? :wink:

**Comment by yan12125** [comment] 2017-11-16 06:05
Looks like the same as #133?

**Comment by palinek** [comment] 2017-11-16 07:39
duplicate of #133

**Closed by palinek** 2017-11-16 07:39 UTC
Labels: invalid/dup/rejected
