### ISSUE TITLE
lxqt-panel: volume plugin: mute from keyboard button doesn't unmute

### ISSUE THREAD

**Issue by chicao** [lxde/lxqt#733] opened 2015-07-05 18:18 UTC
Hello,

I just installed lxqt on my laptop and everything is working great. However, I just noticed a strange behaviour on the volume-plugin, were I mute the output using the 'mute' keyboard shortcut. The sound is muted accordingly, but when I try to unmute it stays with no output. 

I'm on Archlinux and the LXQt version used is 0.9.0-1, installed from pacman. The used backend is Alsa and the selected device is the hw:1-Master. When I restart the computer, the sound works fine again.

**Comment by pmattern** [comment] 2015-07-06 11:03
Duplicate of #612.

**Closed by pmattern** 2015-07-06 11:03 UTC
Labels: invalid/dup/rejected
