### ISSUE TITLE
plugin-tray: misplacement of area responsive to clicking

### ISSUE THREAD

**Issue by Chocimier** [lxde/lxqt#1255] opened 2017-02-11 14:14 UTC
##### Steps to Reproduce (for bugs)
1. Configure panel: Size: 45px, Icon size: 22px, Rows count: 1, Position: left on desktop; add tray widget
2. Restart panel
3. Click between left screen edge and icon: icon reacts, but should not
4. Click on right half of icon: icon does not react, but should do

##### System Information
* Package version: lxqt-panel 0.11.1-1 of Arch

**Comment by pmattern** [comment] 2017-02-12 01:21
I can confirm this finding running [LXQt ConnMan Applet](https://github.com/surlykke/lxqt-connman-applet) in plugin-tray, where a restart of the panel doesn't even seem to be mandatory, but not in plugin-statusnotifier. (For an explanation of the difference between the two plugins see [here](https://github.com/lxde/lxqt-panel#status-notifier-plugin-plugin-statusnotifier--system-tray-plugin-tray).)
Can you verify different behaviour like this in the two plugins? Also, could you state the icons of which applications are affected, in particular whether these are Qt 5, Qt4 or GTK applications?

**Comment by Chocimier** [comment] 2017-02-13 14:08
Plugin-statusnotifier works good.
In plugin-tray all gtk (thunderbird with firetray), qt4 (kvirc) and qt5 
(kadu) icons are buggy.
I noticed that sometimes only click area of last icon is shifted.

**Comment by pmattern** [comment] 2017-02-13 16:50
Thanks for providing this information. I'm adjusting this issue's title to be a bit more specific then.

Notes:
I'm not too optimistic this issue will receive a lot of attention as plugin-tray is basically legacy stuff. Applications compiled against Qt 5 are supporting SNI by design, as for GTK there are wrappers and Qt 4 can be considered seriously outdated by now.
Applications compiled against recent versions of Qt 5 should by default chose to display their icons in plugin-statusnotifier if both this and plugin-tray are available. Doesn't this apply at your side, too?

**Comment by palinek** [comment] 2017-03-09 07:48
fixed in lxde/lxqt-panel@562acac, thanks @Chocimier

**Closed by palinek** 2017-03-09 07:48 UTC
Labels: lxqt-panel
