### ISSUE TITLE
regression in themes: white-on-white main menu under dark system palettes

### ISSUE THREAD

**Issue by v-fox** [lxde/lxqt#1163] opened 2016-10-01 06:00 UTC
I just updated to LXQt 0.11 and the first things I saw was ugly white_text-on-white_background main menu of "dark" theme. Previously I used custom dark colour palette made for KDE4 that was loaded by GTK+ Qt theme through oxygen-gtk GTK2 theme but now I use breeze Qt theme with that customized palette (Breeze-Dark palette shows same glitch though).

The culprit seems to be 167a196a2ef49af428e1fc2d546deb59d9728277 commit of lxqt-common ("Fix the search textfield style for all themes"). I reverted it and the menu seem to be properly dark on the dark theme.

Also, on the system theme text in task manager seem to be aligned to center which makes it unusable then task names do not fully fit in it. How can I force it to be aligned to left ?
And why the hell transparency settings of the panel are blocked even with compton and kwin ?

**Comment by stefonarch** [comment] 2016-10-01 06:14
On the dark theme I cannot see your problem, how do you set your custom palette?
For transparency you have to enable a custom background color. 
Confirmed the bug in "system" themes taskbar.
There are some other themes you can try out:
https://github.com/Val67/lush-lxqt-theme
https://github.com/stefonarch/lxqt-themes

**Comment by v-fox** [comment] 2016-10-01 06:42
> how do you set your custom palette?

Now, with "breeze" widget style (set in lxqt.conf, KDE4 _and_ 5 `kdeglobals`, "Breeze-Dark" theme in GTK2 and 3) and putting it directly into `kdeglobals` (for both KDE4 and KDE5). Also I put .color file of the palette in `~/.config/color-schemes` and `~/.kde4/share/apps/color-schemes/` just to be sure. I can edit it in KDE's systemsettings.

With "GTK+" widget style it's more roundabout because then it loads settings from `~/.gtkrc-2.0` first, which has oxygen-gtk theme in it, which loads palette from KDE4's kdeglobals.

To force Qt4/KDE4 apps to eat up my styles, palettes and icons I need `KDE_FULL_SESSION=false` and `KDE_SESSION_VERSION=4` variables in `~/.config/lxqt/session.conf`. It also a pain to force KDE apps to eat up ComixCursors-Green cursor theme, even LXQt likes to default to crystalgreen for some reason. So I force XCURSOR_THEME variable where I can. KDE's GUI cursor settings just hang for both KDE4 and 5, probably because it reads all icon themes too and it can't handle my mishmash icon theme with a lot of "Inherits".

> For transparency you have to enable a custom background color.

Ha, indeed ! For some reason I never though of that.

> There are some other themes you can try out:
> https://github.com/Val67/lush-lxqt-theme
> https://github.com/stefonarch/lxqt-themes

Unfortunately, making system packages for them is a hassle. There is lush package for openSUSE, I tried it and it's nice, except for eye-gouging bright acid green highlight.

**Comment by stefonarch** [comment] 2016-10-01 07:06
Try out in ../system/lxqt-panel.qss

> #TaskBar QToolButton {
    border: 1px solid silver;
    margin:2px;
}

**Comment by v-fox** [comment] 2016-10-01 08:52
> Try out in /usr/share/lxqt/themes/system/lxqt-panel.qss

That commit seems to indeed fix task name alignment.

By the way, system, ambience and lush themes did not have white-on-white problem even without "search textfield style" commit reversal. So, I think I will use system theme from now on, it properly loads palette and has good icon grouping and better mouse focus highlights under breeze.

**Comment by Esclapion** [comment] 2016-10-01 09:44
I have exactly the same problem v-fox, btw. For the moment, I use ambiance.

**Comment by stefonarch** [comment] 2016-10-01 17:22
For temporary fix the white background issue: Try out in /usr/share/lxqt/dark/lxqt-panel.qss replacing here     ' background: palette(text); ' :

> #MainMenu  QMenu {
    margin: 4px;
    background: black;
}

Actually    background: palette(text) should take text color from widget.

**Comment by tsujan** [comment] 2016-10-01 17:28
@stefonarch 
My lxqt-common may not be up-to-date but the general rule is that when you set the background, you should also set the foreground, and vice versa. Could you please test if this fixes the issue?
````
#MainMenu  QMenu {
    margin: 4px;
    background: palette(text);
    color: palette(window);
}
````

**Comment by stefonarch** [comment] 2016-10-01 17:36
I have no dark palette around, the problem seems to be that (text) is not loaded, so this would probably produce here black text on white background (with dark palette+bug)

**Comment by tsujan** [comment] 2016-10-01 17:41
Anyway, if in any LXQt theme the foreground is set without the background (or conversely), that could create unreadable text and should be fixed. Contrast is guaranteed between `text ↔ window`, `highlighted-text ↔ highlight`, etc.

**Comment by Esclapion** [comment] 2016-10-01 17:48
@tsujan : doesn't work for me :-(

![ar8t6pk](https://cloud.githubusercontent.com/assets/3512979/19016022/0d841146-8810-11e6-94de-b89fedb2a6b2.png)

**Comment by tsujan** [comment] 2016-10-01 17:54
> @tsujan : doesn't work for me :-(

Please also try `background: palette(window-text);` instead of `background: palette(text);`!

**Comment by Esclapion** [comment] 2016-10-01 17:55
@stefonarch:

![a](https://cloud.githubusercontent.com/assets/3512979/19016084/038aeaba-8811-11e6-93d5-36691b99863d.png)

Can we be more precise for the color ?

**Comment by tsujan** [comment] 2016-10-01 17:57
@stefonarch
Is your screenshot about a problem or a solution?

**Comment by tsujan** [comment] 2016-10-01 17:58
I meant @Esclapion...

**Comment by tsujan** [comment] 2016-10-01 18:10
As `window` and `text` may not have enough contrast in some color schemes, the correct pairs of palette colors for background and foreground are:
````
text ↔ base
window-text ↔ window
highlighted-text ↔ highlight
````

**Comment by Esclapion** [comment] 2016-10-01 18:12
_background: palette(window-text) doesn't work too... !-(

**Comment by tsujan** [comment] 2016-10-01 18:14
You mean `background: palette(window-text);`? If it doesn't work, he dark color scheme you use may have issues.

**Comment by Esclapion** [comment] 2016-10-01 18:16
I tried several different themes, always the same problems. It worked in 0.10, but...

**Comment by tsujan** [comment] 2016-10-01 18:20
> I tried several different themes, always the same problem. It worked in 0.10, but...

Then I have no clue. I just know that `#MainMenu  QMenu` should be corrected in LXQt's dark theme as explained above

**Comment by Esclapion** [comment] 2016-10-01 20:57
@stefonarch : your temporary fix doesn't work when you use the search area of the menu.

An idea to solve that ? Which is the relevant part of the  qss ?

**Comment by stefonarch** [comment] 2016-10-01 21:10
> Can we be more precise for the color ?

#MainMenu QMenu {
margin: 4px;
background: #181207;
}

This is the color of the LXQt icon background here, you can use colorpicker plugin in panel to find more suitable ones.

**Comment by Esclapion** [comment] 2016-10-01 21:19
Thanks, I did the try. But for the search area of the menu, it's very annoying :-(

**Comment by tsujan** [comment] 2016-10-01 21:19
@Esclapion 
I took a look at some LXQt themes and saw that they had serious problems. I'll fix them tomorrow.

**Comment by Esclapion** [comment] 2016-10-01 21:22
The other three seem good, only the dark causes me problems. I can't produce an ISO so ;)

**Comment by stefonarch** [comment] 2016-10-01 21:25
It's here, just replace palette(*) with 
#181207 for background 
#DEDEDE for color

#MainMenu QLineEdit {
    background: palette(text);
    border: none;
    padding: 6px;
    margin-bottom: 1px;
    color: palette(window);
}

#MainMenu ActionView {
    border: none;
    background: palette(text);
    color: palette(window);
}

#MainMenu ActionView::item {
    border: 1px solid palette(text);
    padding: 3px 0;
}

**Comment by tsujan** [comment] 2016-10-01 21:26
> The other three seem good, only the dark causes me problems

Its name is misleading: it's dark with *light color schemes* and light with dark ones. In fact, it reverses colors. Maybe we should change its name in the future.

**Comment by tsujan** [comment] 2016-10-02 01:03
OK, I revamped the dark theme and made it really dark.

@Esclapion (or anyone interested), please check https://github.com/lxde/lxqt-common/pull/62. You don't need to download the whole branch but just replace `/themes/dark/lxqt-panel.qss` with that of the PR and also add the images `checked.svg` and `unchecked.svg` to your dark folder.

If any other theme has problem, please tell me (I didn't have time to check all of them)!

**Comment by stefonarch** [comment] 2016-10-02 19:15
The changes proposed are actually a workaround IMHO, I used kvantum with dark/red and palette (*) is not respected in old dark theme in mainmenu but in other menus yes, in frost theme which mostly  uses palette (*)  only in runner I see it active, in panel and all menus not.

**Comment by tsujan** [comment] 2016-10-02 19:41
> I now used kvantum with dark/red and I see palette (*) is not respected in shipped dark theme in mainmenu but in other menus

What do you mean by "palette (*) is not respected"? Which palette, which theme and how?

**Comment by tsujan** [comment] 2016-10-02 19:42
> The changes proposed are actually workarounds

Workarounds for what?

**Comment by stefonarch** [comment] 2016-10-02 19:57
For that palette () works only partially. I see when I comment out 

> #MainMenu QMenu::item {
    color: #DEDEDE;
}
#MainMenu QMenu::item:selected {
    color: #DEDEDE;
    background: rgba(255, 255, 255, 20%)

in the dark theme the menu respects kvantum's palette, but when I try

> #MainMenu QMenu::item:selected {
   background: palette(window);
   color: palette(text)
}

I can fill in whatever I wont it's always the same. Same for system theme, trying some palette() to style something it has not the effect it should.

**Comment by tsujan** [comment] 2016-10-02 20:07
If you do that in the Dark theme, it's because the block `QMenu::item:selected {}` is above `#MainMenu QMenu::item:selected {}` and so, the latter takes precedence over the former (because MainMenu is a QMenu). Do the same thing to the former and you'll see that palette colors will be respected.

**Comment by stefonarch** [comment] 2016-10-02 20:56
Ok I missed that, I thougt it would override, thanks.

**Comment by tsujan** [comment] 2016-10-02 21:07
CSS can get quite complex -- mistakes aren't unusual.

Anyway, I don't think there's any styling bug in the panel. Some themes may have problems but the panel is OK.

**Comment by stefonarch** [comment] 2016-10-03 08:10
> The changes proposed are actually workarounds
Workarounds for what?

My point is: with this commit we have yes  a dark menu but it does not respect palette() which makes sense when somebody uses a bright widget style; but we should have a dark theme which respects palette() in menu and panel -  the system menu has this problem  with text centered and my [proposal](https://github.com/lxde/lxqt/issues/1163#issuecomment-250897205) solves that but disactivates palette() in panel.

Testing the main problem is always border: something in panel , which disactivates palette() but makes text on buttons align left.

**Comment by v-fox** [comment] 2016-10-03 08:22
Shouldn't all non-system themes with hardcoded panel style just have the same style hardcoded for menu and other elements to work the same way on any palette ? Although, that would mean that they should have to automatically use custom text, background and image of panel for all elements.

It seems that there is a lot of assumption going on about everyone having default black-on-white palette.

**Comment by tsujan** [comment] 2016-10-03 08:32
> My point is: with this commit we have yes a dark menu but it does not respect palette() which makes sense when somebody uses a bright widget style

I don't get your point yet. The Dark theme shouldn't respect any palette color of the global widget style exactly because it uses its own colors. Frost gets its colors from palettes but it reverses foreground and background. If a theme follows palette colors, why having a theme at all? It would mean letting the global theme engine style panel an all of its widgets.

Actually,  I use a theme that only styles the panel and the widgets that appear on it but leaves other widgets -- including menus -- to the global widget style (which is Kvantum in my case). In your screenshot, all widgets are styled by Kvantum. You see that there's no icon margin and the text isn't elided. That's because the taskbar items don't obey the style plugin completely (I can see that as a minor bug in panel because if they're buttons, they should follow the style plugin when not styled by an LXQt theme). So, it's better to style them with an LXQt theme.

**Comment by tsujan** [comment] 2016-10-03 08:36
@palinek 
Are taskbar items QToolButtons? If so, why don't they follow the active style plugin when NOT styled by QSS?

**Comment by palinek** [comment] 2016-10-03 08:47
> Are taskbar items QToolButtons?

Yes, they are `class LXQtTaskButton : public QToolButton`.

> If so, why don't they follow the active style plugin when NOT styled by QSS?

I'm not aware of any specific styling except the centering: https://github.com/lxde/lxqt-panel/blob/master/plugin-taskbar/lxqttaskbutton.cpp#L71

Note: you can use the DOM plugin to see properties of all panel widgets

**Comment by tsujan** [comment] 2016-10-03 08:57
> I'm not aware of any specific styling except the centering: https://github.com/lxde/lxqt-panel/blob/master/plugin-taskbar/lxqttaskbutton.cpp#L71

OK! I'll look into it later. And thanks for pointing to the relevant source file.

**Comment by palinek** [comment] 2016-10-03 09:03
Heh... actually a quick look on the code reveals that there is homemade paintEvent: https://github.com/lxde/lxqt-panel/blob/master/plugin-taskbar/lxqttaskbutton.cpp#L731.

I've never looked/touched this code.

**Comment by tsujan** [comment] 2016-10-03 09:13
> Heh... actually a quick look on the code reveals that there is homemade paintEvent: https://github.com/lxde/lxqt-panel/blob/master/plugin-taskbar/lxqttaskbutton.cpp#L731.

So, the wrong styling should happen there. I'll examine it as soon as I have time.

**Comment by tsujan** [comment] 2016-10-03 09:14
But that isn't related to this report.

**Comment by tsujan** [comment] 2016-10-03 14:33
Actually, taskbar buttons follow the style plugin *if their size isn't smaller than what a QToolButton needs*. When the text is too long, for example, they will be ugly. So, we need to elide their text according to their size.

**Comment by tsujan** [comment] 2016-10-03 15:49
I took a look at LXQtTaskButton's code. Unfortunately, it's very style unfriendly, as if it's written with the assumption that Fusion is the only existing style engine. It's a mess with Breeze and Oxygen, better with other styles but still not good. Fortunately, it's relatively OK with QSS but its text may still be cut if too long.

Unless it's rewritten, I can't think of any way to make it style friendly. Therefore, in my opinion, the system theme should be removed and, instead of it, a theme should be added that only styles the task buttons without setting any color.

**Comment by v-fox** [comment] 2016-10-03 16:04
> Unless it's rewritten, I can't think of any way to make it style friendly. Therefore, in my opinion, the system theme should be removed and, instead of it, a theme should be added that only styles the task buttons without setting any color.

WHAT ?! You're going to remove the last thing that works reliably ? Isn't it enough that every LXQt since 0.8 breaks something on every update ? I've heard on the next one screensaver d-bus interface will be nuked and now this.
If there is an issue with it now, relatively to others, it's the lack of icon on the main menu button but that can be fixed with customization setting.

Maybe it isn't a bad idea IF something tested as working actually will be there next time.

**Comment by tsujan** [comment] 2016-10-03 16:06
No need to get emotional! It was just one suggestion made by one person.

**Comment by agaida** [comment] 2016-10-03 16:09
+1 - and the time directly after a release is far the best time to break or re-think things, if needed.

**Comment by v-fox** [comment] 2016-10-03 16:20
Better to be emotional now than when new version comes out and all themes are broken and "system" is missing. For last 2 days I was calming myself down with a though "how good that there's was this system theme around..." while transferring LXQt from openbox & GTK+ style to kwin_x11 & Breeze style and trying out kwin_wayland in it (that didn't turn up that good), and you just decided to scare me like that.

**Comment by tsujan** [comment] 2016-10-03 16:29
Good news:
I succeeded in eliding text with a "dirty hack":

![eliding](https://cloud.githubusercontent.com/assets/981076/19045037/ba0e7e08-89a3-11e6-9884-c2fbfcd652b8.png)

It still needs some work.

**Comment by tsujan** [comment] 2016-10-03 16:35
Even Breeze seems to be happy:

![eliding1](https://cloud.githubusercontent.com/assets/981076/19045256/abef0de6-89a4-11e6-80bc-d0c834bb5013.png)

But there are still some problems.

**Comment by palinek** [comment] 2016-10-03 17:53
> I took a look at LXQtTaskButton's code. Unfortunately, it's very style unfriendly, as if it's written with the assumption that Fusion is the only existing style engine.

The whole taskbar plugin needs to be (re)implemented to proper Model/View ... but that's another story...

**Comment by stefonarch** [comment] 2016-10-03 18:19
In the meantime I [made](https://github.com/stefonarch/simple) system theme for me more "friendly", removing double frames on menus, add some spacing, styled notifyer which with  some widget styles is white-on-white. Only issue is the text in taskbar.

> WHAT ?! You're going to remove the last thing that works reliably ?

It's not that hard to save the system folder in ~/.local/share/lxqt/themes forever.

**Comment by tsujan** [comment] 2016-10-03 18:33
> The whole taskbar plugin needs to be (re)implemented to proper Model/View ... but that's another story...

That's *the* story ;) I agree completely. The sooner, the better!

**Comment by tsujan** [comment] 2016-10-03 20:56
I was able to add a simple workaround to Kvantum to "fix" LXQtTaskButton's text issue completely (I won't add it to the github Kvantum though):

![kvantum](https://cloud.githubusercontent.com/assets/981076/19053698/bd8581a6-89c8-11e6-927b-e5a2f14dd41e.png)

However, every workaround simply points to an unsolved problem. In this case, the problem is that `sizeFromContents(CT_ToolButton,...)` is much smaller that the actual size or, in other words, the text of QToolButton can't really belong to it ...

This is the end of my investigation.

**Comment by tsujan** [comment] 2016-11-23 15:24
Fixed by https://github.com/lxde/lxqt-common/pull/62. Reopen if it happens again!

**Closed by tsujan** 2016-11-23 15:24 UTC
Labels: lxqt-common
