### ISSUE TITLE
lxqt.org website support for SSL/TLS/HTTPS

### ISSUE THREAD

**Issue by fturco** [lxde/lxqt#1108] opened 2016-08-03 11:39 UTC
I'm not sure if I should file this bug here. Please forgive me if I made a mistake.

If I try connecting to https://lxqt.org/ I get the following error message from the Iceweasel browser:

> Your connection is not secure
> The owner of lxqt.org has configured their website improperly. To protect your information from being stolen, Iceweasel has not connected to this website.
> lxqt.org uses an invalid security certificate. The certificate is only valid for the following names: *.github.com, github.com, *.github.io Error code: SSL_ERROR_BAD_CERT_DOMAIN

[SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=lxqt.org) would give lxqt.org an A rating if the problem with the certificate was fixed.

> This server's certificate is not trusted, see below for details.

**Comment by tsujan** [comment] 2016-08-03 12:10
Same here.

**Comment by tsujan** [comment] 2016-08-03 12:12
Chromium and QupZilla say the same thing.

**Comment by jubalh** [comment] 2016-08-03 12:33
Of course they all say the same thing. Because its a certificate not signed by a CA.
However in my opinion this still is no problem.
Others might argue that one should switch to Lets Encrypt.

**Comment by tsujan** [comment] 2016-08-03 13:03
> However in my opinion this still is no problem

It IS a problem. If I didn't know about LXQt and Google led me to that site, I'd think twice before trying it.

**Comment by jleclanche** [comment] 2016-08-03 13:06
The site is hosted on github pages (which doesnt support ssl for custom domains).

I'm closing this; if someone wants to offer a permanent hardware home for lxqt.org please get in touch with @agaida. Otherwise, please ask github to support letsencrypt -- I already did, there's nothing more I can do.

**Comment by tsujan** [comment] 2016-08-03 13:19
@jleclanche 
As far as I know, even when a fix can't be made in LXQt (when the problem is in Qt, for example), we usually don't close an issue until it's fixed.

I reopened this because it's not good for the image of LXQt. Let's tell our users that we care, at least.

**Comment by f2404** [comment] 2016-08-03 13:40
Just for the record - google does not lead to https: the first search result for "lxqt" is http://lxqt.org/.

**Comment by agaida** [comment] 2016-08-03 20:28
the only thing right now would be to rewrite https to http - i see right now no problems in only using http to be true - or as @jleclanche mentioned - we need some hardware to host lxqt.org and lxde.org. I read a lot about possible other "solutions" but they only hide the real problem and do not solve anything. So we had two choices - host everything ourself or live with the fact that we can not deliver https in the moment.

**Comment by jleclanche** [comment] 2016-08-03 23:45
@tsujan Go on any site hosted by github pages with a custom domain, there's the exact same issue as here. And that's a lot of sites. [Here](https://www.django-rest-framework.org/) is an example of a project a lot more popular than LXQt that has the same issue.

https://gist.github.com/coolaj86/e07d42f5961c68fc1fc8

We can't set up an https redirect either. None of this is under our control. So again, unless someone is stepping up to host lxqt.org, there's nothing anyone here can do.

**Comment by tsujan** [comment] 2016-08-04 04:27
@jleclanche 
I understand that it is neither our fault nor under our control (https://github.com/lxde/lxqt/issues/1108#issuecomment-237234640).

**Comment by agaida** [comment] 2017-10-15 21:29
hmm - it might be possible to use hugo for a) importing the jekyll things and made the needed changes or b) switch the site to some github.io (with https://) - and just proxy it - second "solution" with all the nice things like performance penalties because of the proxy

**Comment by jleclanche** [comment] 2017-10-15 22:12
tbh just put cloudflare in front of it; the site itself is a stateless static blog and doesn't need strict e2e encryption. downloads.lxqt.org already has e2e and that's what matters.

**Comment by medicalwei** [comment] 2017-10-17 01:45
The main problem is that GitHub cannot provide SSL/TLS with custom domain
name.

Unless we use some proxies providing SSL like CloudFlare, or move to custom
hosting for static site, or GitHub finally solves the issue, then we have
to keep it as is.

http://lxde.org is facing the same problem.

Yao Wei

**Comment by agaida** [comment] 2017-10-17 16:58
The problem is a little bit deeper - using cloudflare would mean to transfer our complete DNS to Cloudflare - and i really don't like that idea. Second - if we would use cloudflare that would mean that the traffic between cloudflare and our visitors is in fact encrypted - but the traffic between cloudflare and github will be not - i guress that we really don't want that - claiming communication is secured when it is not?

**Comment by jleclanche** [comment] 2017-10-17 17:45
@agaida The lxqt.org site does not do anything that requires encryption further than cloudflare; downloads are on a separate server which *does* have full, strict encryption set up. Having used hugo before I'd also recommend against that if you go the self-hosted route.

IMO this is not worth spending lxqt's precious enough resources on. Using cloudflare as dns is fine.

**Comment by agaida** [comment] 2017-11-21 17:34
done.

**Closed by agaida** 2017-11-21 17:34 UTC
