### ISSUE TITLE
LXQt files in Pootle have a syntax error

### ISSUE THREAD

**Issue by SafaAlfulaij** [lxde/lxqt#831] opened 2015-09-26 15:48 UTC
When I tried to open PCManFM-Qt Arabic translation file in Qt Linguist, it reported about a syntax error in line 4, saying that the "context" tag mismatch.

**Comment by pmattern** [comment] 2015-09-26 22:23
Due to long-standing technical issues Pootle isn't used in LXQt so far. Adding or modifying translations is handled via local Git checkouts right now. A TS file is copied from the templates like pcmanfm-qt.ts if not available yet, edited, possibly via Qt Linguist, and  the result is submitted as pull request ("PR").
So the problem you're facing actually cannot be caused by Pootle. Attending the procedure depicted above ("local checkout") I cannot reproduce the message you state here.
You may want to depict the steps you took so that we can try and reproduce your findings.

**Comment by paulolieuthier** [comment] 2015-09-27 02:33
Pootle will come back, eventually.

**Comment by SafaAlfulaij** [comment] 2015-09-27 07:24
I downaloded this file http://pootle.lxde.org/export/?path=/ar/pcmanfm-qt/pcmanfm/translations/pcmanfm-qt_template-ar.ts. Just try to open it in Qt Linguist and it will report about syntax error.

I'll work on the Arabic translation and send a PR when I'm done. Thanks.

**Comment by pmattern** [comment] 2015-09-27 10:30
> I downaloded this file [...]

Yes, this one seems to be a bit outdated and not usable any longer.
There's already a file `./pcmanfm/translations/pcmanfm-qt_ar.ts` in Git that can be edited in Qt Linguist flawlessly here. So you should be able to use it, otherwise you may let us know.
Given the vast number of countries Arabic is spoken in I wonder whether country-specific translations may make sense. If they do you should copy the said file into a file pcmanfm-qt_ar_<alpha2 code>.ts and edit that one.

**Comment by jleclanche** [comment] 2015-10-17 14:10
Closing, pootle isnt in use right now. I tried my best but the ts support is simply not good enough right now :/ I'll upgrade Pootle and look into it again.

**Closed by jleclanche** 2015-10-17 14:10 UTC
