### ISSUE TITLE
Mouse settings unaffected by configuration upon boot.

### ISSUE THREAD

**Issue by eliaas** [lxde/lxqt#762] opened 2015-07-26 18:34 UTC
I have a mouse with high DPI. That means that I must use the lowest awailable sensetivity setting, This setting is applied, but resetted upon boot.

**Comment by Vladimir-csp** [comment] 2015-07-26 18:51
I think, this should be merged with #337.

**Comment by pmattern** [comment] 2015-07-26 19:09
@eliaas 
Can't confirm running latest VCS code on Arch Linux. Which OS are you using and how did you install LXQt?

@Vladimir-csp 
No. #337 is a complex feature request, this one is about a feature already available apparently malfunctioning. In theory implementing #337 could solve this issue as side-effect but it's not sure whether it will be implemented in the first place and even if it will there's no point in waiting for that before addressing this issue.

**Comment by Vladimir-csp** [comment] 2015-07-26 19:12
OK, but what component is currently responsible for applying xinput settings without opening lxqt-config-input?

**Comment by palinek** [comment] 2015-07-27 05:20
> OK, but what component is currently responsible for applying xinput settings without opening lxqt-config-input?

`lxqt-session` ... see [here](https://github.com/lxde/lxqt-session/blob/master/lxqt-session/src/sessionapplication.cpp#L80) & [here](https://github.com/lxde/lxqt-session/blob/master/lxqt-session/src/sessionapplication.cpp#L185).

**Comment by eliaas** [comment] 2015-07-29 18:15
@pmattern 
I downloaded Arch linux to USB stick. Booted, installed network, looked up LXQt upon Arch linux wiki and installed it accordingly to the documentation.
Another wierd thing i noticed is that keypress delay time also becomes resetted after some time. I fix it with "xset r rate 200" a few times a day. Can it have something to do with me suspending my machine, also a few times a day?

**Comment by eliaas** [comment] 2015-07-30 15:34
@pmattern
It should be added that the settings look like they have not been resetted, byt it is easy to tell that they have. It is hard to click on things again.
In the settings menu: if I just toch the values the settings are once more what they say they are.

**Comment by pmattern** [comment] 2015-07-31 09:47
Confirmed.
(My big mistake when trying to verify before was that I did so in a VM where the pointer devices' settings seem to be sort of superseded by the host's ones.)

Basically exactly like you say, `lxqt-config-input` keeps displaying the settings that were made before but these aren't applied. Tweaking again in a running session does work as expected.
No need to reboot, though. Re-starting the session is sufficient.
I'm under the impression that only sensitivity is affected while acceleration isn't. Hard to tell as there doesn't seem to exist a way to acquire the values that are actually valid. (Does anybody know more regarding the latter?)

Latest VCS checkout of all LXQt components on Arch Linux x86_64.

**Comment by palinek** [comment] 2015-07-31 09:55
> Hard to tell as there doesn't seem to exist a way to acquire the values that are actually valid. (Does anybody know more regarding the latter?)

@pmattern how about `xinput`?
```
$ xinput --list-props 11
Device 'USB Mouse':
        Device Enabled (139):   1
        Coordinate Transformation Matrix (141): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
        Device Accel Profile (268):     -1
        Device Accel Constant Deceleration (269):       1.300000
        Device Accel Adaptive Deceleration (270):       1.000000
        Device Accel Velocity Scaling (271):    10.000000
        Device Product ID (257):        7847, 17
        Device Node (258):      "/dev/input/event12"
        Evdev Axis Inversion (272):     0, 0
        Evdev Axes Swap (274):  0
        Axis Labels (275):      "Rel X" (149), "Rel Y" (150), "Rel Horiz Wheel" (266)
        Button Labels (276):    "Button 0" (290), "Button Unknown" (260), "Button Unknown" (260), "Button Wheel Up" (145), "Button Wheel Down" (146), "Button Horiz Wheel Left" (147), "Button Horiz Wheel Right" (148)
        Evdev Scrolling Distance (277): 1, 1, 1
        Evdev Middle Button Emulation (278):    0
        Evdev Middle Button Timeout (279):      50
        Evdev Third Button Emulation (280):     0
        Evdev Third Button Emulation Timeout (281):     1000
        Evdev Third Button Emulation Button (282):      3
        Evdev Third Button Emulation Threshold (283):   20
        Evdev Wheel Emulation (284):    0
        Evdev Wheel Emulation Axes (285):       0, 0, 4, 5
        Evdev Wheel Emulation Inertia (286):    10
        Evdev Wheel Emulation Timeout (287):    200
        Evdev Wheel Emulation Button (288):     4
        Evdev Drag Lock Buttons (289):  0
```

**Comment by pmattern** [comment] 2015-07-31 10:12
@palinek
Of course I had looked into this. But it doesn't seem to reflect the settings corresponding to "Acceleration" and "Sensitivity" in `lxqt-config-input` here. All values stay the same when those settings are tweaked and obviously in effect.

**Comment by Vladimir-csp** [comment] 2015-07-31 18:14
As I pointed out in #337,  'sensitivity' is a misleading name for acceleration threshold. ...which in turn could be vaguely presented in one of xinput props. Whatever these two 'traditional' parameters are came from, I suggest you do away with them.
What really matters are xinput props:
- "Device Accel Constant Deceleration", which is linear speed divider (must have in any case).
- "Device Accel Profile", which is an algorithm of acceleration, including disabled acceleration.
- "Device Accel Adaptive Deceleration", which controls additional precision of slow movement, AFAIK.
- "Device Accel Velocity Scaling", which is coefficient for acceleration profile.

**Comment by Vladimir-csp** [comment] 2015-07-31 18:46
http://www.x.org/wiki/Development/Documentation/PointerAcceleration/

**Comment by tsujan** [comment] 2015-08-20 07:25
> No need to reboot, though. Re-starting the session is sufficient.

Here, changing the acceleration, then setting it to its previous value and clicking the close button of "Keyboard and Mouse Settings" works without need to restarting the session.

**Comment by tsujan** [comment] 2015-08-20 09:05
Ah, it was just about a typo: the key strings should be changed to "acc_factor" and "acc_threshold" from "accel_factor" and "accel_threshold", respectively, in "sessionapplication.cpp".

**Comment by paulolieuthier** [comment] 2015-08-24 17:57
@eliaas, @Vladimir-csp and @pmattern can you please test it with current master? @tsujan, good catch, thanks!

**Closed** 2015-08-24 17:56 UTC
Labels: lxqt-session

**Comment by pmattern** [comment] 2015-08-24 22:20
@paulolieuthier 
FYI: testing impossible due to #793 right now.

**Comment by eliaas** [comment] 2015-08-25 19:24
thanks for letting us know.

**Comment by pmattern** [comment] 2015-08-26 09:03
Just applied the patch proposed by tsujan on top of an older commit to avoid the problem addressed in #793, see https://github.com/pmattern/lxqt-config/commits/fix-pointer. This does *not* seem to solve the problem.
With the mouse I'm using the only way to get an effect that's recognizable well is setting sensitivity to 110 which makes the pointer behave insanely. If I log out and in again the value is still 110 in lxqt-config-input but the mouse behaves normally again.

Btw. it seems to be necessary to remove settings `acc_{factor,threshold}` from $XDG_CONFIG_HOME/lxqt/session.conf.

But there's something else striking: the values of key `accel_factor` in $XDG_CONFIG_HOME/lxqt/session.conf, `[Mouse]` are the same as the ones from "Acceleration" in lxqt-config-input. But those from `accel_threshold` are 110-\<value of "Sensitivity" in lxqt-config-mouse\>.
This isn't really intended, is it?

**Comment by tsujan** [comment] 2015-08-26 09:54
@pmattern  What worked for me was changing "accel_" to acc_" in 'lxqt-session/src/sessionapplication.cpp". I said nothing about 'lxqt-config-input/mouseconfig.cpp'.

**Comment by tsujan** [comment] 2015-08-26 09:57
In other words, I didn't applied lxde/lxqt-config@e1f4357 here.

**Comment by paulolieuthier** [comment] 2015-08-26 12:20
Yeah, I didn't do exactly the same thing, but it should have fixed the issue.

**Comment by pmattern** [comment] 2015-08-26 12:25
Running lxde/lxqt-config@ab675b2 (changes in $XDG_CONFIG_HOME/lxqt/session.conf due to lxde/lxqt-config@e1f4357 withdrawn as well) and lxde/lxqt-session@225fd535af0a058 both the findings regarding sensitivity value 110 and the strange values of `acc_threshold` are persisting here.

**Comment by paulolieuthier** [comment] 2015-08-26 13:33
The commit fixed the problem in my machine.
