### ISSUE TITLE
lxqt-powermanagement: option to lock screen

### ISSUE THREAD

**Issue by Vladimir-csp** [lxde/lxqt#837] opened 2015-10-01 05:50 UTC
Please add separate option to enable/disable screen locking on suspend/hibernate.

**Comment by paulolieuthier** [comment] 2015-10-01 11:03
I've been planning that, but I'm not sure it should go in lxqt-config-powermanagement. It sounds more like session setting to me.

**Comment by jleclanche** [comment] 2015-10-31 00:45
@paulolieuthier session settings will eventually disappear I think.

**Comment by Vladimir-csp** [comment] 2015-11-25 16:20
> session settings will eventually disappear I think. 
@jleclanche, what do you mean by that?

**Comment by RalfJung** [comment] 2016-03-20 08:54
This looks like a duplicate of #775

**Closed** 2016-03-20 16:41 UTC
Labels: invalid/dup/rejected
