### ISSUE TITLE
Two different menus when right-clicking on desktop

### ISSUE THREAD

**Issue by raspi** [lxde/lxqt#1182] opened 2016-10-21 14:50 UTC
There's two different menus when right-clicking on desktop.

Linux devaus 4.8.2-1-ARCH #1 SMP PREEMPT Mon Oct 17 08:11:46 CEST 2016 x86_64 GNU/Linux
[pacman_Q.txt](https://github.com/lxde/lxqt/files/544594/pacman_Q.txt)
![desktop_menu2](https://cloud.githubusercontent.com/assets/132441/19602655/b67a8dba-97b6-11e6-9489-cc2d3fb1c18d.png)
![desktop_menu](https://cloud.githubusercontent.com/assets/132441/19602656/b67acb5e-97b6-11e6-8fc8-d124c2166358.png)

**Comment by stefonarch** [comment] 2016-10-21 15:03
One is the menu from openbox (window manager), the other the regulare LXQt menu.
In the latter choosing "Desktop preferences" → advanced (or from LXQt-configuration-center > Desktop) you can choose which one to display.

**Comment by pmattern** [comment] 2016-10-21 15:04
Most likely the black background you're using is masking #378, see in particular second to last section of [this comment](https://github.com/lxde/lxqt/issues/378#issuecomment-126693296).
It would be good if you could verify by using a wallpaper which makes #378 get manifest.

Btw. are you running that back background on purpose or is it because of some problem?

**Comment by pmattern** [comment] 2016-10-21 15:19
Alright. You may want to invoke the context menu once more over the wallpaper's and the black area respectively. I'm pretty sure the LXQt context menu as displayed in the second screenshot of the initial posting will be displayed over the wallpaper while it's the Openbox context menu as displayed in the first screenshot over that black area.

**Comment by raspi** [comment] 2016-10-21 15:26
Yes. I get different menu when clicking outside of background. So it's replicating issue #378. pacman -Q listing packages and versions is in the first post.

**Comment by pmattern** [comment] 2016-10-21 15:30
I'm closing this as duplicate of #378 then.

If there are results from testing LXQt on a Raspberry Pi 3 you can be sure we'd be all ears to hear about it. If you don't mind you can drop a mail on the [mailing list](https://github.com/lxde/lxqt/wiki/Contact) (or in the forum which we'll hopefully have in the not too distant future).

**Closed by pmattern** 2016-10-21 15:30 UTC
