### ISSUE TITLE
lxqt-qtplugin possible faulty

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#418] opened 2014-12-26 16:38 UTC
Some symptoms:
* running applications should change look if changes in lxqt-appearance occour - not or only partly the case right now (latest git, KF5 latest, Qt 5.4.0) - changes are applied after relogin
* keyboard indicator don't work as expected in Arch in arch the (aka C - dont work, N Work)
* maybe i'm wrong and this is KF5 related, this bug is only a reminder, discussed this behaviour with Paulo

**Comment by pmattern** [comment] 2015-01-02 09:57
Just a note regarding scroll lock:

At least on Arch Linux the actual scroll lock function doesn't seem to be enabled by default besides the scroll lock key is detected by xev. A corresponding finding is that none of those parameters 'modN' within the output of 'xmodmap [-pm]' has 'Scroll_Lock' assigned, rather one of them has no value assigned at all. After running
> xmodap -e 'add modN = Scroll_Lock'

(N corresponding to the one without value) the scroll lock function works. Also, both the keyboard LED and keyboard indicator's 'S' behave as expected.

**Comment by PCMan** [comment] 2015-01-21 04:08
@agaida the lxqt-qtplugin problems are actually caused by some incompatible changes in Qt 5.4.
It's already fixed in the latest lxqt-qtplugin. So I close this bug tracker.
For the keyboard indicator, it's not related to lxqt-qtplugin.
So if it's still a problem please open aother bug report for it.
Thanks!

**Closed by PCMan** 2015-01-21 04:08 UTC
Labels: upstream

**Comment by agaida** [comment] 2015-01-21 15:58
@pcman - i'm fine with it
