### ISSUE TITLE
lxqt-globalkeys / lxqt-config-globalkeys partly broken

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt#859] opened 2015-10-25 01:47 UTC
Try to setup a different key for the menu - like the "Windows-Key"
Result: 
Only Menu open works reliable, the new key will not be saved and Alt-F1 is back with the next login

Other glitches: open/close is slow - compared to show/hide the runner

**Comment by paulolieuthier** [comment] 2015-10-25 01:55
The time to open is actually a workaround: https://github.com/lxde/lxqt-panel/pull/131.

**Comment by agaida** [comment] 2015-10-25 16:16
ah, ok - forget about that one

**Comment by paulolieuthier** [comment] 2015-10-25 20:00
@palinek could you take a look at this one?

**Comment by palinek** [comment] 2015-10-26 16:28
There are 2 problems in here:
- the mainmenu plugin has it's own configuration for the shortcut which overrides the one configured in lxqt-config-globalkeys
- implementation of working with the shortcut text is wrong as it doesn't handle the 'asyncness' of shortcut registration (but this doesn't harm currently, because it resets the shortcut in all cases)

To fix this issue we should:
- remove configuration of shortcut from mainmenu plugin
- or remove the configuration of the shortcut from the plugin settins (configuration file)

**Comment by paulolieuthier** [comment] 2015-10-26 16:32
> or remove the configuration of the shortcut from the plugin/panel settings (configuration file).

This sounds more correct.

**Comment by palinek** [comment] 2015-10-26 21:08
@agaida please, confirm if it's correct now

**Comment by agaida** [comment] 2015-10-27 00:37
nope - it's not correct, but better - the menu opens with the shortcut provided by the global config, but it does not close if i hit the shortcut again - i would call this a regression, that worked with Alt-F1

**Comment by palinek** [comment] 2015-10-27 07:09
Hm... that's weird. Working as a charm here. Do I need to do something special to reproduce the "not hide" bug?

**Comment by agaida** [comment] 2015-10-27 09:11
will test this with a new installation today afternoon - the only thing i've done is to apply a new shortcut and a restart as it don't work right after applying.

**Comment by palinek** [comment] 2015-10-27 10:25
> the only thing i've done is to apply a new shortcut and a restart as it don't work right after applying.

Hm... the shortcut changes instantly here... no matter if changed via lxqt-config-globalkeys or via mainmenu configuration dialog.

**Comment by agaida** [comment] 2015-10-27 17:44
fine - build a new iso and started this in a VM: current behaviour:
Alt-F1 works like charm, if ich change this via GUI to a new shortcut the shortcut applies immediatly, but:
* show the menu works fine, hide not
* Switching back to Alt-F1 show and hide work like charm so i think that there is a part hard wired and overlooked

**Comment by agaida** [comment] 2015-10-27 19:15
so it seems that i'm a really bad boy who tested this with ununsual and really fugly combinations like Alt+plus and so on - and thats becomes more bad because i can create such shortcuts in the shortcut management. So far so good - these fugly combinations seems to work one way - for the open part, but not for the hide part.

**Comment by pmattern** [comment] 2015-10-27 19:56
I can confirm the findings @agaida posted in his second to last comment on Arch Linux running latest VCS checkouts of LXQt with one exception - using individual keyboard shortcuts that were set by `lxqt-config-globalkeyshortcuts` top open the menu to close the menu does work *sometimes*.
This in turn makes me wonder whether the problem could be related to #401 which I'm still seeing as well (besides I seem to be the only one for whatever reason...).
Btw. hitting `Esc` always closes the menu, too.

Also, what remains is the inconsistency `lxqt-config-globalkeyshortcuts` - configuration dialog of plugin-menu itself  ('Configure "Application menu"' in context menu of the icon).
E. g. if some particular shortcut to open the menu was set in `lxqt-config-globalkeyshortcuts`, say `Ctrl+H`, the plugin's dialog will still state `Alt+F1` as the current shortcut besides `Ctrl+H` is valid.

**Comment by palinek** [comment] 2015-10-27 22:03
There seems to be a discrepancy in string representation of the shortcut in globalkeys and the Qt's QKeySequence and I wasn't able to get the "old" workaround working... so made a new one in lxde/lxqt-panel#255

**Comment by agaida** [comment] 2015-10-27 22:11
cool

**Comment by palinek** [comment] 2015-10-30 15:24
@agaida can we close this?

**Comment by agaida** [comment] 2015-10-30 17:47
i think so

**Closed** 2015-10-30 18:53 UTC
Labels: high-priority, lxqt-panel, regression
