### ISSUE TITLE
Changing the theme in lxqt-config is not apply on lxq-panel, need restart

### ISSUE THREAD

**Issue by gilir** [lxde/lxqt#351] opened 2014-10-30 10:12 UTC
When you change the global theme in lxqt-config, the settings are not apply directly to lxqt-panel. You need to restart the panel for the settings to be effective.

**Comment by goetzc** [comment] 2015-01-01 23:03
Using the latest code from git (in Arch Linux and the set from the AUR), I also experience that the settings are not applied to the panel without a restart. Is there any information that I can provide to help find a possible cause?

**Comment by gilir** [comment] 2015-01-02 15:22
I don't know how to deal with this. If you want me to look more to this, I need clues to debug the issue.

**Comment by jleclanche** [comment] 2015-01-03 08:26
@gilir sorry, didn't notice I assigned you, that wasn't intended.

**Comment by PCMan** [comment] 2015-01-03 11:01
One of the potential cause of this problem is the use of Qss.
Qss is known to be problematic if you mix it with QStyle stuff.
Once a QWidget has a Qss style applied to it, it stops responding to any
other QStyle chane, including change of font.
Besides, QProxyStyle, which is used in many places of LXQt has exactly the
same issue.
I did quite some workarounds to overcome this problem so it should still
work.
Maybe some changes in Qt 5.4 break this?
Please assign this to me. I'll take a look at it.

**Comment by paulolieuthier** [comment] 2015-01-19 10:06
@PCMan is this fixed now?

**Comment by PCMan** [comment] 2015-01-19 12:08
Not yet. Working on that now. Just give me 1 or 2 days.
I know how to fix this.
We need to fix LXQt::Settings.

**Comment by pmattern** [comment] 2015-01-19 15:37
Given PCMan's last post I'm not sure whether it's relevant any more but running latest Git LXQt in an Arch Linux x86_64 VM I get the following findings (all from within LXQt Appearance) which I suppose to be related:
* widget style / icon theme / font
  * LXImage Qt --> first change applied at once, following ones only after restarting the application
  * PCManFM --> all changes only applied after restarting session
* LXQt theme: (as described by OP, that is background image always gets changed at once, panel only after starting new session
* Cursor: any number of changes always applied at once

**Comment by PCMan** [comment] 2015-01-19 15:56
I already have a fixed version of liblxqt in my local drive.
After some testing, I'll create a PR for the bug.
Just stay tunned.

**Comment by PCMan** [comment] 2015-01-19 16:06
The cause of this issue is the same as #441.
I already have a PR there. If it's merged, this issue can be closed as well.

**Comment by jleclanche** [comment] 2015-01-19 16:12
Closing as dup of #441

**Comment by agaida** [comment] 2015-01-19 16:16
only a few remarks to the setting thingy - i have tested that yesterday with a new siduction live iso - same behaviour as gilir describe it - the funny thing is: Same set of packages worked without any issues in the installed system

And thats why i mention the siduction live system - we use Qt 5.3.2 from debian and a set of KF5 packages i have mostly forked form (k)ubuntu back in time. This combination works for me™ - the funny thing is now: if i switch to my new arch with the newest AUR packages i have the same behaviour as in the siduction live iso. The difference is mostly the uses Qt version with should be 5.4 in Arch.

**Comment by PCMan** [comment] 2015-01-19 17:04
Yes, the problem is specifically induced by Qt 5.4.

**Comment by agaida** [comment] 2015-01-21 23:32
i don't want to be a dickhead - but: There is a regression with the currente lxqt-qtplugin and Qt 5.3.2. I released 0.8.0 with Qt 5.3 (siduction 14.1.0) and change of settings work with a live iso - the state now is: it don't work with a live iso but in an installed system. I noticed this behaviour first after the introduction of KF5 components. 

If someone wan't to jump in i can provide fresh built live isos and kvm virtual machines with spice access. @pcman @gilir @jleclanche @paulolieuthier @luis-pereira

**Comment by luis-pereira** [comment] 2015-01-23 15:28
@agaida I'm not sure I understood you correctly. What fails using the latest liblxqt and lxqt-qtplugin when using Qt 5.3 ?

**Comment by agaida** [comment] 2015-01-23 15:57
switching appearance if started from a live iso

**Comment by agaida** [comment] 2015-01-24 01:16
mhh - sorry for the noise - the failure happend if / is mounted as a overlayfs. Works perfect with aufs - so a wild guess is: failure in overlayfs or false mount options for the overlay. Not so nice, but i think there is not much we can or should do in the moment in our code

**Closed by agaida** 2015-01-24 01:16 UTC
Labels: invalid/dup/rejected, lxqt-panel

**Comment by agaida** [comment] 2015-01-24 02:33
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/882147
^^ known bug since 2011 - with a patch since late 2013. i think i will try the patch in my private kernel. if working i think we have a new patch in our kernel tree :)
