### ISSUE TITLE
lxqt-leave: frequent lack of icons due to current handling

### ISSUE THREAD

**Issue by tux3l** [lxde/lxqt#1252] opened 2017-02-01 23:51 UTC
I have seen, as i wanted to shutdown my pc, that the icon on the restart-button (in german "Neustart") is missing. It is a fresh installed system. 
Icon Theme is: Faenza-Ambiance
LXQt-Design: Patience

Screen of Leave window (here is the icon missing):
![leave](https://cloud.githubusercontent.com/assets/24856368/22531117/55267554-e8df-11e6-8646-a339a9902c82.jpg)

Screen of runner (icon is there so no problem here):
![runner](https://cloud.githubusercontent.com/assets/24856368/22531118/55289730-e8df-11e6-8477-e3e32c27e004.jpg)
Screen of startmenu (icon is there too):
![startmenu](https://cloud.githubusercontent.com/assets/24856368/22531119/552e6f52-e8df-11e6-9360-e8d7a52057ab.jpg)

##### Expected Behavior
There should be an Restart icon on the leave window.

##### Current Behavior
The Restart icon is missing on leave window. An all other places it is correct displayed.

##### Possible Solution
Add the picture to the button.

##### Steps to Reproduce (for bugs)
1. open the Leave window.

##### System Information

* Distribution & Version: 
* Kernel: 
Linux vm-pc 4.9.7-towo.1-siduction-amd64 #1 SMP PREEMPT siduction 4.9-13 (2017-02-01) x86_64 GNU/Linux
* Qt Version: 5.7.1
* liblxqt Version:  liblxqt0:amd64      0.11.1-1
* faenza-icon-theme version: 1.3.1-1
* Package version:

**Comment by agaida** [comment] 2017-02-01 23:54
confirmed - i don't know who or when the changes happen - but i know we did something about icon fallbacks and such things - i guess we had forgotten lxqt-leave

**Comment by agaida** [comment] 2017-02-01 23:57
@palinek @intialonso @luis-pereira - do you remember what and when we changed the theme behaviour?

**Comment by pmattern** [comment] 2017-02-02 00:59
It's not necessarily icon "Leave" but other icons may go missing as well depending on the theme in use, see e. g. Numix
![lxqt-leave_missing-icons](https://cloud.githubusercontent.com/assets/9860801/22532912/e891556a-e8ea-11e6-8ad8-de4c8ff00b45.png)
So indeed we either should by default chose icons available in a larger number of icon themes and/or improve the fallback handling when a particular icon isn't available in a theme.

**Comment by tsujan** [comment] 2017-02-02 01:20
Isn't this an icon theme problem? Isn't an icon theme without "system-suspend-hibernate.png/svg" or "system-suspend.png/svg" incomplete? If it is, this isn't an LXQt problem and the issue can be reported to the creator(s) of the theme.

Icon sets made for gtk DE's usually lack some icons needed by KDE, and conversely. An icon theme that covers important icons of both gtk DE's and kde can't cause such problems.

**Comment by intialonso** [comment] 2017-02-02 12:14
@agaida I dont remember any change in the icons behavior. Like @tsujan I think this is a theme issue.

**Comment by tsujan** [comment] 2017-02-02 13:59
With [this](https://store.kde.org/content/show.php?content=171350) set, for example:
![leave](https://cloud.githubusercontent.com/assets/981076/22552135/e0652920-e96c-11e6-8b91-f2f68fde05ec.png)

IMO, this issue can be marked as "invalid".

**Comment by tux3l** [comment] 2017-02-02 14:00
@pmattern ok next time ;)

@tsujan @intialonso usually this could be an theme issue, yes, but why do i have an icon for restart in the runner and start menu? i don't know if this is an fallback icon or the right one, but as user i would suggest that this icon is on all occurrences the same (okay, i know, it can be irritating with e.g. Numix as @pmattern shows us, because there are two icons missing which will end up with the same one for both options)

**Comment by tsujan** [comment] 2017-02-02 14:02
@tux3l 
The icon you have for restart in runner is the general fallback desktop file icon, which is used for all missing icons in desktop files, while the leave dialog only uses the real restart icon -- IMO, no meaningful fallback was possible there.

**Comment by tsujan** [comment] 2017-02-02 14:04
"application-x-desktop.png/svg" is used as fallback for desktop files.

**Comment by agaida** [comment] 2017-02-02 14:07
no - it isn't invalid - please mind that the right icons are in Start and runner. So it would be fine if it would work in leave too

**Comment by tsujan** [comment] 2017-02-02 14:10
> please mind that the right icons are in Start and runner.

As I tried to explain above, those aren't the right icons in @tux3l's case, but the falback "application-x-desktop". All screenshots here are about incomplet/complete icon sets, not about lxqt-session.

**Comment by agaida** [comment] 2017-02-02 14:25
in case we handle incomplete iconsets in the runner and in the panel we should do so in the session

**Comment by tsujan** [comment] 2017-02-02 14:37
Incomplete icon sets could be handled only to some extent and that would be a workaround. Yes, such a workaround can be implemented in `lxqt-session` → `leavedialog.cpp`. I can make a PR but, for example, take a look at the gnome icon theme: which icon do you propose instead of "system-reboot"? It only has logout and shutdown icons in its actions directory. Please propose some gnome icons for the leave dialog!

**Comment by tsujan** [comment] 2017-02-02 14:49
> We see the that things run not as expected with some themes - and we know that our users will see that too. What should they think?

When I started to make an icon set compatible with LXQt, I realized that I should cover important icons of both gtk and KDE. That wasn't surprising to me because LXQt was Qt-based and had GLib dependencies too. So, may answer is that they could think that their icon set is made for GTK, not LXQt.

That being said, I'm waiting for your proposed icons from gnome-icon-theme.

**Comment by tux3l** [comment] 2017-02-02 15:06
i found an "gnome-session-reboot"  image in faenza sources, the same look as the rest 
![gnome-session-reboot](https://cloud.githubusercontent.com/assets/24856368/22554552/c7ce7742-e960-11e6-9a73-576e5ea44f4b.png)
located in the sources of faenza-icon-theme in /Faenza/apps/*/gnome-session-reboot.png|svg
(i wonder why this is in apps not in actions ...)

**Comment by tsujan** [comment] 2017-02-02 15:23
I removed all traces of oxygen and used gnome-icon-theme under kde. Missing reboot, hibernation, .. icons were replaced by the desktop icon on KDE's menu, as they are in LXQt menus. The shutdown "dialog" showed a shutdown icon belonging to breeze, which is a *dependency* of KDE.

Therefore, this problem could be solved completely if we add some icons to lxqt-session, so that they're installed appropriately in the `/usr/share/icons/hicolor` with lxqt-session. This is like what kde does. @agaida, what do you think?

**Comment by agaida** [comment] 2017-02-02 15:30
this is a possible solution - i think the problem goes a little bit deeper - if we provide some falllbacks for some icons we should do system wide - because we should only have _one_ systemwide thing to handle that. It would not be the best idea that lxqt-leave behave other that the runner or the menu - however we worked around this cases.

**Comment by tsujan** [comment] 2017-02-02 15:42
> It would not be the best idea that lxqt-leave behave other that the runner or the menu

If lxqt-leave behaves like the runner or menu, those missing icons will be all replaced by "application-x-desktop". Is that acceptable to you? "application-x-desktop" is appropriate for all missing icons on a menu because menu icons are defined in *desktop files*, but it would look weird on the leave dialog.  Do you have another candidate in mind as a fallback?

The cleanest solution I can think of is adding some SVG icons to lxqt-session (SVG because of the small size -- and I have some light icons ready) and add libqt5svg5/qt5-svg to recommends.

**Comment by agaida** [comment] 2017-02-02 16:52
sounds good

**Comment by tsujan** [comment] 2017-02-02 17:04
OK. A folder can be added to the lxqt-session source with some icons and a cmake file that installs them in `/usr/share/icons/hicolor`. Then, the icons on the leave dialog will be taken from the active icon set and only if not existing, the hicolor icons will be used automatically (provided that the set inherits hicolor -- something all icon themes should do). Later we could add more icons if needed.

Anyone agaist this?

**Comment by tsujan** [comment] 2017-02-02 17:42
On second thought, I'm against it myself ;) Such general icons can't be added to hicolor because other apps may have added or might add them. hicolor is mostly fo app-specific icons.

So, a fallback -- or some fallbacks -- should be chosen, or LXQt should have its own icon theme in lxqt-session or separately so that lxqt-session depends on it. I'm with the fallback solution; but which fallback(s)?

**Comment by tsujan** [comment] 2017-02-02 18:43
Made https://github.com/lxde/lxqt-session/pull/91. I'm not an expert in cmake; it may need changes but works with gnome-icon-theme.

**Comment by luis-pereira** [comment] 2017-02-02 21:29
@tux3l It seems to be an theme/distribution issue.
I'm running Arch and it works just fine. Take a look:
![screen-2017-02-02-21-12-53](https://cloud.githubusercontent.com/assets/62877/22569000/dc4c94ec-e98d-11e6-98a3-d04c5949fb31.png)


@agaida There was no change in behaviour.
@tux3l `liblxqt` doesn't play a role here. `libxdgiconloader` do. Which version are you running ?

`Faenza-Ambiance` do not have a `system-reboot` icon. `Faenza-Dark` has. `Faenza-Ambiance` inherits `Faenza-Dark`. Do you have `Faenza-Dark` installed ?

**Comment by tux3l** [comment] 2017-02-02 22:16
@luis-pereira 
libqt5xdgiconloader2:   2.0.0-5

`faenza-icon-theme` as package includes all themes i think, because i can choose between:
- `Faenza`
- `Faenza-Ambiance`
- `Faenza-Dark`
- `Faenza-Darker`
- `Faenza-Darkes`
- `Faenza-Radiance`

**Comment by agaida** [comment] 2017-02-02 22:19
thanks luis - i will diff debians and arch faenza

**Comment by luis-pereira** [comment] 2017-02-02 23:10
@pmattern I have to check if the Numix behaviour is correct or there's something wrong.

**Comment by agaida** [comment] 2017-02-03 01:38
@luis-pereira it turns out that the arch package has some useful symlinks that are missed in the debian theme. Anyway, the fallback will be handy. And i think i should write some patches for some debian things, starting with faenza

**Comment by luis-pereira** [comment] 2017-02-03 16:48
@agaida Can you list those symlinks ? I want to check if there's something wrong with our icon engine.

@pmattern The Numix case has a bug. The missing icons should have defaulted to the `system` icon. as it did in the `Leave` menu. We are setting the icons in the `.ui` file. The generated code checks it's existance with `QIcon::hasThemeIcon()`, but it doesn't account for fallbacks. https://github.com/lxde/lxqt-session/pull/92 fixes it.

IMO having different icons for the same actions (as proposed in https://github.com/lxde/lxqt-session/issues/91) breaks consistency.

**Comment by agaida** [comment] 2017-02-05 11:26
@luis-pereira yes, have to diff the packages

**Comment by pmattern** [comment] 2017-02-05 16:46
@agaida @luis-pereira
> @agaida Can you list those symlinks ?

Taking the liberty to answer the question as I just ran into this, too. Arch Linux is providing the missing `system-reboot` by symbolic links
```
# ls -l $(locate system-reboot | grep -i faenza) 
lrwxrwxrwx 1 root root 24 11. Jul 2015  /usr/share/icons/Faenza/apps/16/system-reboot.png -> gnome-session-reboot.png
lrwxrwxrwx 1 root root 24 11. Jul 2015  /usr/share/icons/Faenza/apps/22/system-reboot.png -> gnome-session-reboot.png
[...]
```
see section `package()` of the [current PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/faenza-icon-theme).

**Comment by palinek** [comment] 2017-06-16 06:44
closing as upstream problem

**Closed by palinek** 2017-06-16 06:44 UTC
Labels: lxqt-session, upstream
