### ISSUE TITLE
panel not running on startup

### ISSUE THREAD

**Issue by rogerfranz** [lxde/lxqt#936] opened 2016-01-09 19:16 UTC
Just upgraded to Lubuntu 15.10 from 15.04. In 15.04, lxqt-panel ran on startup. I don't remember having to do anything to make that happen. In 15.10, lxqt-panel is not running on startup. I can run it manually, and it works fine once started (not sure I like the appearance, but it runs, and appearance is another issue anyway). Is there an install I'm missing? And, for that matter, what's the best way for me to get it to run automatically?

**Comment by pmattern** [comment] 2016-01-09 19:21
Would you please tell us how LXQt was installed on your system?

**Comment by rogerfranz** [comment] 2016-01-10 02:20
By means of Synaptic, from ppa, lubuntu-daily. lxqt-panel version, 0.10.0+201601071448~ub.

**Comment by pmattern** [comment] 2016-01-10 14:55
The panel gets launched as so-called LXQt Module by file `/etc/xdg/autostart/lxqt-panel.desktop`. It belongs to [lxqt-common](https://github.com/lxde/lxqt-common) which is provided by a package of the same name in PPA `ppa:lubuntu-dev/lubuntu-daily`.
This package is among other a dependency of metapackage `lxqt-metapackage`, see e. g. output of `$ apt-cache rdepends lxqt-common`.

That said I cannot reproduce your problem on a Lubuntu 15.10 instance that was installed from scratch and that's using the same PPA. (The latter is handled by the APT tools from the shell only but this really shouldn't make a diffference.)
`lxqt-metapackage` pulls `lxqt-common` which in turn provides the desktop entry file `lxqt-panel.desktop` as stated above and the panel gets launched as expected.

So this looks as if something has gone wrong when 15.04 was updated to 15.10 on your particular system. You may want to check the packages and files mentioned above.

**Comment by rogerfranz** [comment] 2016-01-10 18:40
So, here is that file, minus the language junk at the end:
[code]
[Desktop Entry]
Type=Application
Name=Panel
TryExec=lxqt-panel
Exec=lxqt-panel
OnlyShowIn=LXQt;
X-LXQt-Module=true
[/code]

There was a problem upgrading from 15.04 to 15.10; metapackage pulled in
sddm, which caused serious problems (I could not get to a login
screen!). I uninstalled sddm, and that particular problem went away. It
may not have completely uninstalled --

[code]
root@firefly:~# debconf-get-selections | grep sddm
sddm    sddm/daemon_name        string  /usr/bin/sddm
[/code]

I do receive a message after login: "system program problem detected,"
with a choice of report problem or not, but it gives no more details
than that and I can find no logs of whatever issue is being noted.

I suppose it's possible that reinstalling the lxqt suite would correct
the issue?

Roger



On 01/10/2016 06:55 AM, Peter Mattern wrote:
>
> The panel gets launched as so-called LXQt Module by file
> |/etc/xdg/autostart/lxqt-panel.desktop|. It belongs to lxqt-common
> <https://github.com/lxde/lxqt-common> which is provided by a package
> of the same name in PPA |ppa:lubuntu-dev/lubuntu-daily|.
> This package is among other a dependency of metapackage
> |lxqt-metapackage|, see e. g. output of |$ apt-cache rdepends
> lxqt-common|.
>
> That said I cannot reproduce your problem on a Lubuntu 15.10 instance
> that was installed from scratch and that's using the same PPA. (The
> latter is handled by the APT tools from the shell only but this really
> shouldn't make a diffference.)
> |lxqt-metapackage| pulls |lxqt-common| which in turn provides the
> desktop entry file |lxqt-panel.desktop| as stated above and the panel
> gets launched as expected.
>
> So this looks as if something has gone wrong when 15.04 was updated to
> 15.10 on your particular system. You may want to check the packages
> and files mentioned above.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/936#issuecomment-170355475>.
>

-- 
====================
Roger Franz
rogerfranz@gmail.com

**Comment by pmattern** [comment] 2016-01-11 00:39
File `/etc/xdg/autostart/lxqt-panel.destkop` as stated above seems all right. SDDM is working without issues on the said Lubuntu system here as well.
So this looks like some really serious problem due to updating from 15.04. to 15.10.

Reinstalling LXQt could eventually solve your problem but it's all but certain. If the problem due to the update involves some of LXQt's dependencies the panel may very well still fail after getting reinstalled.

Nevertheless this is certainly a downstream problem. So please understand that I personally haven't got the time to look into this deeper right now. Leaving the issue open for now so as to see whether someone of the others eventually has an idea.
Otherwise I can only encourage you to try and discuss that whole thing somewhere in the *buntu ecosystem. Sorry for that.

Notes
GitHub is using Markdown not BBCode. So it's e.g . ``` instead of both [code] and [/code]. Tried to fix this in your comment above but it didn't get parsed for whatever reason...
When I was using Debian there was virtually always some rather serious problem when trying to update from one release to another. So I ended up installing from scratch in the first place. At the end of the day saving user data and installing from scratch took less time than ironing the rough edges that always existed.

**Comment by paulolieuthier** [comment] 2016-01-11 01:41
@rogerfranz, could you replace the `Exec` entry with `sh -c "lxqt-panel > ~/log 2>&1"`? That may gather some information in `~/log`.

**Comment by rogerfranz** [comment] 2016-01-11 08:52
I reinstalled. Unfortunately, now I have different issues. Growl. Ah well.

**Comment by paulolieuthier** [comment] 2016-01-11 11:25
So the panel now starts?

**Comment by paulolieuthier** [comment] 2016-01-12 18:29
I'm closing this. @rogerfranz it the problem persists, please reopen.

**Closed by paulolieuthier** 2016-01-12 18:29 UTC
Labels: downstream, invalid/dup/rejected
