### ISSUE TITLE
LXQtPanel-taskbar can't handle some windows?

### ISSUE THREAD

**Issue by sixsixfive** [lxde/lxqt#937] opened 2016-01-10 22:50 UTC
If I minimize/iconify QMMP(http://qmmp.ylsoftware.com/) i got three taskbar entries

![untitled](https://cloud.githubusercontent.com/assets/3780774/12224547/06d4cb84-b7f4-11e5-9fe4-379897ea16f3.png)

I haven't encountered this issue on any other desktop so I guess its an LXQt issue

**Comment by palinek** [comment] 2016-01-11 07:32
I don't see such behaviour on current master. What version of lxqt-panel do you have installed?

**Comment by sixsixfive** [comment] 2016-01-11 18:31
ok i reinstalled the latest git version from AUR(0.10.0.36.g622e326) and now it won't show the equalizer but the playlist is still visible if minimized

**Comment by palinek** [comment] 2016-01-11 21:16
Sorry, but I'm still not able to reproduce this on my system (debian unstable) => I'm not able to guess the reason.

**Comment by palinek** [comment] 2016-02-12 21:51
I can see this behaviour (*playlist*, *equalizer* shown in taskbar when qmms is minimized) on my system. But I'm confused if it is the desired behaviour of qmmp or not.
The *playlist* and *equalizer* windows
- are of type [`NET::Utility`](http://api.kde.org/frameworks-api/frameworks5-apidocs/kwindowsystem/html/classNET.html#a4b3115c0f40e7bc8e38119cc44dd60e0) -> we do show such windows in [taskbar](https://github.com/lxde/lxqt-panel/blob/master/plugin-taskbar/lxqttaskbar.cpp#L102)
- have the hint [`NET::SkipTaskbar`](http://api.kde.org/frameworks-api/frameworks5-apidocs/kwindowsystem/html/classNET.html#a08dce7f5ea8a2a6d1d38aea3498f00ee) set when the *main* window is not minimized
- don't have the hint `NET:SkipTaskbar` set if the *main* window is minimized

In the qmmp's logic there is the logic for setting the `SkipTaskbar` following:
```c++
#ifdef QMMP_WS_X11
bool PlayList::event (QEvent *event)
{   
    if(event->type() == QEvent::WinIdChange ||
            event->type() == QEvent::WindowActivate ||
            event->type() == QEvent::Show ||
            event->type() == QEvent::ShowToParent)
    {   
        WindowSystem::ghostWindow(winId());
        WindowSystem::setWinHint(winId(), "playlist", "Qmmp");
    }
    return QWidget::event(event);
}
#endif
```
```c++
void WindowSystem::ghostWindow(WId win)
{ 
  Display* dsp = QX11Info::display();
  Window root = DefaultRootWindow(dsp);

  Atom win_state = XInternAtom(dsp, "_NET_WM_STATE", False);
  Atom win_state_add = XInternAtom(dsp, "_NET_WM_STATE_ADD", False);
  Atom win_state_settings[] =
  { 
    XInternAtom(dsp, "_NET_WM_STATE_SKIP_TASKBAR", False),
    XInternAtom(dsp, "_NET_WM_STATE_SKIP_PAGER", False)
  };
  XChangeProperty(dsp, win, win_state, XA_ATOM, 32, PropModeReplace,
      reinterpret_cast<unsigned char*>(&win_state_settings), 2);

  XEvent xev;
  xev.type = ClientMessage;
  xev.xclient.type = ClientMessage;
  xev.xclient.display = dsp;
  xev.xclient.window = win;
  xev.xclient.message_type = win_state;
  xev.xclient.format = 32;
  xev.xclient.data.l[0] = win_state_add;
  xev.xclient.data.l[1] = win_state_settings[0];
  xev.xclient.data.l[2] = win_state_settings[1];

  XSendEvent(dsp, root, false,
      SubstructureRedirectMask | SubstructureNotifyMask, &xev);
}
```

I can see following ways of "fixing" this:
- we will not show windows of type `NET::Utility` in taskbar at all (I don't know if this is correct and will not break showing of other needed windows)
- or in qmmp the logic will be fixed to
 - not fiddling with the *\_NET\_WM\_STATE\_SKIP\_TASKBAR* hint and set `Qt::WA_X11NetWmWindowTypeToolBar` for the *playlist* and *equalizer* `QWidget`
  - set the *\_NET\_WM\_STATE\_SKIP\_TASKBAR* hint correctly for *playlist* and *equalizer* windows also in case the main window is minimized

IMO the best way is to fix it in qmmp. It would be great if somebody from qmmp's team can have a look here and state his/her opinion...

**Comment by palinek** [comment] 2016-02-12 22:11
Submitted a ticket in qmmp -> https://sourceforge.net/p/qmmp-dev/tickets/844/. Let's wait for their statement.

**Comment by sixsixfive** [comment] 2016-02-13 14:18
at least you have it now, too

>Let's wait for their statement.

Ok but I still think its a pure LXQt issue since as mentioned I dont have this issue with QMMP on Xfce, LXDE, KDE, MATE, Tint2 or Fluxbox

**Comment by tsujan** [comment] 2016-02-13 15:03
@sixsixfive
Xfce, LXDE, MATE, Tint2 or Fluxb consult Xlib, either directly or through GTK+. We rely on KWindowSystem, hence the difference. Here, only KDE can be considered for comparison.

Now, I don't know whether KDE fully relies on KWindowSystem or it sometimes consults Xlib directly too. The latter case wouldn't be a "clean" approach, IMO.

**Comment by tsujan** [comment] 2016-02-13 15:19
And why can't I reproduce this issue?! I installed QMMP and this is the result:

![qmmp](https://cloud.githubusercontent.com/assets/981076/13028367/74715d12-d282-11e5-821e-ddbffb636239.png)

@palinek can it be because of Debian? My KF5 version is 5.16.0.

**Comment by sixsixfive** [comment] 2016-02-13 17:30
maybe, unstick windows grouping in the panel settings?

**Comment by tsujan** [comment] 2016-02-13 17:47
> unstick windows grouping in the panel settings?

Makes no difference: no multiple popup with window grouping and only one entry without it.
Your KF5 and Qt5 versions?

**Comment by sixsixfive** [comment] 2016-02-14 12:32
>Your KF5 and Qt5 versions?

5.18 & Qt is 5.5.1, lxqt-panel is still the same as above since i haven't used it in the last month(-->too buggy)

**Comment by tsujan** [comment] 2016-02-14 13:02
OK. lxqt-panel has been under heavy development by @palinek and others. I think you have no technical problem with making a clean lxqt-panel Arch package from GitHub for your personal use.

I'm just confused about one thing: it seems @palinek and I both use Debian and have the latest lxqt-panel but he said that he could reproduce the issue while I can't. Until we can pinpoint a difference, finding the real cause isn't easy. QMMP version? Mine is 0.9.7.

On the other hand, this is about QMMP. Do you see the same behavior in any other app (and *with the latest lxqt-panel*)?

**Comment by sixsixfive** [comment] 2016-02-14 13:33
>QMMP
my qmmp version is 1.06

>...both use Debian and have the latest lxqt-panel but he said that he could reproduce the issue while I can't.

maybe he uses sid or rc-buggy, since i have the same issue now on my devuan ceres/sid box

>I think you have no technical problem with making a clean lxqt-panel Arch package from GitHub for your personal use.

by all respect but whats the point of that statement? If it works for you - its ok, For myself: there are just too many tiny issues to get my stuff done effectively. (flock makes also muck). Logical consequence: use a different one(We are on linux so they exist hundreds of alternatives.)

**Comment by tsujan** [comment] 2016-02-14 13:48
> whats the point of that statement?

Clearly it's a simple direction in case you want to participate in solving a problem -- which apparently you don't and that's OK.

As for lxqt-panel being "too buggy" (your words), last summer, when I came to LXQT, it was the only part I had no serious problem with. However, I don't mean at all that your problems aren't real.

**Comment by palinek** [comment] 2016-02-14 20:44
> I'm just confused about one thing: it seems @palinek and I both use Debian and have the latest lxqt-panel but he said that he could reproduce the issue while I can't.

@tsujan are you on debian unstable?

> I can see this behaviour (playlist, equalizer shown in taskbar when qmms is minimized)

If you don't you observe this.... wait... the 0.9.X are Qt4 based, not?

I've got qmmp v1.0.5-1 (directly from [debian](https://packages.debian.org/sid/qmmp)) on my system...

**Comment by tsujan** [comment] 2016-02-14 23:20
> @tsujan are you on debian unstable?

~80% Testing and the remaining Unstable and Experimental, but KF5 and Qt5/Qt4 versions are the same in both, so there should be no difference.

> I've got qmmp v1.0.5-1

Ah, yes! I used the "multimedia.org" version. A few minutes ago, I installed v1.0.5-1 and saw the problem ONLY WHEN QMMP WAS MINIMIZED.

I also have an old Desktop computer with an updated Manjaro. There, the issue is observable whether QMMP is minimized or not.

With so much variation in the behavior of QMMP, I suspect it has some problem with KF5.

**Comment by tsujan** [comment] 2016-02-14 23:38
Moreover, check QMMP -> Settings -> Plugins -> User Interfaces -> Simple User Interface, and there will be no multiple taskbar entry. I think we're trying to fix an outside issue here, hence the confusion.

**Comment by palinek** [comment] 2016-02-15 08:05
> ONLY WHEN QMMP WAS MINIMIZED

yes, I've described that in the above [comment](#issuecomment-183501334)

**Comment by palinek** [comment] 2016-02-15 09:43
Closing as upstream issure... see the discussion in qmmp https://sourceforge.net/p/qmmp-dev/tickets/844/

**Closed by palinek** 2016-02-15 09:43 UTC
Labels: lxqt-panel

**Comment by palinek** [comment] 2016-02-15 13:32
@sixsixfive or anyone else who compiles Qt from source ... you can check if the following patch fixes the issue reported here

> This patch works for me: https://codereview.qt-project.org/#/c/149013/1

**Comment by tsujan** [comment] 2016-02-15 15:56
@palinek Nice catch! lxqt-panel was innocent after all ;)

**Comment by palinek** [comment] 2016-02-15 15:59
> @palinek Nice catch!

It wasn't me, I've just cited trialuser02's [comment](https://sourceforge.net/p/qmmp-dev/tickets/844/#d151)

**Comment by sixsixfive** [comment] 2016-02-24 16:20
@palinek 

thx, that works ;)
