### ISSUE TITLE
Undecorated windows and input problems in reopened session (logout)

### ISSUE THREAD

**Issue by nesnera** [lxde/lxqt#189] opened 2014-06-15 12:49 UTC
How to reproduce:
1) reboot computer and login (have a look at ".xsession-errors_OK")
2) run QTerminal. Window is decorated and you can write into the console
3) logout and login again
4) Error message about authentication agent is displayed for short moment (less the second). Run QTerminal. Windows is undecorated and there is no way how to write something into the CLI. (.xsession-errors_Error)
Interesting is I cannot interact with many applications by keyboard but there are exceptions e.g. editor "medit"
I've tried do the same with disabled PolicyKit (inspired by [this post](https://bugzilla.redhat.com/show_bug.cgi?id=657006#c6)) but without positive effect.

.xsession-errors_OK

```
LxQtGuiPlatformPlugin constructed 
LxQtGuiPlatformPlugin::systemIconThemeName() is called 
Theme: Cannot open file for reading: "/usr/share/lxqt/themes/a-mego/lxqt-session.qss" 
Setting special PATH  variable: "/usr/lib64/lxqt-xdg-tools:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/ln/.local/bin:/home/ln/bin" 
Environment variable PATH = /usr/lib64/lxqt-xdg-tools:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/ln/.local/bin:/home/ln/bin 
/home/abuild/rpmbuild/BUILD/lxqt-session-0.7.0/lxqt-session/src/sessionapplication.cpp : 89 Session "session" about to launch (default 'session') 
Environment variable BROWSER = firefox 
Environment variable TERM = qterminal 
"/home/ln/.config/lxqt/session.conf" 
xrdb: Xcursor.theme:Adwaita
Xcursor.size:18
Xcursor.theme_core:true

Object::connect: No such slot QEventLoop::exit()
start "/home/ln/.config/autostart/clipit-startup.desktop" 
start "/home/ln/.config/autostart/user-dirs-update-gtk.desktop" 
start "/etc/xdg/autostart/imsettings-start.desktop" 
start "/etc/xdg/autostart/lxpolkit.desktop" 
start "/etc/xdg/autostart/lxqt-config-randr.desktop" 
start "/etc/xdg/autostart/lxqt-desktop.desktop" 
start "/etc/xdg/autostart/lxqt-globalkeyshortcuts.desktop" 
start "/etc/xdg/autostart/lxqt-notifications.desktop" 
start "/etc/xdg/autostart/lxqt-panel.desktop" 
start "/etc/xdg/autostart/lxqt-policykit-agent.desktop" 
start "/etc/xdg/autostart/lxqt-powermanagement.desktop" 
start "/etc/xdg/autostart/lxqt-qlipper-autostart.desktop" 
start "/etc/xdg/autostart/lxqt-runner.desktop" 
start "/etc/xdg/autostart/lxqt-xscreensaver-autostart.desktop" 
start "/etc/xdg/autostart/nm-applet.desktop" 
LxQtGuiPlatformPlugin constructed 
LxQtGuiPlatformPlugin::systemIconThemeName() is called 
"qlipper.en_GB" 
Translator is not loaded "qlipper.en_GB" "/usr/share/qlipper/translations" 
start "/etc/xdg/autostart/pulseaudio.desktop" 
Process "Monitor configuration" ( LxQtModule(0xc82660) ) exited correctly. 
No systemtrayicon available
```

.xsession-errors_Error

```
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 20 (X_GetProperty)
  Resource id:  0x80006b
LxQtGuiPlatformPlugin constructed 
LxQtGuiPlatformPlugin::systemIconThemeName() is called 
Theme: Cannot open file for reading: "/usr/share/lxqt/themes/a-mego/lxqt-session.qss" 
Setting special PATH  variable: "/usr/lib64/lxqt-xdg-tools:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/ln/.local/bin:/home/ln/bin" 
Environment variable PATH = /usr/lib64/lxqt-xdg-tools:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/ln/.local/bin:/home/ln/bin 
/home/abuild/rpmbuild/BUILD/lxqt-session-0.7.0/lxqt-session/src/sessionapplication.cpp : 89 Session "session" about to launch (default 'session') 
Environment variable BROWSER = firefox 
Environment variable TERM = qterminal 
"/home/ln/.config/lxqt/session.conf" 
xrdb: Xcursor.theme:Adwaita
Xcursor.size:18
Xcursor.theme_core:true

start "/home/ln/.config/autostart/clipit-startup.desktop" 
start "/home/ln/.config/autostart/user-dirs-update-gtk.desktop" 
start "/etc/xdg/autostart/imsettings-start.desktop" 
start "/etc/xdg/autostart/lxpolkit.desktop" 
start "/etc/xdg/autostart/lxqt-config-randr.desktop" 
start "/etc/xdg/autostart/lxqt-desktop.desktop" 
start "/etc/xdg/autostart/lxqt-globalkeyshortcuts.desktop" 

** (lxpolkit:2091): WARNING **: Unable to register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject
start "/etc/xdg/autostart/lxqt-notifications.desktop" 
start "/etc/xdg/autostart/lxqt-panel.desktop" 
start "/etc/xdg/autostart/lxqt-policykit-agent.desktop" 
start "/etc/xdg/autostart/lxqt-powermanagement.desktop" 
start "/etc/xdg/autostart/lxqt-qlipper-autostart.desktop" 
start "/etc/xdg/autostart/lxqt-runner.desktop" 
start "/etc/xdg/autostart/lxqt-xscreensaver-autostart.desktop" 
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 20 (X_GetProperty)
  Resource id:  0x80006b
start "/etc/xdg/autostart/nm-applet.desktop" 
LxQtGuiPlatformPlugin constructed 
LxQtGuiPlatformPlugin::systemIconThemeName() is called 
An instance of qlipper is already running!
start "/etc/xdg/autostart/pulseaudio.desktop" 
Process "Monitor configuration" ( LxQtModule(0xa346a0) ) exited correctly. 
N: [pulseaudio] main.c: User-configured server at {8a001379ae864a9a98231de10f96aca8}unix:/run/user/1000/pulse/native, which appears to be local. Probing deeper.
xscreensaver: 13:58:24: already running on display :0 (window 0x1c00001)
 from process 1366 (ln@pb.domainln).
```

**Comment by palinek** [comment] 2017-04-24 20:08
Seems not reproducible and there were so many changes since the original report...closing. If new facts are ready, feel free to reopen.

**Closed by palinek** 2017-04-24 20:08 UTC
