### ISSUE TITLE
Icon images missed after LXQt installation

### ISSUE THREAD

**Issue by Audi-Hsu** [lxde/lxqt#493] opened 2015-02-10 17:57 UTC
After the LXQt (0.9.0) installation, some icon images on desktop and program menu are missed. Such as Qt Creator, refer to the screenshot.
![screenshot2](https://cloud.githubusercontent.com/assets/10945294/6132885/eeba07a4-b190-11e4-8e48-6ac7befce9ab.png)

I have checked the path "/usr/share/pixmaps" and can't find the corresponding image file which defined in the .desktop file of these application.

**Comment by pmattern** [comment] 2015-02-18 15:37
Running LXQt 0.9 or latest Git code on Arch Linux x86_64 I can't confirm your findings.

To further track your issue I'd suggest the following steps:
Your system is probably relying on freedesktop.org's Icon Theme Specification (http://standards.freedesktop.org/icon-theme-spec/latest/). Qt Creator isn't using a generic icon as defined by the specification but a genuine one. Genuine icon files go to /usr/share/icons/hicolor according to the specification.
You say you've already checked that icon file's name in Qt Creator's desktop entry file (*.desktop) in /usr/share/applications. So first look for the icon file in /usr/share/icons/hicolor. If it's lacking in this directory there's probably an issue regarding your system. You could then e. g. look into the content of Qt Creator's package as provided by your distribution and hence see whether it's missing in the package in general or on your system only.
Otherwise I'd suggest you install another desktop environment such as Xfce or KDE and look whether the problem is reproducible within that other desktop environment as well.

Also, further informations regarding your system - architecture, distribution and so an - would be helpful.

**Comment by jleclanche** [comment] 2015-02-27 23:42
@lxde/release-maintainers is lxqt-qtplugin working properly for you guys or did you have to patch it? I'm thinking I screwed up releasing that plugin on arch.

**Comment by sfalken** [comment] 2015-02-28 00:23
Nope, no patch needed.  on openSUSE and Fedora we just had to deal with the issue of forcing qt5 version on the running system to match the version qt-plugin was built with, due to private headers being used.

**Comment by sfalken** [comment] 2015-02-28 00:24
I have noticed where on Fedora, I'm missing a *bunch* of icons for things, doesn't seem to be as prevalent on openSUSE

**Comment by heliocastro** [comment] 2015-02-28 00:30
Tomorrow will be my off day just to LXQt. I will be polishing Fedora
packages and integrate the default theme.
This issue is already on the list to check.

Regards, Helio

**Comment by hterh** [comment] 2015-02-28 10:28
I noticed that many icons are now missing if switching to Adwaita. Other icon themes appear not affected.
![screenshot_2015-02-28_11-20-06](https://cloud.githubusercontent.com/assets/9549846/6425816/d95160ce-bf3c-11e4-9e5a-4488def2cf4a.png)

**Comment by tsujan** [comment] 2015-08-25 12:08
I see a general proplem when the icon of a desktop file is only in /usr/share/pixmaps. Not only such icons aren't shown in pcmanfm-qt, the configuration center doesn't give enough space to them.

In the image below, the first item under System Settings is galternatives, the icon of whose desktop file is in the pixmap folder. If I put the full icon path in its desktop file, it'll be shown correctly but that's not a real solution. The same was true for the Kvantum icon but I included it in the icon theme.

![config-center](https://cloud.githubusercontent.com/assets/981076/9466099/682ef7fc-4b47-11e5-8728-79dda9b422da.png)

Which LXQT source should I examine to see if I can fix this?

**Comment by palinek** [comment] 2015-08-25 12:16
@tsujan for the configuration center i've made a commit (for testing...) in https://github.com/lxde/lxqt-config/commits/cc_item_size... can you try, if it helps?

**Comment by tsujan** [comment] 2015-08-25 12:43
I applied just your commit and nothing else since 2015/08/19, and yes, it fixed the config center problem. Thanks!

**Comment by agaida** [comment] 2015-08-25 14:26
@tsujan - nice catch, thanks

**Comment by tsujan** [comment] 2015-08-25 14:31
@agaida - I didn't do anything! It was palinek's commit.I just tested it.

**Comment by palinek** [comment] 2017-06-12 10:46
closing... as the same was discussed in #976

**Closed by palinek** 2017-06-12 10:46 UTC
Labels: polish
