### ISSUE TITLE
.desktop file on desktop lacking icon

### ISSUE THREAD

**Issue by gjedeer** [lxde/lxqt#389] opened 2014-11-22 21:16 UTC
I wanted to have a desktop shortcut for claws-mail, so I copied /usr/share/applications/claws-mail.desktop to ~/Desktop. LXQT is displaying a generic question mark icon. This happens with all .desktop files I tried.

The icon definition in the .desktop file is as following:

    Icon=claws-mail

The icon file exists:

    ➜  ~  find /usr/share/icons/ -name claws-mail\*
    /usr/share/icons/lubuntu/apps/24/claws-mail.svg
    /usr/share/icons/lubuntu/apps/16/claws-mail.svg
    /usr/share/icons/lubuntu/apps/48/claws-mail.svg
    /usr/share/icons/lubuntu/apps/22/claws-mail.svg

    ➜  ~  apt-cache policy lxqt-session
    lxqt-session:
      Installed: 0.8.0+bzr217+201411071933~ubuntu14.04.1

**Comment by pranavg189** [comment] 2015-01-04 18:14
This happens on my system too. The .desktop file for Codeblocks show a blank page icon instead of showing codeblocks icon...Anyone knows how to solve it...?

**Comment by Thorn-Inurcide** [comment] 2015-01-04 22:53
I built mine from git and can't reproduce this either, *.desktop icons are working as expected when I copy and paste them to the desktop

**Comment by jleclanche** [comment] 2015-02-08 20:32
Yes this was fixed in libqtxdg a while back.

**Closed by jleclanche** 2015-02-08 20:32 UTC
