### ISSUE TITLE
Country flag icon for keyboard layout indicator

### ISSUE THREAD

**Issue by Ilya87** [lxde/lxqt#1404] opened 2017-11-11 16:31 UTC
##### Feature request
IMO it would be right to have an option for country flag icon for active keyboard layout. This way of indication would be much comfortable then see only two letters of language. Icons can be taken from qxkb.

##### System Information
 Latest Arch Linux x86_64: 
 Qt 5.9.2
liblxqt 0.12:  
lxqt-panel from git master :

**Comment by palinek** [comment] 2017-11-12 14:03
Duplicate of #1162

**Closed by palinek** 2017-11-12 14:03 UTC
Labels: accessibility
