### ISSUE TITLE
Can't populate lxqt-panel quicklaunch widget via system-wide config file

### ISSUE THREAD

**Issue by lbssousa** [lxde/lxqt#1091] opened 2016-07-12 11:57 UTC
I'm building an openSUSE appliance in SUSE Studio based on LXQt 0.10.0. I'm trying to customize default lxqt-panel layout following this `/etc/xdg/lxqt/panel.conf` contents:
```
panels=panel1

[panel1]
plugins=mainmenu,desktopswitch,quicklaunch,taskbar,tray,statusnotifier,mount,volume,networkmonitor,clock,quicklaunch2
position=Bottom
desktop=0

[mainmenu]
alignment=Left
type=mainmenu

[desktopswitch]
alignment=Left
type=desktopswitch

[quicklaunch]
alignment=Left
apps\1\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\2\desktop=/usr/share/applications/chromium-browser.desktop
apps\3\desktop=/usr/share/applications/org.kde.kcalc.desktop
apps\4\desktop=/usr/share/applications/qterminal.desktop
apps\size=4
type=quicklaunch

[taskbar]
alignment=Left
type=taskbar

[tray]
alignment=Right
type=tray

[statusnotifier]
alignment=Left
type=statusnotifier

[mount]
alignment=Right
type=mount

[volume]
alignment=Right
device=0
type=volume

[networkmonitor]
alignment=Right
type=networkmonitor

[clock]
alignment=Right
type=clock

[quicklaunch2]
alignment=Right
apps\1\desktop=/usr/share/applications/lxqt-leave.desktop
apps\size=1
type=quicklaunch
```

However, my `quicklaunch` widgets are not populated with only this global config. In order to get my launchers properly placed, I need to copy over my `[quicklanuch*]` settings to a per-user config file `~/.config/lxqt/panel.conf` like this one:
```
[General]
__userfile__=true

[quicklaunch]
alignment=Left
apps\1\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\2\desktop=/usr/share/applications/chromium-browser.desktop
apps\3\desktop=/usr/share/applications/org.kde.kcalc.desktop
apps\4\desktop=/usr/share/applications/qterminal.desktop
apps\size=4
type=quicklaunch

[quicklaunch2]
alignment=Left
apps\1\desktop=/usr/share/applications/lxqt-leave.desktop
apps\size=1
type=quicklaunch
```

**Comment by Vladimir-csp** [comment] 2016-07-12 12:06
offtopic: why desktop entries are represented by full paths? Should be just names with XDG hierarchy support.

**Comment by lbssousa** [comment] 2016-07-12 13:11
@Vladimir-csp This is the way LXQt itself writes them in `~/.config/lxqt/panel.conf` when I drag the shortcuts to panel's quicklaunch widget. I'm just following it.

**Comment by pmattern** [comment] 2016-07-12 18:00
I can confirm your findings exactly as depicted above running 0.10 on Arch Linux but the problem is fixed in current master.
Depending on your needs you may want to wait until release 0.11 is out which will be rather soon or temporarily use Git checkouts as well. A backport of the commit(s) in question will probably be rather cumbersome if possible at all since lots of changes have taken place under the hood since 0.10 was released.

**Closed by pmattern** 2016-07-12 18:00 UTC
