### ISSUE TITLE
After leaving full-screen mode, the window moves to main monitor

### ISSUE THREAD

**Issue by rscafi** [lxde/lxqt#635] opened 2015-05-06 13:08 UTC
When using multiple monitors, exiting full-screen mode causes the window to move to the main monitor, instead of staying on the monitor where it originally was.
(tested with fullscreen mode of Google Chrome, PhpStorm and Sublime Text)

Using Lubuntu 14.10 with lxqt installed via apt-get.

**Comment by pmattern** [comment] 2015-05-06 15:38
Hm.
Can't confirm your findings here.
Placing windows is actually the window manager's job. Which one are you using, including version?

**Comment by rscafi** [comment] 2015-05-06 19:20
I'm using Openbox 3.5.2.
And I used the built-in Monitor Settings from lxqt to configure my monitors.

**Comment by pmattern** [comment] 2015-05-07 00:01
If you set / saved your settings once using lxqt-config-monitor (GUI "Monitor Settings") you could post .config/autostart/lxqt-config-monitor-autostart.desktop here. Also, ~/.config/openbox/rc.xml would be helpful, maybe better on gist.github.com due to its size.

**Comment by rscafi** [comment] 2015-05-07 11:10
Here it is. Thanks for the help so far.
https://gist.github.com/rscafi/11eec5bc0bc8786c33ba

**Comment by rscafi** [comment] 2015-05-07 11:12
I also noticed another bug, perhaps belonging to openbox too:
System dialogs (like when you confirm that you want to shutdown the computer) shows up on the wrong monitor (not main one), but using window's center position from main monitor, really weird.

**Comment by selairi** [comment] 2015-05-08 10:32
It could be the primary output settings. Could you be so kind to
change primary output settings and test it again?

Thanks

2015-05-07 13:12 GMT+02:00, Ravan Scafi <notifications@github.com>:

**Comment by jleclanche** [comment] 2015-05-08 10:48
I've had the same issue with chrome. I think it's actually a chrome bug, since it does its own window management.

**Comment by pmattern** [comment] 2015-05-08 14:41
In the meantime I could reproduce this issue's actual problem with any arbitrary application window like so: maximize window - drag it to another monitor - restore regular size ("Restore" in menu in the upper left corner of the window or middle icon in the upper right corner).
Seen on a dual-monitor system, monitors connected to VGA and DVI output of a single graphics card and with different resolutions that the window size was adjusted to when dragged to the other monitor. Maximizing before dragging to the other monitor seems crucial as problem can't be seen if window is in "restored" size before dragging. Things that did not matter are which monitor was the primary one (xrandr --primary), placement of monitors within the screen (xrandr --pos or --{right,left}-of) and direction in which the window was moved (VGA --\> DVI or the other way around).
But all those findings were the very same in an Openbox session without desktop environment.

Regarding the placement of dialog windows I'd bet it's related to settings \<monitor\> and \<primaryMonitor\> in rc.xml and their corresponding topics "Placing Windows - Prefer to place new windows on" and "Primary Monitor - Primary monitor" in ObConf - Windows (tab at the left) respectively. Also note the corresponding comments in rc.xml.

On a side note, the rc.xml you've been posting comprises setting \<center\> which isn't valid in Openbox 3.5.2 (see [Openbox bug 5946(https://bugzilla.icculus.org/show_bug.cgi?id=5946), corresponding patch included in VCS after 3.5.2 was released only).
Mentioning as this could mean you're using an rc.xml from an outdated Openbox version which in turn could give rise to problems. Maybe start over after deleting the current rc.xml?

You may want to try to reproduce all that stuff so as we can figure out whether or not your findings are due to LXQt.

**Comment by palinek** [comment] 2015-06-03 21:52
...closing as this issue is related to window manager and not LXQt itself.

**Closed by palinek** 2015-06-03 21:52 UTC
Labels: multi-monitor
