### ISSUE TITLE
Broken .desktop files

### ISSUE THREAD

**Issue by filat0ff** [lxde/lxqt#1007] opened 2016-04-01 08:10 UTC
In files 
lxqt-config.desktop
lxqt-config-appearance.desktop
lxqt-config-file-associations.desktop
lxqt-config-input.desktop
lxqt-config-monitor.desktop

When launch update-desktop-database I see that message:
"Could not parse file "/usr/share/applications/lxqt-config.desktop": Key file contains line 'Binary file /build/lxqt-config/src/lxqt-config-0.10.0/src/translations/lxqt-config_ar.desktop matches' which is not a key-value pair, group, or comment"

LXQT-0.10.0-4

**Comment by Esclapion** [comment] 2016-04-01 09:21
I confirm for lxqt-config.desktop, there is junk in it, easy to see. I took the preceeding one to solve it.

**Comment by pmattern** [comment] 2016-04-01 19:51
This is caused by some well-known problem affecting grep which is fixed in latest VCS code. This issue is hence a duplicate.

Upstream issue is #957, downstream Arch Linux can be found at https://bugs.archlinux.org/task/48754.

Note a simple workaround is to re-compile package lxqt-config on a system with some arbitrary UTF-8 locale.

**Closed by pmattern** 2016-04-01 19:51 UTC

**Comment by Esclapion** [comment] 2016-04-01 20:12
It's to note than the Arch binary packages of jleclanche have this problem, and it's too late for the user.

**Comment by jleclanche** [comment] 2016-04-01 20:14
I'm fixing it.
