### ISSUE TITLE
Using the new XdgIconLoaderEngine, Qt4 status notifier items have no icon

### ISSUE THREAD

**Issue by paulolieuthier** [lxde/lxqt#1081] opened 2016-06-28 12:46 UTC
[sni-qt](https://launchpad.net/sni-qt) turns Qt4's `QSystemTray` items into `StatusNotiferItem`s. After the new `XdgIconLoaderEngine` addition to our Qt plugin (lxde/lxqt-qtplugin#10), those icons are no longer visible.

This is what happens (AFAIK):
* lxqt-panel asks the application for a icon name, and then asks `QIcon` for that icon [(source)](https://github.com/lxde/lxqt-panel/blob/master/plugin-statusnotifier/statusnotifierbutton.cpp#L139).
* `QIcon` creates the icon through our engine [(source)](https://github.com/qt/qtbase/blob/dev/src/gui/image/qicon.cpp#L1182).
* `XdgIconLoaderEngine` can't find sni-qt powered icons, because those are in private, custom folders.
* Somehow the `QIcon` instance created is valid [(source)](https://github.com/qt/qtbase/blob/dev/src/gui/image/qicon.cpp#L1224) and lxqt-panel won't search for the icons in the custom theme folders because it thinks the icons were found in the system theme.

This needs to be fixed in the current milestone.

**Comment by paulolieuthier** [comment] 2016-06-28 12:59
The weird thing is that I (still) don't see any difference between `XdgIconLoaderEngine` and [`QIconLoaderEngine`](https://github.com/qt/qtbase/blob/dev/src/gui/image/qiconloader.cpp#L499).

**Comment by tsujan** [comment] 2016-06-28 14:05
If that's the case, it should be fixed before the next release, IMHO. Sorry that I can't help (I didn't have time to try XdgIconLoaderEngine and still use my old trick https://github.com/lxde/lxqt-qtplugin/pull/9). I may be totally lost asking this but how could a Qt5 icon loader affect Qt4 apps? Here, without XdgIconLoaderEngine, I see Skype's icon among status notifier items.

**Comment by paulolieuthier** [comment] 2016-06-28 14:10
Well, that's actually a good question. I think that's because lxqt-panel is the one using XdgIconLoaderEngine, and the Qt4 apps are using the StatusNotifierItem protocol.

**Comment by paulolieuthier** [comment] 2016-06-28 14:14
The way I see it, the problem is not about Qt4, or the SNI protocol. It's about the icon loader engine stating that it found icons that it didn't find.

**Comment by luis-pereira** [comment] 2016-06-28 18:45
@paulolieuthier Can you give me an example ?

**Comment by paulolieuthier** [comment] 2016-06-28 18:49
KeePassX and MEGASync.

**Comment by luis-pereira** [comment] 2016-06-28 18:55
KeePassX is working for me
![screen-2016-06-28-19-54-22](https://cloud.githubusercontent.com/assets/62877/16428520/2f5d77a8-3d6a-11e6-96db-b63634defe39.png)

**Comment by stefonarch** [comment] 2016-06-28 19:32
Keepassx works  too here, but appset-qt is not visible, was always wondering why

**Comment by palinek** [comment] 2016-06-28 20:04
I'd would like to sort this out, but both megasync & keepasx are working here...

**Comment by stefonarch** [comment] 2016-06-28 20:14
I'm still somewhat confused about the differences between    tray icons and status-notifier icons, is this issue about both? Because keepassx, recordmydesktop and qstardict do not notify anything and are in teg systray.

**Comment by luis-pereira** [comment] 2016-06-28 20:16
I'm in the same situation as @palinek. keeppassx, megasync, appset-qt and skype work Ok im my system.
![screen-2016-06-28-21-11-54](https://cloud.githubusercontent.com/assets/62877/16430758/2ef8e954-3d75-11e6-820b-d42fef49a333.png)

**Comment by stefonarch** [comment] 2016-06-28 20:24
Skype always worked, megasync too. So the only one for me is appset-qt which is invisible.

**Comment by paulolieuthier** [comment] 2016-06-28 21:43
Are you all using the lastest version of Qt, as in Arch?

**Comment by luis-pereira** [comment] 2016-06-28 21:58
@paulolieuthier I'm running Arch  qt5-base 5.6.1-2

**Comment by pmattern** [comment] 2016-06-28 22:57
@luis-pereira 
Some strange findings with QupZilla's UI here are suggesting this *could* be related to Qt 5.7.

**Comment by stefonarch** [comment] 2016-06-29 06:20
I'm running latest arch + lxqt stuff. Clearly I remember that when I installed appset-qt  June 2 the icon in tray was working and stopped after, that was still with qt5.6; looking at pacman's log this would not be related to qtplugin, at least no directly
.`[2016-05-01 07:54] upgraded lxqt-qtplugin-git (0.10.0.1.g2b494a5-1 -> 0.10.0.5.g4a3d790-1)
[2016-05-09 09:51] reinstalled lxqt-qtplugin-git (0.10.0.5.g4a3d790-1)
[2016-05-21 12:51] upgraded lxqt-qtplugin-git (0.10.0.5.g4a3d790-1 -> 0.10.0.7.g3ad671e-1)
[2016-06-07 19:14] reinstalled lxqt-qtplugin-git (0.10.0.7.g3ad671e-1)
`

**Comment by luis-pereira** [comment] 2016-06-29 22:55
@paulolieuthier Just updated to Qt 5.7.0 on Arch. Now I'm able to reproduce it.

**Comment by luis-pereira** [comment] 2016-07-10 13:10
Can we close this ? After lxde/lxqt-qtplugin@411f696ef699be2bf00d67344cd6c86cba04e4db everything works fine to me.

**Comment by stefonarch** [comment] 2016-07-10 14:46
The only program which wasn't displayed here correctly was appset-qt, I notice now that it works even before   upgrading lxqt-qtplugin-git (0.10.0.7.g3ad671e-1 -> 0.10.0.8.g411f696-1)
So yes, for me everything works fine.

**Comment by paulolieuthier** [comment] 2016-07-10 19:24
Running lastest Arch, lxqt-panel and lxqt-qtplugin. Qt4 (sni-qt) apps are still icon-less.

**Comment by stefonarch** [comment] 2016-07-10 19:29
After full upgrade appset-qt has still problems, but I think that it's fault.
 skype, megasync, qt-recordmydesktop icons are all working.

**Comment by luis-pereira** [comment] 2016-07-12 10:53
I'm running:
- Arch with Qt 5.7.0
- lxqt-qtplugin master branch

**Not running:**
- sni-qt

Resulting in:
![screen-2016-07-12-11-48-59](https://cloud.githubusercontent.com/assets/62877/16764653/42614ed4-4827-11e6-8c67-3149692a9f5a.png)

**Comment by paulolieuthier** [comment] 2016-07-12 14:34
Of course it works if I unninstall sni-qt, but then Qt4 apps will appear in the old system tray, which is not what we want. If I checkout lxde/lxqt-qtplugin@4a3d790df0df9fe332d90cd30fbe759cdceb219a (the commit before the commit that introduces the new icon loader engine), it works perfectly.

@luis-pereira does it work for you **with** sni-qt installed?

**Comment by stefonarch** [comment] 2016-07-12 14:53
I missed something, I was never running sni-qt, as it's dependency was optional. Running it I see same problems.

**Comment by paulolieuthier** [comment] 2016-07-21 02:21
After another update, transmission-qt, which is Qt5-based (no sni-qt), is iconless as well:

![Uploading screenshot.png…]()

**Comment by luis-pereira** [comment] 2016-07-30 00:58
@paulolieuthier Can you pls test with the libqtxdg backport branch ?
I get this:
![screen-2016-07-30-01-56-01](https://cloud.githubusercontent.com/assets/62877/17267042/fbdbb096-55f8-11e6-9113-a4623b6ba715.png)
Although something strange happens with the Breeze icon theme.

p.s. Long delay. Real life gets in the way.

**Comment by paulolieuthier** [comment] 2016-07-30 02:51
Transmission is back, but the sni-qt apps are still not, unfortunately:

![screenshot_20160729_234922](https://cloud.githubusercontent.com/assets/1238157/17267729/339ab00c-55e7-11e6-8f99-7e282a852dcb.png)

**Comment by tsujan** [comment] 2016-07-30 03:07
After upgrading LXQt last week, I forgot to say that all sni-qt apps are OK here.

**Comment by luis-pereira** [comment] 2016-07-30 03:31
Actually I didn't debug  the statusnotifier thing, yet.

**Comment by tsujan** [comment] 2016-07-30 03:35
Is it possible that this difference in results is due to the icon theme? On Debian, I don't have breeze and everything is OK. On Manjaro, when breeze is activated, I see no problem but there I have only one sni-qt app.

**Comment by paulolieuthier** [comment] 2016-07-30 13:11
I had already tried with other icon themes, same thing.

**Comment by paulolieuthier** [comment] 2016-07-30 13:36
The following patch is a workaround to the bug:

```diff
diff --git a/plugin-statusnotifier/statusnotifierbutton.cpp b/plugin-statusnotifier/statusnotifierbutton.cpp
index 0aa68c4..adc87a6 100644
--- a/plugin-statusnotifier/statusnotifierbutton.cpp
+++ b/plugin-statusnotifier/statusnotifierbutton.cpp
@@ -136,9 +136,8 @@ void StatusNotifierButton::refetchIcon(Status status)
         QIcon nextIcon;
         if (!iconName.isEmpty())
         {
-            if (QIcon::hasThemeIcon(iconName))
-                nextIcon = QIcon::fromTheme(iconName);
-            else
+            nextIcon = QIcon::fromTheme(iconName);
+            if (nextIcon.isNull())
             {
                 QDir themeDir(mThemePath);
                 if (themeDir.exists())
```

The thing is that `QIcon::hasThemeIcon` is always returning `true` with our icon engine.

**Comment by luis-pereira** [comment] 2016-07-30 14:33
@paulolieuthier Thanks for the great clue. When real life gets a little bit out of the way (begining of next week) it will be much faster.

**Comment by paulolieuthier** [comment] 2016-07-30 16:11
Although lxde/libqtxdg#99 fixes the issue with the statusnotifier icons, lxde/libqtxdg#97 (the backport branch) is still needed for other icons issues, like with pcmanfm-qt:

![screenshot_20160730_131040](https://cloud.githubusercontent.com/assets/1238157/17271624/1fe11af4-5657-11e6-9d2f-9eeac6010b69.png)

**Comment by luis-pereira** [comment] 2016-07-30 16:15
@paulolieuthier Sure. But this particular issue is about the Status Notifier.
I made the patch from master because they are independent from each other. Both should make it to master if we found they are reliable.

**Comment by paulolieuthier** [comment] 2016-07-30 16:18
Yeah, sure. I'm just keeping record of it.

**Closed** 2016-08-05 17:06 UTC
Labels: high-priority, lxqt-panel, regression

**Comment by tsujan** [comment] 2016-08-07 14:00
It's my turn to report a similar problem ;)
Under Debian, status notifier icons were (and are) all right. But, under a newly installed Manjaro, Pidgin and Skype don't have a tray icon, while I have sni-qt, lib32-sni-qt and all libappindicators here. Both Pidgin and Skype do have tray icon under KDE.

**Comment by paulolieuthier** [comment] 2016-08-08 00:48
@tsujan Skype does not support the Status Notifier specification, so it should appear in the old system tray plugin. Plasma turns XEmbed icons into SNIs [using a bridge](https://github.com/KDE/plasma-workspace/tree/master/xembed-sni-proxy).

**Comment by tsujan** [comment] 2016-08-08 05:25
> Skype does not support the Status Notifier specification

On Debian and when 32-bit sni-qt is installed, Skype's tray icon appears in LXQt's Status Notifier -- I never use the old systray.

**Comment by tsujan** [comment] 2016-08-08 06:14
> Did you realy get e.g. pidgin icon into SNI?

Yes! That requires `pidgin-indicator`. Until now, only Skype doesn't have an icon and only on Manjaro; I don't know what I'm missing here.

**Comment by luis-pereira** [comment] 2016-08-08 09:56
@tsujan What do you don't see ? Only the icon or the item is not there ?

**Comment by tsujan** [comment] 2016-08-08 10:15
@luis-pereira 
First, I may be wrong but I don't think this is about an LXQt bug because, with the same version, the Skype tray icon is OK on Debian. It may be related to Qt or ... That was the reason I didn't reopen this issue.

Second, it's only about Skype so far: it has no item in the status notifier at all.
