### ISSUE TITLE
lxqt-panel no longer reacting to X11 screen resize

### ISSUE THREAD

**Issue by suncore** [lxde/lxqt#1034] opened 2016-04-25 10:52 UTC
Hi! I'm using TigerVNC with lxqt. After updating to Ubuntu 16.04, the lxqt panel no longer reacts when the TigerVNC window resizes (which causes the X11 server screen to resize). The panel stays put without using the new size. I think you can repeat the problem if you change desktop resolution or use xrandr to change screen size, e.g. xrandr --output HDMI1 --panning 1856x1056. (Check output using xrandr -q).
Version of panel is: lxqt-panel                                      0.10.0+201604240431~ubuntu16.04.1
I use this ppa:
deb http://ppa.launchpad.net/lubuntu-dev/lubuntu-daily/ubuntu xenial main

**Comment by pmattern** [comment] 2016-04-25 11:43
This is most likely due to the regression depicted in https://github.com/lxde/lxqt-panel/pull/310#issuecomment-211419224.
The commit discussed in that PR was meant to fix #990 which is about a problem similar to the one you're seeing on a single-monitor system right now on multi-monitor systems.

Closing as duplicate for now. Feel free to drop a note if you disagree.

**Closed by pmattern** 2016-04-25 11:43 UTC
