### ISSUE TITLE
Default browser does not work

### ISSUE THREAD

**Issue by RalfJung** [lxde/lxqt#986] opened 2016-03-20 09:14 UTC
I configured "firefox" to be my default browser. If I now click a link in an application (I tried Gajim and Liferea), they seem to just call "firefox" without any further arguments -- so the website that I clicked on is not actually opened.

With KDE and Cinnamon, this worked fine, so it seems that LXQt is doing something wrong in communicating the default browser to applications.

**Comment by Vladimir-csp** [comment] 2016-03-20 11:07
How exactly did you configure it?

On the backend side, there should be correct desktop entry associated with `x-scheme-handler/http`, `x-scheme-handler/https` and may be some other schemes in `$XDG_CONFIG_HOME/mimeapps.list` or `$XDG_DATA_HOME/applications/mimeapps.list` (deprecated). 

Desktop entry should have `Exec=/usr/lib/firefox/firefox %u` where %u is URL.

If you set default browser via Firefox itself, it generates user-level random firefox-XXXXXX.desktop, but it is sufficient to use plain firefox.desktop.

**Comment by RalfJung** [comment] 2016-03-20 15:12
I went to the LXQt session configuration and picked `/home/r/bin/firefox.d/firefox` as default browser. As I reported in <https://github.com/lxde/lxqt/issues/984>, this got shortened to `firefox`. Still, `x-www-browser` and `sensible-browser` work fine, and so does `xdg-open https://url`.

I also set the default browser in Firefox itself.

The `mimeapps.list` contains
```
x-scheme-handler/http=userapp-Firefox-NHMTUW.desktop;alacarte-made-74b2612a-cc0d-11e5-8580-10bf4805c7f7.desktop;Firefox.desktop;
x-scheme-handler/https=userapp-Firefox-NHMTUW.desktop;alacarte-made-74b2612a-cc0d-11e5-8580-10bf4805c7f7.desktop;Firefox.desktop;
```

Of these, only `Firefox.desktop` exists. It contains
```
Exec=/home/r/bin/firefox.d/firefox
```
Changing this to `... %u` fixed the problem, thanks!

So, the LXQt session configuration does not touch this file at all? That's rather confusing...

**Comment by luis-pereira** [comment] 2016-03-29 13:42
Confirmed.

**Comment by pmattern** [comment] 2016-03-30 16:29
Section "Default Applications" of `lxqt-config-session` is indeed setting environment variables only.
To deal with MIME types / [MIME Applications Specification](http://www.freedesktop.org/wiki/Specifications/mime-apps-spec) there's binary `lxqt-config-file-associations`. It's still writing in `$XDG_DATA_HOME/applications/mimeapps.list` instead of `$XDG_CONFIG_HOME/mimeapps.list` and it's UI isn't exactly intuitive for users without some knowledge about that whole MIME battle.
So all in all LXQt doesn't allow for dealing with MIME types in a comfortable way yet but that's a known issue already discussed e. g. in #433.

`sensible-browser` is a script which first tries to evaluate $BROWSER and falls back to Debian's Alternative System, where `x-www-browser` is one of the first generic names it looks for.
A desktop entry file `Firefox.desktop` where they value of key `Exec` does not state a so-called field-code like `%u` is homebrew stuff.
> The `mimeapps.list` contains

The important question would have been which mimeapps list. The one in `$XDG_DATA_HOME/share/applications` still gets written, among other by `xdg-mime` as well, but most applications are reading the one in $XDG_CONFIG_HOME only.
Anyway this
> Of these, only Firefox.desktop exists. It contains

seems to be the key. You probably removed the desktop entry file written by Firefox so applications using this particular file mimeapps.list will fell back to your custom `Firefox.desktop` lacking the field-code.

All in all I fail to see what should be the problem at LXQt's side here aside from the well-known ones I tried to depict above.

**Comment by RalfJung** [comment] 2016-03-31 10:17
I agree, this bug is essentially saying "the lxqt-session-config does not set the XDG default browser".

**Comment by Vladimir-csp** [comment] 2016-03-31 10:24
lxqt-config-session already has "Environment" tab. "Default Applications" could be dropped as there is nothing worth being specially edited there. 
Default browser functionality is covered by #1004 in lxqt-config-file-associations where it logically belongs.

**Comment by pmattern** [comment] 2016-03-31 11:13
> I agree, this bug is essentially saying "the lxqt-session-config does not set the XDG default browser".

Exactly.

> lxqt-config-session already has "Environment" tab. "Default Applications" could be dropped as there is nothing worth being specially edited there.

Agree, but should probably discussed elsewhere, see below.

So this issue is yet another indication that dealing with default applications / MIME types in LXQt needs to be addressed but the discussion should take place elsewhere, maybe in #433, #1004 or even in a new issue summarizing all aspects involved.
Thus closing this one, feel free to grumble if you disagree.

**Closed by pmattern** 2016-03-31 11:13 UTC
Labels: lxqt-session
