### ISSUE TITLE
[lxqt-panel] - Multi-monitor

### ISSUE THREAD

**Issue by ArthurBorsboom** [lxde/lxqt#738] opened 2015-07-08 09:19 UTC
With two monitors, the lxqt-panel is shown on the primary monitor, but uses the width of the secundaire monitor. The result is that the panel continues on the second monitor. I have made a screenshot and drawn a line where the monitor split is.

Arch Linux with lxqt 0.9

![2015-07-08-111104_3600x1080_scrot](https://cloud.githubusercontent.com/assets/6639859/8567116/04c094fa-2563-11e5-88f3-3e6755f38ddb.png)

![2015-07-08-111747_532x442_scrot](https://cloud.githubusercontent.com/assets/6639859/8567122/0d59d6bc-2563-11e5-8a9a-1affc3bf7335.png)

![2015-07-08-111750_532x442_scrot](https://cloud.githubusercontent.com/assets/6639859/8567125/0fffe0aa-2563-11e5-95dd-f9151da7da4a.png)

**Comment by pmattern** [comment] 2015-07-08 10:53
Duplicate of #650.

You may want to read [this comment](https://github.com/lxde/lxqt/issues/650#issuecomment-107385604) for an explanation what's happening. The only thing that doesn't fit 100% is the fact that the panel seems to be at the same vertical position on both monitors here. But your screenshot obviously doesn't display both monitors completely as it looks as if those had he same vertical resolution which doesn't apply according to the settings you posted.
Also see #680 (linked in #650 as well) for an explanation why the underlying faulty monitor configuration can come to happen easily in LXQt right now.

As a workaround you can e. g. place the monitors adjacent by lxqt-config-monitor. A corresponding xrandr command could be `xrandr --output eDP1 --mode 1920x1080 --primary --output HDMI2 --mode 1680x1050 --right-of eDP1`, you could invoke it manually from a terminal emulator or state it as argument of key `Exec` in ~/.config/autostart/lxqt-config-monitor-autostart.desktop which is where lxqt-config-monitor saves its settings.
In addition you may have to adjust the settings in 'Alignment & position' in LXQt panel's configuration dialog.

**Closed by pmattern** 2015-07-08 10:53 UTC
Labels: lxqt-panel, multi-monitor

**Comment by ArthurBorsboom** [comment] 2015-07-08 15:12
The suggested xrandr command works, but does not do what I want.
It puts the panel on the eDP1 instead of the HDMI2 (my primairy monitor).

The closest to what I want is this command

xrandr --output eDP1 --mode 1920x1080 --pos 0x0 --output HDMI2 --mode 1680x1050 --pos -1680x30 --primary

However, a small part of the panel is on the second monitor, as shown in the picture.

**Comment by pmattern** [comment] 2015-07-08 16:55
```
xrandr --output eDP1 --mode 1920x1080 --pos 0x0 --output HDMI2 --mode 1680x1050 --pos -1680x30 --primary
```
→ Not reasonable, IMHO: Negative values **--**1680x30 aren't allowed. To get HDMI2 right of eDP1 you'd e. g. have to state
```
xrandr --output eDP1 --mode 1920x1080 --pos 0x0 --output HDMI2 --mode 1680x1050 --pos 1920x00 --primary
```
    
> The suggested xrandr command works, but does not do what I want.
It puts the panel on the eDP1 instead of the HDMI2 (my primairy monitor).

To place the panel on a distinct of those two monitors you have to tweak 'Alignment & position' in the panel's configuration dialog as stated above. Invoke from panel's context menu (right-click).

**Comment by ArthurBorsboom** [comment] 2015-07-13 12:39
With your suggestions I have indeed solved the issue.
How these settings got there in the first place is unknown to me.

The solution is to edit ~/.config/autostart/lxqt-config-monitor-autostart.desktop
```
Exec=xrandr --output HDMI2 --mode 1680x1050 --pos 0x0 --primary --output eDP1 --mode 1920x1080 --pos 1680x0
```
and set alignment & position settings to the following.

![2015-07-13-143542_435x517_scrot](https://cloud.githubusercontent.com/assets/6639859/8649641/74a8585e-296c-11e5-9206-7bb894dc8107.png)

Thanks for your support.

**Comment by pmattern** [comment] 2015-07-13 12:51
> How these settings got there in the first place is unknown to me.

Could very well have been some misbehaviour of lxqt-config-monitor. Not a good moment to further investigate right now as it's under rather [heavy development](https://github.com/lxde/lxqt-config/commits/switch-to-kscreen)...

> Thanks for your support.

You're welcome.
