### ISSUE TITLE
.desktop URL's don't seem to be implemented (or improperly)

### ISSUE THREAD

**Issue by Jemi** [lxde/lxqt#921] opened 2015-12-19 04:23 UTC
I just tried creating a .desktop link to a URL in lxqt:

[Desktop Entry]
Encoding=UTF-8
Name=Link to Google
Type=Link
URL=https://www.google.com/
Icon=text-html

Attempting to open this shortcut resulted in pcmanfm-qt opening with a modal box:

"The specified directory 'https://www.google.com/'" is not valid"

The desktop entry I used was taken from https://github.com/beckus/WebShortcutUtil-Perl/blob/master/t/samples/real/desktop/gnome/Google.desktop - so it should work.

Operating System: Linux
CPU:  AMD64
Distro: Gentoo
LXQT version: 0.10.0

**Comment by pmattern** [comment] 2015-12-19 23:53
Confirmed.

Behaviour slightly different here, though.
Double clicking a desktop entry file as posted above yields a dialog "Error" saying `Operation not supported`. Upon confirmation PCManFM-Qt dumps core.

Problem seems to be due to PCManFM-Qt misinterpreting the desktop entry files in a weird way depending on the URL that's stated, see column "Type" in right pane.
*Every* URL featuring a trailing slash like `www.debian.org/` is considered a folder, `www.google.com` is considered a "DOS/Windows executable", both trigger the problem. In contrast `www.debian.org` or `www.google.de` (sic!) are considered "shortcut to URI" and work as expected.

Eventually related to the failure to drag & drop from plugin-mainmenu to the desktop as discussed [here](https://github.com/lxde/lxqt/issues/446#issuecomment-158757875).

Latest VCS checkouts of all LXQt components including lxde/pcmanfm-qt@5d62a63 on Arch Linux x86_64. All desktop entry files used to test checked by `desktop-file-validate` without any complaints.

**Comment by LStranger** [comment] 2015-12-20 10:42
That is a LibFM issue. The "folder" type needs a bit of rethinking there,
since it is in fact a folder still, but it should not be interpreted as
an usual folder. I'd fix this before LibfM 1.2.4 release. Thank you for
reporting this.

**Comment by luis-pereira** [comment] 2016-05-21 16:42
@pmattern @Jemi @LStranger I can't reproduce it anymore. I'm running the latest git pcmanfm and libfm 1.2.4
Can you guys confirm, it's fixed ?

**Comment by agaida** [comment] 2016-05-21 16:56
copied @Jemi's snippet into a new .destktop file and klicked on it - works like charm. So i going to close this now.

**Closed by agaida** 2016-05-21 16:56 UTC
Labels: crash, pcmanfm-qt

**Comment by tsujan** [comment] 2016-05-21 17:17
> copied @Jemi's snippet into a new .destktop file and klicked on it

I did so too and the same dialog @Jemi told about appeared. pcmanfm-qt and libfm-qt are up-to-date here but, perhaps, not other components. So, the bug couldn't be in libfm(-qt) if it's fixed now.

**Comment by tsujan** [comment] 2016-05-21 17:19
BTW, no dumpcore here.

**Comment by agaida** [comment] 2016-05-21 17:23
@tsujan, running sid and the lxqt-snapshots repo - status latest git. So maybe that differs to your installation.

**Comment by tsujan** [comment] 2016-05-21 17:36
@agaida I trust your and @luis-pereira 's observation and accept that the bug is fixed. I'm just not comfortable with its automatic disappearance ;)

**Comment by luis-pereira** [comment] 2016-05-22 18:28
@tsujan By the comments I assumed it was fixed in libfm 1.2.4, didn't check

**Comment by tsujan** [comment] 2016-05-22 21:05
> I assumed it was fixed in libfm 1.2.4

But libfm hasn't changed for "ages" ;) My PR, https://github.com/lxde/libfm/pull/8, is still undecided since Aug 29, 2015!

**Comment by agaida** [comment] 2016-05-23 00:53
@tsujan - maybe we should point @LStranger again to this :P

**Comment by luis-pereira** [comment] 2016-05-23 13:53
@tsujan Only confirmed that, at least, in my system didn't show up. @agaida confirmed it.
libfm not changing for "ages" is a not so good fact

**Comment by paulolieuthier** [comment] 2016-05-23 13:59
> libfm not changing for "ages" is a not so good fact

Certainly not. It also does not handle NotShowIn and OnlyShowIn, as you noted in #582.

**Comment by tsujan** [comment] 2016-05-23 14:08
Actually, I thought libfm might be a "taboo" area for some reason ;) It isn't touched since I came to LXQt.

**Comment by luis-pereira** [comment] 2016-05-23 17:40
@tsujan I'm not familiar with the code base.

**Comment by tsujan** [comment] 2016-05-23 18:07
@luis-pereira  It's OK. @PCMan wrote the code; I got somehow familiar with it before the above-mentioned PR and during my work on both pcamnfm-qt and libfm-qt; and I'm sure you will too if you study it. It's written cleanly, like other @PCMan's works.

I guess people find it a bit hard to recompile libfm and libfm-extra for testing. I always test before making PRs. Reading the contents of a PR shouldn't be difficult. And if compatibility with the gtk version of pcmanfm was the reason for not touching libfm, it's quite easy to know whether a change is backward compatible or not. Therefore, there should be no obstacle to working on libfm (at least after @PCMan returns).

Please tell me if there's another reason I don't know of.

**Comment by luis-pereira** [comment] 2016-05-23 19:32
@tsujan Of course it's a clean code base. To be true, I don't even compile it, I just installed from Arch repos.
When @PCMan was around all the time, he take care of that. Now that he isn't, I end up working in things that I can provide results quicker than learning libfm.

I don't know about any other reason. I only speak by myself, of course.

**Comment by LStranger** [comment] 2016-05-23 19:43
>@tsujan - maybe we should point @LStranger again to this :P 

Well, there were few fixes in libfm-1.2.4 in regards of .desktop files,
especially one mentioned in this report, if you look into changelog (the
NEWS file) you'll see:

* Fixed testing URIs like http://some.host.com for MIME type.

* Dropped using shortcuts to URIs like http://host/ as directories, no
    directory should be in principle used in shortcuts.

And I explicitly mentioned that it should be fixed in 1.2.4, see my
comment above.

**Comment by tsujan** [comment] 2016-05-23 19:46
OK. I think that @PCMan's didn't have time to review the PRs because he focused on libfm-qt and pcmanfm-qt PRs.

BTW, I think the development of libfm should be revived because there's a crashing bug in the search utility with this backtrace:
````
#0  0x00007fc8b78199a0 in ?? () from /lib/x86_64-linux-gnu/libpcre.so.3
#1  0x00007fc8b7829c73 in pcre_exec () from /lib/x86_64-linux-gnu/libpcre.so.3
#2  0x00007fc8bb6df2eb in g_match_info_next () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fc8bb6e0b8f in g_regex_match_full () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fc8bb6e0cda in g_regex_match () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fc89a9e89ed in ?? () from /usr/lib/libfm/modules/vfs-search.so
#6  0x00007fc8bbc389ed in g_file_enumerator_next_file () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007fc8bc19608b in ?? () from /usr/lib/libfm.so.4
#8  0x00007fc8bc19b5bd in ?? () from /usr/lib/libfm.so.4
#9  0x00007fc8bb6f450e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007fc8bb6f3b75 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007fc8ba62c454 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#12 0x00007fc8ba92aeed in clone () from /lib/x86_64-linux-gnu/libc.so.6
````
I'll check it when I have time.

@LStranger I suppose you're familiar with its code. Then, we could review its PRs and revive its development.

**Comment by luis-pereira** [comment] 2016-05-23 19:50
@tsujan Pls open a new issue. This one should be closed.

**Comment by LStranger** [comment] 2016-05-23 19:50
>But libfm hasn't changed for "ages" ;) My PR, https://github.com/lxde/libfm/pull/8, is still undecided since Aug 29, 2015!

Well, I highly appreciate your input but your PR introduces a feature but
libfm is in 1.2.x state. I plan to start work on 1.3 series later, after
I finish my work on lxpanel bringing it to 1.0, and I have a lot of work
in my TODO list for 1.3 already, including complete support for mentioned
".directory" file, not just icon but sorting, view mode, etc. Just let do
it later, OK? Thank you very much!

**Comment by LStranger** [comment] 2016-05-23 19:54
>> libfm not changing for "ages" is a not so good fact

>Certainly not. It also does not handle NotShowIn and OnlyShowIn, as you noted in #582.

libfm has nothing to do with NotShowIn and OnlyShowIn, those attributes
are menu related, not file manager entities.

**Comment by luis-pereira** [comment] 2016-05-23 19:58
@LStranger The menus are handled by menu-cache. Doesn't it depend on libfm ?

**Comment by LStranger** [comment] 2016-05-23 20:08
>@LStranger The menus are handled by menu-cache. Doesn't it depend on libfm ?

Nope. The libmenu-cache is independent thing, only dependence is on XML
parser/editor library (libfm-extra) since .menu files are in fact XML
files. That said libfm-extra is just a library included into the libfm
distribution, nothing more, no other relation with libfm.

**Comment by LStranger** [comment] 2016-05-23 20:20
Anyway, for last few years I'm the main developer for both libfm and
libmenu-cache, I did big rewrite of few critical places and a lot of
polishing before releases 1.0 for both and all improvements later. So you
may freely address me for bugs in both those libraries, I suspect nobody
is more familiar with them now than me.

**Comment by tsujan** [comment] 2016-05-23 20:45
> I finish my work on lxpanel bringing it to 1.0, and I have a lot of work in my TODO list for 1.3 already, including complete support for mentioned ".directory" file, not just icon but sorting, view mode, etc.

@LStranger From your words I got the impression that there may really be an unspoken "taboo" here.

In all other parts of LXQt, it's about step-by-step PRs and contributions. Do you mean that no one should contribute to developing libfm? I mean by coding, not just by suggesting ideas? If there's such an exception about libfm, please tell me because it's exactly what I wanted to know above.

> Just let do it later, OK? 

Frankly speaking, it's not OK to me at all.

**Comment by paulolieuthier** [comment] 2016-05-23 20:47
> libfm has nothing to do with NotShowIn and OnlyShowIn, those attributes are menu related, not file manager entities.

Ah, OK. I thought libfm was going to  handle that as well because of this: https://github.com/lxde/libfm/blob/master/src/actions/condition.vala#L510.

**Comment by LStranger** [comment] 2016-05-23 21:16
>> I finish my work on lxpanel bringing it to 1.0, and I have a lot of work in my TODO list for 1.3 already, including complete support for mentioned ".directory" file, not just icon but sorting, view mode, etc.

>@LStranger From your words I got the impression that there may really be an unspoken "taboo" here.

No, it's not taboo, it's just nobody was seemed to want to take part in
development, so it was long bugfix -- fast development cycle. And what I
meant was I have no time for development right now, just for bugs fixing
(as it was since 1.2.0 which I considered more or less feature complete).
And as for 1.3.0 release, I would rather not release it with just few
improvements while there are a lot in TODO. But sure, they can come into
GIT, even into master branch, we always can create 1.2 branch from point
where feature was introduced to create next bugfix release. I'm sorry for
misunderstanding if there was one, I tend to not tell my thoughts clearly
sometimes.

>In all other parts of LXQt, it's about step-by-step PRs and contributions. Do you mean that no one should contribute to developing libfm? I mean by coding, not just by suggesting ideas? If there's such an exception about libfm, please tell me because it's exactly what I wanted to know above.

>> Just let do it later, OK? 

>Frankly speaking, it's not OK to me at all.

You are more than welcome to make any contributions, just let don't release
them as 1.3.0 yet, it's what I meant with "later". If you are OK to have it
as a development (GIT-only) source, it would be very much fine for me too.

**Comment by LStranger** [comment] 2016-05-23 21:27
>> libfm has nothing to do with NotShowIn and OnlyShowIn, those attributes are menu related, not file manager entities.

>Ah, OK. I thought libfm was going to  handle that as well because of this: https://github.com/lxde/libfm/blob/master/src/actions/condition.vala#L510.

No, that code is only for context menu actions (DES-EMA), nothing more.
Though I have draft of vala-less actions code (see branch no-vala-code)
where that support will be implemented when released in future 1.3.0. But
again, that has nothing to do with system menu. :)

**Comment by luis-pereira** [comment] 2016-05-23 21:29
> No, that code is only for context menu actions (DES-EMA), nothing more.
> Though I have draft of vala-less actions code (see branch no-vala-code)
> where that support will be implemented when released in future 1.3.0. But
> again, that has nothing to do with system menu. :)

Ok, so menu-cache is the place to look into.

**Comment by tsujan** [comment] 2016-05-23 21:46
> No, it's not taboo ... I'm sorry for misunderstanding if there was one, I tend to not tell my thoughts clearly sometimes.

It's OK! Thank you very much for your rational reply!

> ... just let don't release them as 1.3.0 yet, it's what I meant with "later".

Oh, I'm not interested in version numbers at all ;) Let me explain my point with an example: 

Suppose I or someone else will fix the bug I mentioned at https://github.com/lxde/lxqt/issues/921#issuecomment-221075317 in a PR tomorrow. If the fix is OK -- and it's only a matter of rational reasoning plus testing to know if it is OK or not -- it should be merged as soon as possible. That doesn't mean releasing a new version of libfm, although the next version will include the fix automatically. What I'm telling is just about *gradual* development, not about releasing another version.

What's your opinion? If you disagree, please tell your reasons too!

**Comment by LStranger** [comment] 2016-05-24 08:03
>> ... just let don't release them as 1.3.0 yet, it's what I meant with "later".

>Oh, I'm not interested in version numbers at all ;) Let me explain my point with an example: 

>Suppose I or someone else will fix the bug I mentioned at https://github.com/lxde/lxqt/issues/921#issuecomment-221075317 in a PR tomorrow. If the fix is OK -- and it's only a matter of rational reasoning plus testing to know if it is OK or not -- it should be merged as soon as possible. That doesn't mean releasing a new version of libfm, although the next version will include the fix automatically. What I'm telling is just about *gradual* development, not about releasing another version.

>What's your opinion? If you disagree, please tell your reasons too!

Well, all reasoning with version numbers is that all versions with the
same major and minor number (1.2.* here) should have the same list of
features and strings. Any changes in features should go into 1.3.*. So
any bug fix is certainly welcomed and should be released as next 1.2.*
release version.

Thank you very much.

**Comment by tsujan** [comment] 2016-05-24 11:02
> all versions with the same major and minor number (1.2.* here) should have the same list of features and strings

So, practically, new feautures are blocked *for 10 months* just because of a versioning formality?! Apparently, I have no control over it but can dispute it at least: nowhere in LXQt I've encountered such a conventional obstacle!

**Comment by LStranger** [comment] 2016-05-24 11:49
>So, practically, new feautures are blocked *for 10 months* just because of a versioning formality?! Apparently, I have no control over it but can dispute it at least: nowhere in LXQt I've encountered such a conventional obstacle!

Well, as I said, new features can come to GIT in any case. If you want
them released, we can discuss new release (1.3.0) but that will mean the
release numbers will grow fast (1.4.0, 1.5.0, etc.) and users will be
confused with each new big release for just one or two features while
a lot of other features are waiting still. Are you sure you want that,
and you want to repeatedly explain users why one feature was released and
another wasn't implemented still? I'm not comfortable at all with such
explanations, it's why I prefer to release features in a batch, not just
single feature for each big release. Well, that means that bugfixing
releases happen often but feature releases don't, so releases happen to
be 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.2.0, ... instead of 1.1.0, 1.2.0,
1.3.0, 1.4.0, 1.5.0, 1.6.0, ... never giving people to get bugfixes but
always new features (with chance for new bugs).

**Comment by tsujan** [comment] 2016-05-24 12:00
That formality is discouraging to contributors for obvious reasons. Why should someone try to add a new feature when they know that it may not be merged after a year or at all?

All of us have limited free time but the fact that there's no monopoly on any LXQt component has made LXQt grow fast. That's the spirit of cooperation, which is apparently missing from libfm -- and only from it.

In your reply, you repeated the same set of versioning rules you'd explained before, as if they're sacred and should have priority over practicality.

Of course, bug fixes are important but new features and bug fixes aren't mutually exclusive -- they haven't been in LXQt at least. Moreover, the above-mentioned situation is discouraging for fixing bugs too, as is apparent from https://github.com/lxde/libfm/pulls.

**Comment by tsujan** [comment] 2016-05-24 12:12
For example, now I have no incentive even to try to fix https://github.com/lxde/lxqt/issues/1058. That's while I'm motivated to help fixing bugs in other areas of LXQt, even when I have to study the sources for hours.

**Comment by LStranger** [comment] 2016-05-24 12:33
I suppose there is some misunderstanding there. All I did I've tried to
explain my opinion, nothing more, and I believe I have right to explain
my opinion, just because it's so rare anyone wanted to contribute in last
years. And also you can look into git history and into tracker as well, I
never ignored people who sent patches. Well, I might be slow in response,
but you know, everyone has some life after all. And also I'm not only one
who can push changes into GIT. There is no such thing as monopoly in the
GIT community, and libfm isn't my private repository, I'm just a mere
contributor here, albeit the most active one, but I always thought you
should not blame me for that. I can leave the project if you think I am
an obstacle, anyway, it's first time I meet such opinion on me.

**Comment by tsujan** [comment] 2016-05-24 12:51
> it's first time I meet such opinion on me

Oh no! My opinion wan NOT about *you*! It was about the state of affairs -- about facts, not persons. Please don't let your emotions interfere with this! I *never ever* judge people but actions, ideas, thoughts, etc.

**Comment by tsujan** [comment] 2016-05-24 12:54
> I can leave the project if you think...

IMO, you should never do so because of what I or someone else thinks. That was a dialog between two rational persons. You and I have different opinions. I see it as an opportunity to make constructive changes -- not in personalities but in LXQt ;)

**Comment by tsujan** [comment] 2016-05-24 13:07
Trying to remove misunderstandings, I add that my using of words "incentive" or "motivated" wasn't emotional but purely logical. You set a goal for yourself only when it's attainable. Here, the goal is fixing bugs in or adding new features to *the source*. I can (and probably will) do so for my personal use but the goal in question doesn't seem attainable with this state of affairs.

**Comment by LStranger** [comment] 2016-05-24 13:23
It appears to be misunderstanding again. I'm always positive on adding
new changes and fixing things. All I wanted to tell you is I feel not so
good with making next major official release (1.3.0) with just a single
feature or two, that's all. Anyway, every move may (and should be) well
discussed. In regards of all bugs (in both main tracker and in github's
issues list), I simply had no free time for them lately, neither test
patches nor fix bugs. And as I said before, I'm not a single developer
who can push changes into libfm GIT.

**Comment by tsujan** [comment] 2016-05-24 13:34
> I'm always positive on adding new changes and fixing things.

Really good to know that.

> All I wanted to tell you is I feel not so good with making next major official release (1.3.0) with just a single feature or two, that's all.

And I quote myself, "I'm not interested in version numbers at all," which could mean that there would be no clash between interests. As far as I'm concerned, the next major official release could have any version. However, *only when the patches (bug fixes + features) are applied to https://github.com/lxde/libfm*, we could say this or that bug/feature is fixed/added but not yet released officially -- as is the case with other components.

**Comment by agaida** [comment] 2016-05-24 15:05
@tsujan - i think you and @LStranger have sorted out the possible misunderstandings in cases of merged/released - and i have only some statistics to add. LXDE is mature and widespread, LXQt is not, so we can move LXQt fast forward, if we release bugs or make some not so lucky design descisions, we can fix it up without causing much trouble to much people, in case of LXDE it's a little bit different, so a more conservative release strategy is needed i think. Ok, it's only the popularity contest of debian (not every installation is count, only for people who have activated popcon), dunno if ubuntu have something similar, but one could see a little difference in the user count.

LXDE: https://qa.debian.org/developer.php?email=lxde-debian%40lists.lxde.org
LXQt: https://qa.debian.org/developer.php?email=pkg-lxqt-devel%40lists.alioth.debian.org

**Comment by tsujan** [comment] 2016-05-24 15:40
@agaida Thanks for the info!
