### ISSUE TITLE
Desktop wouldn't change resolution

### ISSUE THREAD

**Issue by regs01** [lxde/lxqt#917] opened 2015-12-14 15:11 UTC
Anything above original resolution have black background with black cursor over it. I.e. unavailable. So desktop is like in a window in upper left corner. Reboot didn't help, so digged down a bit.

there is a file lxqt-config-monitor.conf stored in ~/.config/LXQt folder, while rest of config files stored in ~/.config/lxqt

Copied file from LXQt to lxqt, restarted session and it's now full screen.

0.10 from official launchpad ppa

**Comment by pmattern** [comment] 2015-12-14 21:06
If I got it right this issue is a duplicate of #378. So please be so kind and add your thoughts to that issue.
Otherwise drop a not here so that we can reopen if needed.

Thanks for contributing to LXQt.

**Closed by pmattern** 2015-12-14 21:06 UTC

**Comment by regs01** [comment] 2015-12-15 01:38
It lacks resolution and desktop words, so hard to find it
