### ISSUE TITLE
Add info on howto to re-enable power-management panel icon

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#849] opened 2015-10-16 10:32 UTC
It might be hard, for a newcomer, and maybe not so newcomer, find out how to re-enable it.
A message box stating how to do it would be nice.

**Comment by palinek** [comment] 2015-10-16 10:36
Where should the new dialog should appear? IMO the checkbox in power-management configuraiotn is pretty obvious.

**Comment by luis-pereira** [comment] 2015-10-16 10:39
When the user, clicks on _Disable Icon " a message box would appear. I also find it obvious.
But..... some of my friends don't feel the same way.

**Comment by jleclanche** [comment] 2015-10-24 03:53
@luis-pereira I'm closing this because lxqt-powermanagement settings need a fairly thorough UX pass; I'll do it now, but it won't land for 0.10.

**Comment by jleclanche** [comment] 2015-10-24 04:52
Followup in #857

**Comment by jleclanche** [comment] 2015-10-24 04:53
I just realized I misunderstood what the issue is. Yes, I'm fine with a notification that says "To reenable the battery icon, go to ..."

**Closed** 2015-10-29 06:24 UTC
Labels: lxqt-powermanagement, polish

**Comment by Paulo-Murilo-Dev** [comment] 2024-01-27 06:36
### Perdeu o ícone da bateria lxqt-power manager?

Olá galera, vou aproveitar esse tópico para adicionar essa informação aqui, se você está sem o icon de gerenciamento de bateria do lxqt-powermanager e não está conseguindo adicionar novamente na dock depois de customizar seu sistema aqui está a solução: Depois de alguma atualização que eu n faço a menor ideia de qual seja o lxqt mudou seu sistema de noficação, antes era um pluguin chamado "tray2" agora o novo pluguin se chama statusnotifier2, e você tem q adicionar ele no lxqt-panel pelo menu de widgets se quiser o ícone do lxqt-power manager, você também pode instalar outros gestores de bateria e usar o lxqt-powermanager apenas para visualização, já que com ele você pode personalizar o ícone e tudo mais, bem só queria mostrar a resolução de um problema que eu estava a 4 hrs tentando achar a solução!

[ENGLISH]

### Lost the lxqt-power manager battery icon?

Hello guys, I'm going to take advantage of this topic to add this information here, if you are without the lxqt-powermanager battery management icon and are unable to add it back to the dock after customizing your system, here is the solution: After an update that I have no idea what lxqt changed its notification system, before it was a plugin called "tray2" now the new plugin is called statusnotifier2, and you have to add it to the lxqt-panel through the widgets menu if you want the lxqt-power manager icon, you can also install other battery managers and use lxqt-powermanager just for viewing, since with it you can customize the icon and everything, well I just wanted to show the resolution of a problem I was having 4 hours trying to find the solution!
