### ISSUE TITLE
Lost shortcut

### ISSUE THREAD

**Issue by OhDaeto** [lxde/lxqt#1055] opened 2016-05-20 22:30 UTC
Hello! Recently I had to remove Lxqt configuration (~/config/lxqt) and found strangly bug. When LXQt creates a new configuration, after each run the desktop I get the following message in notification: 
``` Show Desktop: Global shortcut 'Control + Alt + D'. Cannot be registered```
![shortcut-bug](https://cloud.githubusercontent.com/assets/14937307/15444048/ef4a5f94-1efd-11e6-9940-0e9941505470.png)

**Comment by agaida** [comment] 2016-05-20 22:40
This isn't really new - it only says that your window manager claims the "show desktop" shortcut. But you are right, it is a bug.

**Comment by pmattern** [comment] 2016-05-20 22:44
If you're using Openbox which I'd deem likely this is a duplicate of #1032. Otherwise let us know so that we can eventually reopen.

**Closed by pmattern** 2016-05-20 22:44 UTC

**Comment by OhDaeto** [comment] 2016-05-20 23:11
I think I found the reason! Now I deleted ~/.config/lxqt together with ~/.config/openbox and noticed that in lxqt-rc.cml file a copy is created. Can somehow cancel the creation of this action if the folder does not exist openbox?

**Comment by pmattern** [comment] 2016-05-21 14:15
No, you haven't. The logic used to copy a template configuration file of Openbox into users' home directory is all right. It's just that the template itself isn't really good atm. Please see #1032.
