### ISSUE TITLE
lxqt-config: the displayed text is truncated

### ISSUE THREAD

**Issue by goetzc** [lxde/lxqt#501] opened 2015-02-15 22:58 UTC
If the text to be displayed is too long, it isn't displayed.

This is the default appearance of lxqt-config I get, window size is also default.
![lxqt-config](https://cloud.githubusercontent.com/assets/2220440/6205417/66c6f628-b53b-11e4-81b1-b843e7193aab.png)

**Comment by paulolieuthier** [comment] 2015-03-02 20:12
Can reproduce it only when using 12pt as font size, which is insanely big.

**Comment by goetzc** [comment] 2015-03-02 20:32
Maybe I am insane :) but it is easier to read that way. It also depends on other factors such as the number of pixels, the display size, etc.

Screenshot using 9pt as font size. The text is still cropped and the selected item looks bad:
![lxqt-config-9px_font](https://cloud.githubusercontent.com/assets/2220440/6449776/36050bbc-c0f1-11e4-9043-908be7df035c.png)

**Comment by paulolieuthier** [comment] 2015-03-02 20:38
@goetzc what qt widget style are you using?

**Comment by goetzc** [comment] 2015-03-02 20:56
@paulolieuthier I'm using QtCurve, but it is the same with Fusion (`lxqt-config -style fusion`).

**Comment by paulolieuthier** [comment] 2015-03-02 21:01
KWin, QtCurve, 10pt

![screen png](https://cloud.githubusercontent.com/assets/1238157/6450370/1d72fba8-c106-11e4-8e1c-dd75236240d0.jpg)

**Comment by goetzc** [comment] 2015-03-02 21:11
Can you break it with a bigger font?

**Comment by paulolieuthier** [comment] 2015-03-02 21:15
Only with 11pt and greater. The first item, "Appearance", only with 12pt and greater.

**Comment by Esclapion** [comment] 2015-03-02 21:30
Same problem here.
![cc](https://cloud.githubusercontent.com/assets/3512979/6450946/aeba673e-c12b-11e4-8d49-2a60b60e0d59.png)

**Comment by goetzc** [comment] 2015-03-04 15:43
Maybe it is some bug in Qt, I have Qt 5.4.1. Which version do you have? @paulolieuthier @Esclapion

**Comment by paulolieuthier** [comment] 2015-03-04 16:28
I have Qt 5.4.1 as well. And have never seen this bug.

**Comment by Esclapion** [comment] 2015-03-05 09:59
qt5-base 5.4.0-3 (qt qt5)

Manjaro, package coming from Archlinux. I always had this problem.

**Comment by Esclapion** [comment] 2015-03-05 16:59
Hmmm, it works since I changed the fonts with obconf, from Deja-vu to ttd-droid.
![ess](https://cloud.githubusercontent.com/assets/3512979/6509677/431b42e0-c361-11e4-9e39-3ba93b22dc31.png)

**Comment by goetzc** [comment] 2015-03-05 18:52
I does indeed look better, although the text is still cropped for the second item. 

I also get a better effect (but not much better), the Droid font does look narrower, compared to the DejaVu font (which I was also using).

**Comment by Esclapion** [comment] 2015-03-05 18:55
The text is not cropped if I scroll a bit more. I use also infinality smoothing.

**Comment by goetzc** [comment] 2015-03-05 18:57
I mean the "Configuration de l'apparence..."

**Comment by Esclapion** [comment] 2015-03-05 19:00
The french translation is not finished also.

**Comment by alfredobonino** [comment] 2015-06-27 17:40
On ubuntu the text is cutted!

**Comment by palinek** [comment] 2015-06-29 09:55
There are 2 problems (as I see it):
1. there is a static "presentation" space for each application - 100px x 100px (icon size is 32px) -> the text can't fit into it for everey possible font/size setting

2. the QIcon for some application specific icons present that there is only one available size 0px x 0px (`QIcon::availableSizes()`) -> widget/view is confused and calculates wrongly the size of presented/inside cell

In commit https://github.com/lxde/lxqt-config/commit/92fd4521df4b I've changed the model logic to present only 32x32 icon for the widget/view which solves #710

**Comment by palinek** [comment] 2016-05-02 14:58
Logic around the the presentation and the grid size was discussed and fixed in lxde/lxqt-config#79... and I believe it's fixed now.

**Closed by palinek** 2016-05-02 14:58 UTC
Labels: lxqt-config, polish, translations/i18n
