### ISSUE TITLE
Windows go under panel by dragging them with left mouse button

### ISSUE THREAD

**Issue by scootergrisen** [lxde/lxqt#1217] opened 2016-12-20 02:29 UTC
Its a bit annoying that i can move the windows up under the panel when the panel is at the top of the screen.

So the window title bar is under the panel when you release and it not so easy to move the window with the mouse because you can't grap the title.

You can right click the edge of the window but thats not so easy if the edge is only 1 pixel wide. Or use Alt while draging.

So maybe there should be some kind og protection so users can't place the window under the panel, unless the users really wants to. Like holding the Alt key.

**Comment by tsujan** [comment] 2016-12-20 02:54
Do windows go behind the panel automatically or do *you* place them there?

**Comment by scootergrisen** [comment] 2016-12-20 02:56
Like if i want to move a window that is not maximized to the top of the screen it goes under.
I'm not sure if newly created windows are placed under, i might have seen it but not sure.
I will try and notice if some window are placed under that i have not moved.

**Comment by tsujan** [comment] 2016-12-20 03:02
I can't reproduce that behavior with Openbox, KWin or Compiz as window manager. Which window manager do you use?

**Comment by tsujan** [comment] 2016-12-20 03:14
Most window managers have a concept like "resistance", which doesn't allow windows to overlap each other easily. It also works with panel.

**Comment by scootergrisen** [comment] 2016-12-20 03:15
wmctrl -m says Openbox.

**Comment by tsujan** [comment] 2016-12-20 03:23
OK! You could play with the folowing values in your Openbox config (which is ~/.config/openbox/lxqt-rc.xml or ~/.config/openbox/rc.xml depending on your LXQt version):
````
  <resistance>
    <strength>10</strength>
    <screen_edge_strength>20</screen_edge_strength>
  </resistance>
````

**Comment by scootergrisen** [comment] 2016-12-20 03:26
Using LXQt 0.11.0.

**Comment by scootergrisen** [comment] 2016-12-20 04:23
Try changing the panel height and see it you can do it.
I got mine at 60 pixels height.

**Comment by tsujan** [comment] 2016-12-20 12:23
Whether under LXQt or under any other DE, I can place windows behind panel or even partly off screen. What matters is than window edges show resistence so that windows don't go behind panel automatically.

**Comment by scootergrisen** [comment] 2016-12-20 19:46
In GNOME and Xfce if i drag the window up on the top panel the window shows it want to maximize below the top panel if i let go of the button.
I can't move the window under the top panel in GNOME and Xfce with just the mouse, but i can if i use keyboard like Super or Alt keys.
LXDE and LXQt works the same i can move the window below the top panel just with the mouse.

**Comment by tsujan** [comment] 2016-12-20 19:55
Now I completely understand your point. If not a bug, this is about an important feature.

@palinek, would you please look into this?

**Comment by tsujan** [comment] 2016-12-21 14:36
My mistake! This isn't related to the panel but to the window manager.

@scootergrisen 
As I explained [here](https://github.com/lxde/lxqt/issues/1217#issuecomment-268144331), increase `screen_edge_strength`. Unfortunately, Openbox has no per-application setting for resistance strength to set it for the panel. KWin is worse because I can't find any setting for edge resistance for it.

Since WM doesn't belong to LXQt, I close this issue.

**Closed by tsujan** 2016-12-21 14:36 UTC
