### ISSUE TITLE
lxqt-notificationd: use the common notification icon

### ISSUE THREAD

**Issue by sixsixfive** [lxde/lxqt#941] opened 2016-01-24 15:46 UTC
https://github.com/lxde/lxqt-notificationd/blob/master/config/lxqt-config-notificationd.desktop.in

please use the common icon for notification settings

-Icon=preferences-desktop-theme
+Icon=preferences-desktop-notification

**Comment by pmattern** [comment] 2016-01-24 20:02
Unlike `preferences-desktop-theme` a name `preferences-desktop-notification` isn't covered by the [Icon Naming Specification](http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html). It happens to be provided by Oxygen Icon theme but isn't part of e. g. Adwaita, GNOME or Tangerine icon themes and hence doesn't seem like a good alternative.

While it could be discussed whether some alternative name could basically make sense I couldn't find anything more suitable that's covered by the said specification at first glance.

So I do not think any change regarding the icon in use makes sense right now.

**Comment by palinek** [comment] 2016-01-25 11:27
The (non)usage of specific icon names was already discussed in #576 also....

**Comment by sixsixfive** [comment] 2016-01-25 17:07
>The (non)usage of specific icon names

>It happens to be provided by Oxygen Icon theme but isn't part of e. g. Adwaita, GNOME or Tangerine icon themes and hence doesn't seem like a good alternative.

I don't really see why this is an issue KDE oxygen and Enlightenment are probably the only projects that really tried to follow and extend this specification(eg following the naming scheme for new icons). 

Adwaita is now part of GTK3, and GNOME 3 proved that they actually don't care if libgnome stuff breaks outside GNOME so why should other desktops care about GNOME? You could also still ship an icon named "preferences-desktop-notification" and install it into the hicolor icon set since all Icon themes should inherit it(http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#file_formats).

Also following blindly this old outdated specification is probably not the best way especially since Qt never fully supported that spec:

https://bugreports.qt.io/browse/QTBUG-33123
https://bugreports.qt.io/browse/QTBUG-43620

**Comment by tsujan** [comment] 2016-01-25 17:51
Sticking to Gome/GTK+ icon themes isn't a good approach to me either. After all, thanks to Gnome's weird concepts of "standard", we now have LXQT. Being based on Qt, KDE is a better model to follow. I would consider an icon theme incomplete if it doesn't have `preferences-desktop-notification`.

BTW, don't desktop files accept fallback icons?

**Comment by pmattern** [comment] 2016-01-25 18:22
> I don't really see why this is an issue [...] why should other desktops care about GNOME?

Icon themes are usually provided independently from any desktop environment they eventually belong to. So chances are distinct icons are lacking in some particular theme if their names aren't covered by the Icon Naming Specification.

Nevertheless this issue is clearly a duplicate of #576 that you opened as well, which really doesn't make sense.

All relevant aspects, in particular the indeed rather important question whether or not LXQt should stick with the Icon Naming Specification / how to deal with the specs bad condition is already addressed there.
Hence closing this one.

**Closed by pmattern** 2016-01-25 18:22 UTC
Labels: idea/discussion, lxqt-notificationd
