### ISSUE TITLE
[lxqt] Download folder of Chromium

### ISSUE THREAD

**Issue by Esclapion** [lxde/lxqt#697] opened 2015-06-17 12:55 UTC
Under Chromium, if I make a download, it goes in the correct folder.
But if I go to the download page for Chromium (Ctrl-J), "open the downloads folder" or "display the folder" opens  /.
(manjaro lxqt 0.9, based on arch stable)

**Comment by pmattern** [comment] 2015-06-17 13:15
Duplicate of lxde/pcmanfm-qt#170.

**Closed by pmattern** 2015-06-17 13:15 UTC
