### ISSUE TITLE
Inconsistency inside File Associations dialog

### ISSUE THREAD

**Issue by fulalas** [lxde/lxqt#1285] opened 2017-04-28 01:10 UTC
1- If you add a new association, the dialog isn't refreshed, so you need to click on another file type and then click again on the first one to see the changes;

2- When opening the dialog for the first time the focus isn't inside search textBox;

**Comment by luis-pereira** [comment] 2017-05-05 22:29
@fulalas I was not able to reproduce the first point. By adding, you mean editing, right ?
Point 2 addressed at https://github.com/lxde/lxqt-config/pull/120.

**Comment by fulalas** [comment] 2017-05-06 02:52
@luis-pereira, sorry if it's not clear enough. Let's try again :)

In this dialog: http://img.photobucket.com/albums/v256/Delerue/fileassociations_zpst0bfm7co.png

If you click in 'Change' you'll face a new dialog and after selecting a new or different app for a given file extension, you'll click in 'OK' and you'll return to the main dialog, which isn't refreshed with the new setting.

**Comment by luis-pereira** [comment] 2017-05-06 15:18
Before the edit:
![screen-2017-05-06-16-13-24](https://cloud.githubusercontent.com/assets/62877/25773563/2f78e0ee-3277-11e7-81f1-12a0ab022bf7.png)

Then I edited it. Clicked Ok and the main dialog is this:
![screen-2017-05-06-16-14-04 png](https://cloud.githubusercontent.com/assets/62877/25773574/558d0d6e-3277-11e7-848f-8987dcfedfc8.jpg)
Which is Ok.

Are talking about resetting (clearing) the search edit ?

**Comment by tsujan** [comment] 2017-05-06 15:49
@fulalas 
Like @luis-pereira, I can't reproduce this issue. Are you sure your installed LXQt is up-to-date?

**Comment by fulalas** [comment] 2017-05-07 03:22
Hmmm... I'm using Arch build: https://www.archlinux.org/packages/?sort=&q=lxqt&maintainer=&flagged=

**Comment by luis-pereira** [comment] 2017-05-11 14:55
@fulalas Reopen if needed. 
Closed by https://github.com/lxde/lxqt-config/pull/120.

**Closed by luis-pereira** 2017-05-11 14:55 UTC
Labels: lxqt-config
