### ISSUE TITLE
I think I found a bug in "lxqt-appearance"

### ISSUE THREAD

**Issue by aleex5** [lxde/lxqt#1436] opened 2018-01-16 19:53 UTC
I opened "Lxqt-Appearance" by means of pcmanfm-qt in super user mode and when I clicked on a theme of the widgets, the appearance of the desktop changed to a totally different theme, I do not know if the theme "frost" or "dark" , the theme of the icons was also changed (by itself) and the configuration of the appearance is completely blocked, try several times to change the appearance by executing "Lxqt-Appearance" in a normal way, but when trying to change the appearance nothing happens, this happened without wanting to, because the idea was only to change the gtk theme of the applications in root mode with LXAppearance and then out of curiosity I did what I said at the beginning

PD1: the only theme that remained as it was was the gtk theme, the panel theme and icons were changed without me changing them

PD2: I do not know if it was understood what I tried to say

**Comment by tsujan** [comment] 2018-01-16 20:04
Check the permissions of the folder `~/.config/lxqt/` and an all its contents. If they belong to root, make them yours by whatever means.

Please tell us if they belong to root because in that case, there's a bug: opening apps as root -- even inadvertently -- should not change the permissions of the user's config.

**Comment by aleex5** [comment] 2018-01-16 21:03
I do not know what the correct permissions are, but I took images to show some how they come out
checking the files I see that in "lxqt.config" and "session.config" they come out as root
to return the configuration to normal I suppose I should change the 2 root files to my user?
is that I had never touched the permissions of the system folders


![1](https://user-images.githubusercontent.com/35360938/35011815-de0e19ba-fadd-11e7-829e-8450e731bb21.png)

![2](https://user-images.githubusercontent.com/35360938/35011816-de970644-fadd-11e7-94e3-27cc3253b67b.png)

![3](https://user-images.githubusercontent.com/35360938/35011817-df06c5ba-fadd-11e7-9599-66352efb0745.png)

![4](https://user-images.githubusercontent.com/35360938/35011819-df3a7662-fadd-11e7-9e6f-5c4d824a5d66.png)

![5](https://user-images.githubusercontent.com/35360938/35011822-dfbdf028-fadd-11e7-8453-40e21a9869a4.png)

**Comment by agaida** [comment] 2018-01-16 21:03
@tsujan full ack - and in the worst case it would be root:root 660 - so config-appearance would fall back to defaults :D

**Comment by tsujan** [comment] 2018-01-16 21:24
This is a duplicate of https://github.com/lxde/lxqt/issues/1138. Let's talk there.

**Closed by tsujan** 2018-01-16 21:24 UTC

**Comment by tsujan** [comment] 2018-01-16 21:36
@aleex5 All lxqt config folders and files inside `~/.config` should belong to you (as *user* and *group*). Make them yours and don't run GUI apps as root until the problem is fixed.
