### ISSUE TITLE
colors in qt breeze theme are broken in git

### ISSUE THREAD

**Issue by technic** [lxde/lxqt#1312] opened 2017-06-13 16:08 UTC
##### Expected Behavior
Have correct colors when Breeze widget style is selected in lxqt configuration. Pickup colorsheme for Breeze theme that is set in KDE configuration center.

##### Current Behavior
Colors don't follow Breeze colorscheme but taken from default Qt fusion theme.
Window and toolbars background has more red, but in Breeze it has more blue. It is not possible to have "Breeze Dark" colors.

##### Possible Solution
I this commit https://github.com/lxde/lxqt-qtplugin/commit/d5f8558ee6add4c3db212957d1810a8afe3efbe8
QPlatformTheme::palette is always used that returns Fusion color palette as I see from qt sources.

starting single application with `QT_QPA_PLATFORMTHEME=qt5ct` allows to follow Breeze colorschemes. I think we can make `QT_QPA_PLATFORMTHEME=lxqt` work the same way.

##### System Information
* Distribution & Version: ArchLinux
* Kernel: 4.11.3-1-ARCH
* Qt Version: 5.9.0
* lxqt Version:  recent git

**Comment by tsujan** [comment] 2017-06-13 16:23
I can confirm this and, IMO, it is a bug. Since LXQt doesn't have a widget style of its own, it should accept KDE colorschemes for its users to have a variety of choices with Breeze at least. If https://github.com/lxde/lxqt-qtplugin/commit/d5f8558ee6add4c3db212957d1810a8afe3efbe8 is the cause, it should be reversed.

If I used Breeze or one of Qt's default themes, I'd report this sooner.

**Comment by technic** [comment] 2017-06-13 16:35
I suppose, that breeze platform theme binary reads something from .config/kdeglobals and set colors defined there as application's default palette.

according to Qt documentation
> QPalette::QPalette()
> Constructs a palette object that uses the application's default palette.
so it worked before the commit. 

We can also have a look how qt5ct handles this situation
(https://github.com/mati75/qt5ct/blob/master/src/qt5ct-qtplugin/qt5ctplatformtheme.cpp#L114)
They have a related setting in the config, but It seems like returning `nullptr` is the right thing to inherit from widget style. We might need to do comprehensive test against all qt widget styles.

P.S. of course there was a memleak in the lxqt code before the commit.

**Comment by tsujan** [comment] 2017-06-13 16:39
> P.S. of course there was a memleak in the lxqt code before the commit.

If so, it should be fixed really.

**Comment by tsujan** [comment] 2017-06-13 16:41
> We might need to do comprehensive test against all qt widget styles.

No all Qt widget styles depend on KDE color schemes -- Kvantum has its own.

**Comment by agaida** [comment] 2017-06-13 16:42
and we should not read things from kdeglobals - please not :D

**Comment by tsujan** [comment] 2017-06-13 16:46
> and we should not read things from kdeglobals

Did we before that commit?!

**Comment by technic** [comment] 2017-06-13 16:52
> No all Qt widget styles depend on KDE color schemes -- Kvantum has its own.

How does it work for quantum? where does it get color scheme? I still don't clearly understand the relation between theme-engine, colors and platform-plugin.

**Comment by tsujan** [comment] 2017-06-13 17:05
>  I still don't clearly understand the relation between theme-engine, colors and platform-plugin.

There was a long discussion somewhere but I don't remember the place ;)

KDE color scheme is more than a set of palette colors -- it also contains colors that don't have meaning for Qt -- you could see it as a partial color config for Breeze.

Kvantum, on the other hand, is independent of KDE and uses its `kvconfig`and SVG files for colors and shapes (however, a few KDE apps get some of their colors directly from KDE color scheme, which is a bug IMO -- a different story). That's why I hadn't seen this issue before.

If I correctly recall, QtCurves could use it own colors too.

**Comment by technic** [comment] 2017-06-13 17:41
> There was a long discussion somewhere but I don't remember the place ;)
Probably this one https://github.com/lxde/lxqt/issues/572

But still, what is QPlatformTheme::palette interface for? If Kvantum is not affected, it doesn't use it. Am I right?

**Comment by tsujan** [comment] 2017-06-13 18:03
> Probably this one #572

Yes!

> If Kvantum is not affected, it doesn't use it. Am I right?

No style plugin can be without palette color in its code. How to get *another* set of palette colors from a config file is another story. In old days, when KDE was the only Qt DE, QtCurves and other style engines used KDE color schemes but that wasn't a necessity. Kvantum uses "THEME.kvconfig" (in special places) to get its colors and much more.

**Comment by tsujan** [comment] 2017-06-13 18:18
I forgot to explain this:

Color scheme has meaning as a (color) config for a style plugin -- if that plugin allows such a thing. So, color scheme becomes important when the current style plugin has only one and the same general look: only the colors could be changed for the look to be changed a little.

QtCurves was an exception in this regard because its general look could also be changed to some extent. However, all QtCurves has something in common visually. Kvantum is a complete exception because two different Kvantum themes could share no common visual element. Hence color schemes aren't important for it.

My point: color scheme is a KDE way of enriching the unchangeable looks of KDE style plugins (previously Oxygen, now Breeze). As https://github.com/lxde/lxqt/issues/572 shows, some LXQt developers don't agree with me on this.

**Comment by technic** [comment] 2017-06-13 18:52
Thanks for the explanation. So style plugins may or may not ask for the palette. 

Because nobody has written a gui for managing color palettes from lxqt configuration we can return `nullptr`. From the qt-base reference implementation, it is a valid behavior. Returning default constructed `QPalette()` seems to give the same result.
Default `QPlatformTheme::palette` implementation returns `qt_fusionPalette()` that is forcing style engine to use unsuitable fusion colors.

**Comment by tsujan** [comment] 2017-06-13 19:37
> So style plugins may or may not ask for the palette.

Yes! Fusion asks for nothing but most style engines ask for something: Breeze and oxygen ask for what KDE calls as "colorscheme" (Qt color palette plus more colors -- but just colors), while QtCurve and Kvantum ask for config files that are far more than mere colors.

**Closed** 2017-06-14 18:15 UTC
Labels: lxqt-qtplugin, regression
