### ISSUE TITLE
stretching wallpaper larger than 1920px don't work

### ISSUE THREAD

**Issue by kalle68** [lxde/lxqt#1219] opened 2016-12-23 10:03 UTC
I've a new install from lxqt in gentoo with a solution 2560x1440px. Wallpapers can't fill out the desktop without crop. As an example see the picture with Light-Theme.
![desktop](https://cloud.githubusercontent.com/assets/23744352/21451441/67c2dff4-c8ff-11e6-92a6-7c7350e30615.jpg)

**Comment by tsujan** [comment] 2016-12-23 10:15
We're aware of that. It's a Qt bug and this is a duplicate of https://github.com/lxde/pcmanfm-qt/issues/346. New comments should go to https://github.com/lxde/lxqt/issues/1027.

**Closed by tsujan** 2016-12-23 10:15 UTC
