### ISSUE TITLE
xrdp start menu dissapear

### ISSUE THREAD

**Issue by Jack85** [lxde/lxqt#1271] opened 2017-03-17 11:43 UTC
install xrdp 
install lxqt-core

login via xrdp click on start it dissapears

##### System Information

* Distribution & Version: ubuntu 16.04
* Kernel: 
* Qt Version: 
* liblxqt Version:  lxqt-core
* Package version:

**Comment by pmattern** [comment] 2017-03-17 12:00
Are you saying the topic of xrdp is disappearing from the panel's main menu? If so this is probably a duplicate of #65 and it just happens to get manifest in an RDP session but would get manifest the very same way if you were accessing the machine running LXQt directly (no desktop sharing / "sit in front of it").

**Comment by Jack85** [comment] 2017-03-17 12:35
No, Im saying WHOLE MENU just dissapears, you cann clin on any item if accesing over xrdp

**Comment by pmattern** [comment] 2017-03-17 23:44
How exactly did you configure xrdp on the host that's meant to run LXQt?

Any chance you can check whether the problem is also manifest when you're working at that host itself, so don't access it via network connections?

**Comment by Jack85** [comment] 2017-03-20 08:36
Sorry Im on vps, so not possible to check it without xrdp. What I tried was upgrading to ubuntu 16.10 where the menu does appear (theher is another problem with browser not starting). 

On v. 16.04
I did following

sudo apt-get install lxqt
sudo apt-get install xrdp
and login

**Comment by pmattern** [comment] 2017-03-20 10:20
Meanwhile I've tested xrdp with recent VCS checkouts of LXQt on Arch Linux. There was some issue with faulty background but I couldn't see any problem affecting the panel's main menu which was working as expected. You say, that you don't see the problem any longer on Ubuntu 16.10 either.
All in all this strongly suggests the problem you saw is downstream (Ubuntu) and nothing we can fix as far as LXQt is concerned.

As for the browser issue you may want to launch the browser from a virtual terminal (CLI) which frequently gives useful output. Is it really limited to LXQt sessions?

On a side note it's probably safe to say that RDP isn't the most common way to access desktop systems on *ix devices and you may hence want to consider accessing the (virtual?) machine in question by some other technique.
Both VNC and SPICE (virtual machines only) can be considered as reliable alternatives, and clients supporting a range of different platforms are available for both as well.

**Comment by Jack85** [comment] 2017-03-20 10:27
As you wish.  I tend to use xrdp - from win world most straightforward. 
Browser stuff, not sure. To test it correctly, you would need to have 16.04 dist. 

Regards

**Comment by pmattern** [comment] 2017-03-20 10:35
I'm closing this as downstream then.
Feel free to drop another comment if there's evidence the problem does affect LXQt; we'll reopen the issue then.
Unfortunately I don't have an Ubuntu system at hand right now, neither do the other team members afaik. But I guess if there was a general problem with browsers in LXQt, we'd already have heard of it...

**Closed by pmattern** 2017-03-20 10:35 UTC
