### ISSUE TITLE
lximage-qt-git does not load translations

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#1343] opened 2017-08-30 21:10 UTC
As title, tested for italian and german, always english is displayed. Latest git checkout.

##### Context

Strange enough: installing  lximage-qt instead from  arch repos does simple crash. Backtrace:
http://paste.ubuntu.com/25434294/

##### System Information

* Distribution & Version: Arch up-to-date
* Qt Version: 5.9.1-3

**Comment by tsujan** [comment] 2017-08-30 21:39
> Strange enough: installing lximage-qt instead from arch repos does simple crash.

That's because your other lxqt components are newer.

**Comment by tsujan** [comment] 2017-08-30 21:50
Confirming. No translation is shown.

Does it happen for pcmanfm-qt too? (I can't test because I compile it without translations).

**Comment by stefonarch** [comment] 2017-08-30 21:56
pcmanfm-qt is fine, as far as I see all other applications are 

> That's because your other lxqt components are newer.

 Only dependency is libfm-qt, should be this.

**Comment by tsujan** [comment] 2017-08-30 22:00
> pcmanfm-qt is fine

I know from another page that you've compiled pcmanfm-qt recently, against the new libfm-qt; haven't you? So, apparently, the problem is lximage-qt itself.

**Comment by tsujan** [comment] 2017-08-30 22:17
@stefonarch The problem is in `src/CMakeLists.txt`. Change this line:
```sh
-DLXIMAGE_DATA_DIR="${CMAKE_INSTALL_DATAROOTDIR}/lximage-qt"
```
to:
```sh
-DLXIMAGE_DATA_DIR="${CMAKE_INSTALL_PREFIX}/share/lximage-qt"
```
and recompile!

**Comment by tsujan** [comment] 2017-08-30 22:18
And if the problem is fixed, please make a PR (I can't now).

**Comment by tsujan** [comment] 2017-08-30 22:22
![german](https://user-images.githubusercontent.com/981076/29897697-6695cb60-8df7-11e7-9a83-6da772bf206b.png)

**Comment by stefonarch** [comment] 2017-08-31 07:34
Perfect, will make a PR but the credit is yours ;)
Compiled everything some days ago, there is a now a crash of pcmanfm when changing in some second subfolder first time, but it's not reproducable well and I've no clue for the moment.

**Comment by tsujan** [comment] 2017-08-31 07:46
> there is a now a crash of pcmanfm when changing in some second subfolder first time

Oh, that's important! If you have a backtrace (`coredumpctl gdb pcmanfm-qt` → `where`), please report it on pcmanfm-qt page!

**Comment by stefonarch** [comment] 2017-08-31 10:36
I never used gdb... what do you mean with →where? Just using your command I get https://pastebin.com/VAtNpfJE and no window open.

**Comment by tsujan** [comment] 2017-08-31 10:46
> what do you mean with →where?

After `coredumpctl gdb APP` and before `q`, if you write `where`, a useful backtrace will be shown.

**Comment by stefonarch** [comment] 2017-08-31 10:52
I've edited in mean time, another is here https://pastebin.com/PCUm54r8

**Comment by tsujan** [comment] 2017-08-31 11:02
Thank you! I'll search for the cause.

**Comment by tsujan** [comment] 2017-08-31 11:05
Fixed in https://github.com/lxde/lximage-qt/pull/110.

**Closed by tsujan** 2017-08-31 11:05 UTC
