### ISSUE TITLE
OnlyShowIn  and NotShowIn in *.desktop files  is not followed

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#694] opened 2015-06-16 13:56 UTC
On 2 different machines I have  twice the  KDE  settings in Settings submenu.
/usr/share/applications/kde4/kdesystemsettings.desktop
/usr/share/applications/kde4/systemsettings.desktop

The first is meant to show only in non-KDE environments  while the second should not show up in LXQt (OnlyShowIn=KDE), but anyway, changing or introducing 
NotShowIn=LXQt in any .desktop file does not work.

**Comment by pmattern** [comment] 2015-06-16 14:49
Duplicate of #582.

**Closed by pmattern** 2015-06-16 14:49 UTC
