### ISSUE TITLE
Wrongly rendered background on dual monitor setup

### ISSUE THREAD

**Issue by dobo90** [lxde/lxqt#1027] opened 2016-04-20 21:39 UTC
After recent upgrades on Arch Linux I've found that desktop background is wrongly rendered on dual monitor setups. On the second screen there's small left vertical bar which is a copy of right part of background of first desktop.

Bug is reproducible on physical environtment as also on VirtualBox. I've attached middle of two screens.
![lxqt_dual_monitor](https://cloud.githubusercontent.com/assets/1268906/14691316/d573d8da-0750-11e6-960f-5b96af143668.png)

Is there anything that I can supply to make this bug easier to solve?

Version on packages installed:
➜  ~  pacman -Qs lxqt
local/liblxqt 0.10.0-6
    Common base library for LXQt components.
local/lximage-qt 0.4.0-1 (lxqt)
    LXQt image viewer
local/lxqt-about 0.10.0-4 (lxqt)
    LXQt about dialog.
local/lxqt-admin 0.10.0-2
    LXQt system administration
local/lxqt-common 0.10.0-3 (lxqt)
    Common data to run a LXQt session.
local/lxqt-config 0.10.0-5 (lxqt)
    LXQt system configuration.
local/lxqt-globalkeys 0.10.0-3 (lxqt)
    LXQt daemon and library for global keyboard shortcuts registration.
local/lxqt-notificationd 0.10.0-3 (lxqt)
    LXQt notification daemon and library.
local/lxqt-openssh-askpass 0.10.0-3 (lxqt)
    LXQt openssh password prompt
local/lxqt-panel 0.10.0-5 (lxqt)
    The LXQt desktop panel
local/lxqt-policykit 0.10.0-3 (lxqt)
    The LXQt policykit authentication agent
local/lxqt-powermanagement 0.10.0-3 (lxqt)
    LXQt power management daemon
local/lxqt-qtplugin 0.10.0-3 (lxqt)
    LXQt platform integration for Qt
local/lxqt-runner 0.10.0-4 (lxqt)
    The LXQt application launcher
local/lxqt-session 0.10.0-3 (lxqt)
    The LXQt session
local/lxqt-sudo 0.10.0-3 (lxqt)
    LXQt privilege program (lxsu).
local/openbox 3.6.1-3 (lxde lxde-gtk3 lxqt)
    Highly configurable and lightweight X11 window manager
local/pcmanfm-qt 0.10.0-3 (lxqt)
    The LXQt file manager, Qt port of PCManFM

**Comment by pmattern** [comment] 2016-04-21 11:15
Confirmed as depicted above running latest VCS checkouts of all LXQt components on Arch Linux "bare metal".

Another manifestation of the problem is that the wallpaper gets displayed as expected on the second monitor while there's no wallpaper at all on the first monitor which is just black instead.

So far I couldn't track down when exactly the problem takes place either. But the fact that both release 0.10 as used by the OP and recent VCS checkouts are affected is suggesting that backend KScreen is involved somehow, IMO.

**Comment by selairi** [comment] 2016-04-21 11:26
> But the fact that both release 0.10 as used by the OP and recent VCS checkouts are affected is suggesting that backend KScreen is involved somehow, IMO.

Have you set screen config with `xrandr`? It could be useful to discard other problems.

**Comment by pmattern** [comment] 2016-04-21 18:26
> Have you set screen config with xrandr? It could be useful to discard other problems.

Normally I set the desired configuration by running `xrandr` in a terminal emulator (I basically want the "Extended View" but in reverse order which could never be achieved conveniently running `lxqt-config-monitor` so far) and invoke `lxqt-config-monitor` to save the settings / have them restored upon starting sessions.

But after having another look I realized that probably neither `lxqt-config-monitor` nor KScreen are involved:
When `lxqt-config-monitor` does not get run at all the two monitors do get set up in extended view nevertheless and the faulty handling of the wallpaper can be seen as well. (Regarding the black screen I failed to figure out how exactly to reproduce so far.)

It seems the default behaviour of RandR changed as of X.org server 1.*18*.
In former versions two monitors with different native resolutions were by default set up in clone mode upon launching the server. As of 1.18 they are set up in extended view mode, though.
Maybe PCManFM-Qt doesn't get along with this new behaviour somehow?

On a side note I find it difficult to understand how `lxqt-config-monitor` is meant to work right now.
It an be assumed that invocation `lxqt-config-monitor -l` as found in `~/.config/autostart/lxqt-config-monitor-autostart.desktop` is restoring the settings saved in `~/.config/lxqt/lxqt-config-monitor.conf`. But documentation doesn't seem to exist.
So maybe we could have a little man page or complement `lxqt-config-monitor` with the usual switch `--help` briefly explaining the basic modes of operation?

**Comment by joanasleet** [comment] 2016-04-27 19:50
I have the same issue. I noticed that upon drawing a marking-rectangle on the buggy part of the desktop makes the wallpaper appear correctly.
Hope it helps.
![normal](https://cloud.githubusercontent.com/assets/5249907/14866004/b96b4832-0cc1-11e6-941a-9241555e9763.png)
![marked](https://cloud.githubusercontent.com/assets/5249907/14866003/b96a2862-0cc1-11e6-860a-b998f6c0a2c0.png)

**Comment by PCMan** [comment] 2016-06-27 16:22
After some debugging, unfortunately, I think this is a regression bug of Qt. There is nothing we can do here. I already report the bug to Qt developers. Please help vote for the bug and add comments to it so it can be fixed earlier, hopefully.
https://bugreports.qt.io/browse/QTBUG-54384

**Comment by foxpup** [comment] 2016-10-21 22:32
For what its worth, I thought I'd mention that the 'weirdness' happens even when the image size matches the screen size on multiple monitors if the image is big enough.   I've got three 4k monitors side by side.  (not as impressive as it sounds, they are only 30hz)  The dimensions are 11520x2160.  Even when i make a custom jpg or png to match it essentially tiles portions of it over and over.  Because of the vastness of the real estate I can easily recognize a pattern that there is a tiling break every 2048 horizontal pixels.  I experience no vertical tiling in my panoramic configuration.  Maybe that 2048 pixel segmenting will help troubleshooters reach a solution.  Additionally, pcmanfm-qt is extremely unstable and I frequently find myself having to sometimes kill and relaunch it just to get file access back.

**Comment by tsujan** [comment] 2016-10-21 22:52
> Additionally, pcmanfm-qt is extremely unstable and I frequently find myself having to sometimes kill and relaunch it just to get file access back.

Could you please be more specific about this part? (1) How unstable? (2) Which version do you have?

**Comment by foxpup** [comment] 2016-10-21 23:10
@tsujan What I mean by "pcmanfm-qt is extremely unstable" is in the context of this triple 4k monitor setup.  On other, more reasonable machines, 1920x1080 for instance it is rock solid.  On the huge panoramic setup, I often lose the desktop icons an frequently open windows of pcmanfm-qt die and disappear.  I often find myself trying launch new ones or kill the running one (as root) in system monitor so I can relaunch it and hopefully get back icons on the desktop, pcmanfm-qt windows and file access for programs.  Sometimes the situation gets so bad that I have to restart and sometimes forcefully.  Currently, I'm going to play around and see if no background image or small background images are more stable.  I'm running QT 0.10.0. :-)  Also, if you want me to try anything, I may be foxpup, but I'm willing to be a guinea pig. :-)

**Comment by tsujan** [comment] 2016-10-21 23:25
V0.10.0 is too old but let's ignore that for now! You mean the unstable state is because pcmanfm-qt tries to draw the 4k desktop? I have two questions:

(1) What if you stop it from Configuration Center → Session Settings and use pcmanfm-qt without its desktop module, i.e. by launching it from the main menu or with its launcher in `/usr/share/applications`? Do you see any problem then?

(2) Does pcmanfm-qt takes a great amout of CPU time when it draws desktop?

**Comment by foxpup** [comment] 2016-10-21 23:57
@tsujan  I can try running without a desktop for a while and I'm always watching CPU and memory using those wonderful graphs in the lxqt-panel.  (It's the panel that made me love lxqt in the first place - lots of useful tools that can be shoved way off to the left, outside of my field of view while I ork.)  I don't remember seeing heavy CPU usage during the problem, but I do often hit against RAM limitations since I'm a bit of a tab-aholic in firefox and keep thunderbird running all the time while I run blender, google earth, libre-office or other things.  My humble 8 gigs often feels low.  (need to upgrade CPU/Mobo/RAM combination some day, but that ASUS core continues to be rock solid and its hard to chuck reliable machines that are paid for. :-)   I'll try with and without the desktop like you showed me and also with, without, & tiled background along with the desktop.  

Also something weird I noticed.  When I do a fresh boot and auto-login.  panel  and program fonts are larger than when I log out and then back in again.  Its like the first login is special somehow. :-)  

You mentioned that V.10.0 is too old.  I was looking for a ppa to add so I can just do a "sudo apt upgrade" and get the latest lxqt but the right entry so far has alluded me. :-)  I'm fond of that method of distributing new updates over manually downloading and updating, although I'm getting better at it. :-)  After getting tired being frustrated by Apple, and then later Microsoft systems, (too expensive, restrictive and "black boxy') I resolved to make linux my new computing home and it has taken a few years to get comfortable but I'm glad I made the transition.  I used to be, or technically still am, an MCSE, certified for windows NT/2K/XP/2003 + DBA and training, but that was long ago and I got tired of MS's rat race with too many changes for no good reason.  

I'll post my observations. :-)

**Comment by tsujan** [comment] 2016-10-22 01:05
@foxpup 
I asked those questions to know if pcmanfm-qt had any problem *other than* the one discussed here because you mentioned instability. The current issue is caused by a regression in Qt and, unfortunately, Qt developers haven't paid attention to https://bugreports.qt.io/browse/QTBUG-54384 yet. It seems that we can't do anything about it. I don't have access to a 4k monitor to try workarounds either.

As for V0.10.0, yes, it's old. LXQt, in general, and pcmanfm-qt, specifically, have changed a lot and become more stable since that version. But I didn't mean that the latest version would fix this special issue.

**Comment by pmattern** [comment] 2016-10-22 11:54
> I was looking for a ppa [...]

Beware the PPAs as described [here](https://github.com/lxde/lxqt/wiki/Binary-packages#ppas)! If you're lucky and they happen to have rather few flather some time they may allow for having a first look at LXQt, whether or not one may like it or so. But they sure a completely unsuitable for debugging as its far too likely that problems you see running them are caused by themselves.

But as @tsujan rightfully said a rather old version 0.10 really should not be used to haunt bugs.
If you don't care too much about clean uninstall you may follow our instructions to [build from the sources](https://github.com/lxde/lxqt/wiki/Building-from-source). The [scripts](https://github.com/lxde/lxqt/wiki/Building-from-source#scripts-to-build-in-one-step) work reliably among other on Ubuntu.
Now that you seem to be comfortable with *buntu you may also consider switching to Debian. The packages are maintained by an LXQt team member and in general in far better shape than those of *buntu. Release 0.11 is available in Debian testing right now and will hence make it to the next stable around the end of this year.

As for the Qt bug, voting may help...

**Comment by agaida** [comment] 2016-10-22 12:20
@pmattern LXQt 0.11.0 will migrate to debian/testing in 3 days, right now it is only in sid. And please don't try to install LXQt on powerpc or sh4 right now, there are some packages not build yet. :)

**Comment by PCMan** [comment] 2017-01-10 06:58
Though the upstream Qt bug 54384 is marked as "critical" which might block releases, the Qt guys never fixed it. :-(  Luckily, I found a possible workaround today.
https://github.com/lxde/pcmanfm-qt/commit/e766bf8a91db938df4f3d3e54367358547c5fd2b
By disable the built-in background painting of Qt widgets and try to paint the widget background ourselves, this hack seems to work. Not sure if this causes other side effects or conflicts with some style engines, though. More experiments are needed.

**Comment by tsujan** [comment] 2017-01-10 15:17
> Luckily, I found a possible workaround today.

That's really good news! Many users reported issues related to that bug.

**Comment by PCMan** [comment] 2017-01-12 03:36
Already fixed in https://github.com/lxde/pcmanfm-qt/commit/de24628202b2789d8c11954669a5b86f35b2c346.
Cheers!

**Closed by PCMan** 2017-01-12 03:36 UTC
Labels: lxqt-config, multi-monitor, regression, upstream

**Comment by jleclanche** [comment] 2017-01-27 23:39
@PCMan That commit seems to have broken tiling on Arch Linux.

**Comment by jleclanche** [comment] 2017-01-27 23:41
![image](https://cloud.githubusercontent.com/assets/235410/22391585/c7f75a00-e4fa-11e6-95cc-bc4e2fd08d3e.png)

**Comment by tsujan** [comment] 2017-01-28 08:08
> @PCMan That commit seems to have broken tiling on Arch Linux.

Will look into it.

**Comment by tsujan** [comment] 2017-01-28 08:31
@jleclanche https://github.com/lxde/pcmanfm-qt/pull/446 should fix it. Please try it!

**Comment by jleclanche** [comment] 2017-01-28 08:35
Thanks! I won't be able to try it any time soon though :/

**Comment by tsujan** [comment] 2017-01-28 11:31
> I won't be able to try it any time soon though

It's OK. The patch works with a single 1920x1080 monitor. Waiting for a test with a higher resolution or dual monitor.

**Comment by tsujan** [comment] 2017-01-30 15:03
Anyone with an HDPI display, please try https://github.com/lxde/pcmanfm-qt/pull/448 with tiled wallpaper!

**Comment by yarwelp** [comment] 2017-09-19 13:47
Upstream bug report https://bugreports.qt.io/browse/QTBUG-54384 was closed today because they are unable to reproduce.

**Comment by tsujan** [comment] 2017-09-19 14:06
> ... was closed today because they are unable to reproduce.

Not the first time they can't reproduce bugs that so many users see -- I know that some Qt devs use Ubuntu+Unity (and not even Kubuntu) for testing -- but closing this one after such a long time was a strange reaction. Fortunately @PCMan found and applied a workaround for it.

Edit:
Wow! Quoting a Qt dev on that same page: "I could not reproduce this with 5.10 and 5.6.3 on Ubuntu+Unity..." Someone please tell them that Unity is not good for testing Qt. I'd told them several times and still....

**Comment by tsujan** [comment] 2017-09-19 14:10
Added a comment there ... but they didn't listen before.

**Comment by agaida** [comment] 2017-09-19 14:11
<rant>Cool - but thats KDE/Qt - they have a long term relation with ubuntu. So if it isn't reproducible with any ubuntu the bug doesn't exist.</rant>

**Comment by agaida** [comment] 2017-09-19 14:12
bah, github dont like my rant or sarcasm tags - bad bad github ...

**Comment by tsujan** [comment] 2017-09-19 14:18
@agaida I've got tired of denials. There are critical bugs on Qt bug tracker that have remained unattended for such a long time and some Qt devs (not all of them) say VERY strange things about them. I could add some links here but it wouldn't be of any help. Unity and Qt?! Shouldn't a Qt developer know the obvious? Or maybe becoming a Qt developer has become too easy nowadays?

**Comment by agaida** [comment] 2017-09-19 14:23
No - i remember discussions with some Qt- and KDE devs back in 2010 - they make no mistakes, distributions do ... Sounds familar? But this situation has slightly changed to the better. (some times, QtWebengine anyone?)

**Comment by jeremywh7** [comment] 2017-09-21 14:32
Well, the good news; they reopened the QTBUG yesterday.  The bad; they closed it today based on Lubuntu and Openbox testing!  Isn't Lubuntu still using LXDE?  [please see my avatar] I think we must be getting Punk'd.  I guess somebody needs to very clearly state (again) that this is a Qt issue ___in LXQt___.  Maybe they'll test it in DOS next.  :-|

**Comment by tsujan** [comment] 2017-09-21 14:41
@jeremywh7 The real good news is that this bug doesn't concern us after PCMan's workaround, which will be quite safe even if the bug is fixed in Qt.

**Comment by jeremywh7** [comment] 2017-09-21 15:34
Yes, very good for PCman's fix.  :-)  I was partly speaking to the principle, and partly to Qt's attitude and inability to even test with even reasonably close setups to the submitted report:
> Reported in LXQt bug tracker by many users.  https://github.com/lxde/lxqt/issues/1027

**Comment by tsujan** [comment] 2017-09-21 15:52
@jeremywh7 

Most Qt devs are very active and attend to bugs quickly. However, a few devs (I know of 2) can almost never reproduce critical bugs and I think that's mostly because they use Unity or gnome-shell. I show persistence and point out contradictions politely whenever that happens but can't do more than that -- dealing with Gerrit is beyond my limited time.

Yes, the current situation with Qt5 sometimes makes me angry too ;) but we might have to accept and tolerate it.
