### ISSUE TITLE
Volume control notification on every start: Shortcuts could not be registered

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [lxde/lxqt#527] opened 2015-03-03 06:08 UTC
something relating to XF86 lower/mute/raise volume

**Comment by jleclanche** [comment] 2015-03-03 06:11
You sound like you don't have lxqt-globalkeys running.

**Comment by ThebestwaytodesignJoinGitHub** [comment] 2015-03-03 06:44
"Global Keyboard Shortcuts" Running

**Comment by kuzmas** [comment] 2015-03-03 07:01
As I said in https://github.com/lxde/lxqt/issues/505#issuecomment-75199217 I have the same issue in VirtualBox. But these volume keys don't work in KDE and even in xev for me there, so it looks like a VirtualBox's issue. I asked if someone can check the issue in the real environment.
@ThebestwaytodesignJoinGitHub: do you use virtual machine or a real one? If real - what happens in `xev` if you press those problematic volume up/down/mute keys?

**Comment by palinek** [comment] 2015-03-03 07:27
I have the same situation... but didn't bother me. It came with 0.9.0. I thought that this was being happen because of the keybindings already registered by WM (openbox in my case).

**Comment by ThebestwaytodesignJoinGitHub** [comment] 2015-03-03 07:31
Running a real Debian.
Xev says "KeymapNotify event, serial 51, synthetic NO, window 0x0" and so on.
XF86AudioMute is enabled and is functioning as it should!
XF86Lower and XF86Raise are disabled, I do not have such keys on my bambus keyboard.

**Comment by palinek** [comment] 2015-03-03 07:34
Just tested it... for me removing the XF86* volume handling keybindings from OpenBox configuration did resolve this problem. After openbox restart and plugin remove/add keybindings are registered ok and working with the volume plugin.

**Comment by kuzmas** [comment] 2015-03-03 07:38
Thanks @ThebestwaytodesignJoinGitHub , @palinek

**Comment by ThebestwaytodesignJoinGitHub** [comment] 2015-03-03 07:54
But I have no keybindings related to XF86 in my openbox rc.xml files

**Comment by palinek** [comment] 2015-03-03 08:12
@ThebestwaytodesignJoinGitHub what is the full ```xev``` output for the key event.

With no openbox keybindigns I'm getting:
```
KeyPress event, serial 48, synthetic NO, window 0x1200001,
    root 0x98, subw 0x0, time 4536085, (19,168), root:(3120,190),
    state 0x10, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 48, synthetic NO, window 0x1200001,
    root 0x98, subw 0x0, time 4536301, (19,168), root:(3120,190),
    state 0x10, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

While with openbox keybindings:
```
KeymapNotify event, serial 48, synthetic NO, window 0x0,
    keys:  4294967192 0   0   0   0   0   0   0   0   0   0   0   0   0   0   8   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   

KeyRelease event, serial 48, synthetic NO, window 0x1200001,
    root 0x98, subw 0x0, time 4723381, (39,169), root:(3140,191),
    state 0x10, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

So there is no KeyPress event for the XF86* ... I'm not guru for X11, just assuming that in my case the KeyPress event was consumed by Openbox.

**Comment by kuzmas** [comment] 2015-03-03 08:20
My output of xev in real machine: KDE, kwin, volume keys not assigned in KDE:
```
KeyPress event, serial 40, synthetic NO, window 0x7200001,
    root 0xb7, subw 0x0, time 5153250, (-179,77), root:(1086,100),
    state 0x0, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic NO, window 0x7200001,
    root 0xb7, subw 0x0, time 5153374, (-179,77), root:(1086,100),
    state 0x0, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

with assigned volume keys:
```
KeymapNotify event, serial 40, synthetic NO, window 0x0,
    keys:  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   8   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeyRelease event, serial 40, synthetic NO, window 0x7200001,
    root 0xb7, subw 0x0, time 5297326, (1596,834), root:(1596,857),
    state 0x0, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

Looks like `KeymapNotify`+`KeyRelease` printed when the shorcut is in use. Just like you have, @ThebestwaytodesignJoinGitHub in https://github.com/lxde/lxqt/issues/527#issuecomment-76899469

**Comment by ThebestwaytodesignJoinGitHub** [comment] 2015-03-04 04:19
my xev output

FocusOut event, serial 45, synthetic NO, window 0x2c00001,
    mode NotifyGrab, detail NotifyAncestor

PropertyNotify event, serial 45, synthetic NO, window 0x2c00001,
    atom 0x1c1 (_NET_WM_ICON_GEOMETRY), time 347134, state PropertyNewValue

FocusIn event, serial 45, synthetic NO, window 0x2c00001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 45, synthetic NO, window 0x0,
    keys:  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

**Comment by palinek** [comment] 2015-03-04 12:00
@ThebestwaytodesignJoinGitHub that's it. You don't get the KeyPress event and volume control is complaing about registering. So somebody is stealing the event.

**Comment by palinek** [comment] 2015-03-16 08:21
@ThebestwaytodesignJoinGitHub were our findings appropriate? If yes, we can close this...

**Comment by ThebestwaytodesignJoinGitHub** [comment] 2015-03-16 16:40
Please do not close it, I still have this popup after session launch.
And here is nothing stealing the shortcuts, there is no entry in my openbox config files.

**Comment by pmattern** [comment] 2015-03-21 21:27
The problem isn't limited to those audio buttons but seems to affect any plugin that wants to register some default keys.
E. g. I can see the very same behavior with plugins 'Show desktop' (shortcut Ctrl+Alt+D) and 'Launch screensaver' (shortcut Ctrl+Alt+L).

"bare metal" all keys and keyboard shortcuts are working as expected besides the warning.
In a KVM/QEMU virtual machine according to xev none of XF86Audio{Raise,Lower}Volume and XF86AudioMute is recognized, yet all warnings appear including the one about those multimedia keys.

Problem persists if all relevant configuration files and directories in $HOME are deleted before launching LXQt and also if lxqt-globalkeysd is *not* enabled.

It seems pretty unlikely to me that it's the window manager which is reserving those keys.
Running Openbox + LXQt xev states 'KeymapNotify event' roughly as stated above when any of XF86Audio{Raise,Lower}Volume and XF86AudioMute is hit. But in an Openbox ("only") session on the very same system xev is displaying the regular 'Key{Press,Release} event'.
Left windows key is definitely reserved by Openbox as so-called "Super key". Yet xev is indicating regular 'Key{Press,Release} event' upon hitting this button.
The messages persist running Xfwin + LXQt. And I couldn't find any hint that Xfwin is using any of XF86Audio{Raise,Lower}Volume and XF86AudioMute either.

@palinek
Could you tell me what exactly you meant by "removing the XF86* volume handling keybindings from OpenBox configuration"? Was it something custom?
As I could neither find any hint on those keys being used by Openbox in my rc.xml nor in documentation about default settings, namely [DefaultConfiguration](http://openbox.org/wiki/Help:DefaultConfiguration) (a bit outdated) and [Changelog](http://openbox.org/wiki/Openbox:Changelog).

**Comment by palinek** [comment] 2015-03-22 20:14
> Could you tell me what exactly you meant by "removing the XF86* volume handling keybindings from OpenBox configuration"? Was it something custom?

Yes, while OpenBox is able to handle keyboard shortcuts (http://openbox.org/wiki/Help:Bindings), I was just suggesting that you/he/she can have some colliding configuration there.

@ThebestwaytodesignJoinGitHub the problem is only notification, but the key is works (mute/unmute)?

@pmattern regarding the clean LxQt and xev: if the volume plugin is running (and it was able to register the shortcut) the keypress event is not delivered elsewhere -> xev won't show it

**Comment by ThebestwaytodesignJoinGitHub** [comment] 2015-03-23 06:06
Yes, the key works

**Comment by palinek** [comment] 2015-03-23 09:36
@ThebestwaytodesignJoinGitHub does it work also when you remove the volume plugin?

**Comment by ThebestwaytodesignJoinGitHub** [comment] 2015-03-23 11:02
No Sir. And the popup appears when adding the volume widget, not when launching the session.

**Comment by palinek** [comment] 2015-03-23 11:35
So the problem is just a false alarm about unsuccessfull registration of shortcuts.

**Comment by palinek** [comment] 2015-03-23 11:40
@ThebestwaytodesignJoinGitHub you get the error notifiaction for all three XF86Audio* shortcuts or only for XF86Audio{Raise,Lower}Volume?
...or simply paste text of notification here

**Comment by ThebestwaytodesignJoinGitHub** [comment] 2015-03-23 13:30
All three. Even though lower and raise are disabled in the global actions manager.

**Comment by palinek** [comment] 2015-03-26 11:47
While looking on other issue I think that I've tracked this ...
@kuzmas IMHO it is related to https://github.com/lxde/lxqt-globalkeys/commit/76a2a8958e820712dd4bacf505b919684acbfddf and the logic how plugins are registering the shortcuts, e.g.:
```c++
    m_key = GlobalKeyShortcut::Client::instance()->addAction(QString(), QString("/panel/%1/show_hide").arg(settings()->group()), tr("Show desktop"), this);
    if (m_key)
    {
        connect(m_key, SIGNAL(activated()), this, SLOT(toggleShowingDesktop()));

        if (m_key->shortcut().isEmpty())
        {   
            m_key->changeShortcut(DEFAULT_SHORTCUT);
            if (m_key->shortcut().isEmpty())
            {   
                LxQt::Notification::notify(tr("Show Desktop: Global shortcut '%1' cannot be registered").arg(DEFAULT_SHORTCUT));
            }
        }
    }
```

since the `addAction` now doesn't block the above code get's weird results

**Comment by palinek** [comment] 2015-03-26 13:44
@ThebestwaytodesignJoinGitHub, @pmattern please, confirm if the above solved this issue

**Comment by pmattern** [comment] 2015-03-26 20:56
Problem seems to be fixed.

Out of curiosity I compiled the versions corresponding to the latest six commits (c7d2455 - 2c38da7). With all plugins in question the problem disappeared with the respective commit as stated in the commit names.

On a side note I was wondering about the fix in 'Desktop switcher': I couldn't see the problem with this plugin, including commits c7d2455 and a0ebff6 which where the last before the commit series comprising the actual fixes.

**Comment by palinek** [comment] 2015-03-26 21:23
Desktop switcher was updated today as a part of optimization and this changed the way how shortcuts were registered(lxde/lxqt/panel#157). That fixed it, but broke feature of changing the shortcut in lxqt-config-globalkeys (changed to default after each widget restart).

**Comment by palinek** [comment] 2015-03-26 21:24
Desktop switcher was updated today as a part of optimization and this changed the way how shortcuts were registered(lxde/lxqt/panel#157). That fixed it, but broke feature of changing the shortcut in lxqt-config-globalkeys (changed to default after each widget restart).

**Comment by ThebestwaytodesignJoinGitHub** [comment] 2015-03-30 05:37
Fixed, thank you

**Closed** 2015-03-30 06:06 UTC
