### ISSUE TITLE
Qt5 builds of LXQt are suicidal at startup

### ISSUE THREAD

**Issue by v-fox** [lxde/lxqt#499] opened 2015-02-15 13:26 UTC
Not long ago i permanently moved from KDE to LXQt on openSUSE for my personal usage and for my live distribution. Qt4-build of version 0.8.0 worked and does work pretty good but ANY Qt5 builds of LXQt (0.8 or 0.9, linked against Qt 5.3.2 or 5.4) behave like this:
on startup LXQt components (lxqt-{session,policykit-agent,notificationd,globalkeyd,runner,panel}) crash randomly, sometimes they don't, sometimes it's several of them, sometimes entire session dies and throws me away on login screen. It happens only on login and all other Qt5 apps work fine.

Errors in dmesg are like this (nothing notable anywhere else):
(first fail at autologin on bootup)
```
[   13.740016] lxqt-session[2330]: segfault at 529 ip 00007f1c19aa7f3f sp 00007fff258f7018 error 4 in libQt5Core.so.5.3.2[7f1c199a0000+4b9000]
```
(usually this "trap" thing happens when panel with tray crashes with similar "error 4" but i don't see that here, those autostart apps died anyway though)
```
[ 1446.319317] traps: pasystray[6846] trap int3 ip:7f72d58fa7f3 sp:7fff12c62120 error:0
[ 1446.319620] traps: gnote[6561] trap int3 ip:7f90bb97a7f3 sp:7fffdfdf40f0 error:0
[ 1446.319740] traps: nm-applet[6468] trap int3 ip:7f812aea27f3 sp:7fffd2d1bf90 error:0
[ 1446.320142] traps: blueman-applet[6448] trap int3 ip:7faffbcba7f3 sp:7fff7d1b9e00 error:0
[ 1446.322397] traps: ibus-ui-gtk3[6588] trap int3 ip:7f51b23d27f3 sp:7fff973147f0 error:0
```
(2 more login attempts with full session crash until final LXQt-Qt5 uninstall)
```
[ 1452.856036] lxqt-policykit-[7533]: segfault at 419 ip 00007ff0e32e7f3f sp 00007fffc4d16b48 error 4 in libQt5Core.so.5.3.2[7ff0e31e0000+4b9000]
[ 1452.904278] lxqt-session[7398]: segfault at 261 ip 00007f103f377f3f sp 00007fff7bc0f2f8 error 4 in libQt5Core.so.5.3.2[7f103f270000+4b9000]
[ 1459.884573] lxqt-session[7720]: segfault at 61 ip 00007f492a187f3f sp 00007fff780d6f08 error 4 in libQt5Core.so.5.3.2[7f492a080000+4b9000]
```
Bad Qt5 builds are from [here](https://build.opensuse.org/project/show/X11:lxde), good Qt4 builds are from [here](https://build.opensuse.org/project/show/home:X0F:LXQt-Qt4).
[Others seem to experience it too](https://forums.mageia.org/en/viewtopic.php?f=3&t=7604&start=50#p54429). I thought that it might have something to do with issue #310 but proposed workaround from there didn't help. I tried to tinker with everything that might have something to do with Qt5 or session startup in general but with no result. So, for now i stay on Qt4 builds.

**Comment by jleclanche** [comment] 2015-02-15 14:55
@lxde/release-maintainers Can someone from opensuse take a look at this please?

**Comment by heliocastro** [comment] 2015-02-15 14:59
We are suffering issues on startup as well on Fedora rawhide, but our
investigation stopped under Qt5, as even KDE is crashing right now due the
introduction of new gcc 5.
So for now is difficult to know if the bug is caused by lxqt itself or a
side effect on broken gcc 5.

I will keeping up to date as soon we have Qt back in regular state.

On Sun, Feb 15, 2015 at 12:55 PM, Jerome Leclanche <notifications@github.com

**Comment by jleclanche** [comment] 2015-02-15 15:00
Keeping in mind one of the lxqt-qtplugin releases were broken. What's downloadable *right now* should work fine.

**Comment by heliocastro** [comment] 2015-02-15 15:08
Yep, we're already using latest tarball, md5sum
91220a62607ea42a439bd56c23e7303d  lxqt-qtplugin-0.9.0.tar.xz

**Comment by v-fox** [comment] 2015-02-15 15:21
In openSUSE 13.2 gcc is 4.8.3 and i even tried commenting out QT_PLATFORM_PLUGIN and QT_QPA_PLATFORMTHEME or replacing 'lxqt' with 'gtk2' (for qt5/plugins/platformthemes/libqgtk2.so) in startlxqt - no change.
You can see what exactly it's build with in [build logs](https://build.opensuse.org/package/live_build_log/X11:lxde/lxqt-qtplugin/openSUSE_13.2/x86_64).

**Comment by pvanek** [comment] 2015-02-16 11:08
@v-fox can you tell me what apps are you rinning in the session? I use lxqt 0.9 on all y suse machines without any issue (except malformed systray). Do you run 32b or 64b distro?

**Comment by sfalken** [comment] 2015-02-16 17:34
On Sun, 2015-02-15 at 06:55 -0800, Jerome Leclanche wrote:
> @lxde/release-maintainers Can someone from opensuse take a look at
> this please?
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 

Please file a bugreport in the openSUSE bugzilla, I am not seeing these
issues on Tumbleweed with the latest 0.9.0 builds.

**Comment by sfalken** [comment] 2015-02-24 17:38
This issue should now be fixed on openSUSE, it had to do with lxqt-qtplugin, and incompatibilities with the installed qt5 version.   I've done about ten different installs in the last week, and all of them have brought up a proper desktop.

**Comment by v-fox** [comment] 2015-02-24 23:52
@sfalken I specifically pointed out that i even tried disabling lxqt-qtplugin altogether. It changed nothing. I also tried LXQt build against Qt 5.4. Again, nothing. So i pretty sure that it has nothing to do with qtplugin.
And even if it were, Tumbleweed is not a release of openSUSE, it would be irrelevant.

And i tried it on quite a few different PCs also. Same result.
@pvanek It's 64bit, obviously. Tried it with all autostart disabled, no change. Here's my current setup:
![window - lxqt session settings - 2015-02-25_04 44 14](https://cloud.githubusercontent.com/assets/362763/6361938/1f9a3f06-bca9-11e4-9865-182f8086d822.jpg)

From "non-standard" things, i've replaced `pcmanfm-qt --desktop --profile=lxqt` from lxqt-desktop.desktop with `nitrogen --restore` because LXQt's wallpaper handling is garbage. But i'm pretty sute that i tried with that disabled too.

When i can I will try to make openSUSE live build with broken LXQt for you to feel it out yourself.

**Comment by sfalken** [comment] 2015-02-25 00:25
@v-fox I've no idea what you mean by "Tumbleweed is not a release of openSUSE"  it most certainly is.

Spinning up a 13.2 VM right now to verify that it works there.

**Comment by PCMan** [comment] 2015-02-25 01:12
From "non-standard" things, i've replaced pcmanfm-qt --desktop
--profile=lxqt from lxqt-desktop.desktop with nitrogen --restore because
LXQt's wallpaper handling is garbage. But i'm pretty sute that i tried with
that disabled too.

As the author of the "garbage", I'd like to know how to improve that. Any
suggestions?

> When i can I will try to make openSUSE live build with broken LXQt for
you to feel it out yourself.

**Comment by jleclanche** [comment] 2015-02-25 01:47
@PCMan We had similar issues in razor-qt, where razor-desktop was garbage and we wanted to replace it with another app. But it didn't go anywhere, pcmanfm replaced it.

**Comment by sfalken** [comment] 2015-02-25 01:56
Please see http://youtu.be/z5yfn85OXms   That is a fresh install of openSUSE 13.2 with the currently published X11:lxde repo providing lxqt and it's assorted bits.   I didn't check every screen to keep my upload size to something decent, but it installs and works fine.

**Comment by v-fox** [comment] 2015-02-25 09:09
> @v-fox I've no idea what you mean by "Tumbleweed is not a release of openSUSE" it most certainly is.

It's no more a release than a git master branch is.

> As the author of the "garbage", I'd like to know how to improve that. Any suggestions?

pcmanfm-qt itself is a nice little thing but it's desktop mode is no good (at least for me) because:
0) It treats desktop as directory, WIndows-style. That's a bad habbit, not as bad in Linux with proper /home separation thought.
1) There is no "scale with crop" mode for wallpapers, in fact, i don't think there is even "scale while keeping aspect ratio" option.
2) No multiscreen support,
Nitrogen fulfils that role much better. However, a major improvement for its main mode would be dolphin-like session handling, with windows and tabs restoring on login. For now i'm using krusader as main FM but its development seems quite dead.

**Comment by sfalken** [comment] 2015-02-25 16:17
@jleclanche as far as the openSUSE maintainer is concerned, this is a fixed issue, everything installs and works on both the 13.2 point release, and the Tumbleweed rolling release, please mark as such, the desktop image discussion isn't openSUSE specific.

**Comment by paulolieuthier** [comment] 2015-04-27 13:43
@v-fox are you still able to reproduce this issue?

@heliocastro I'm having issues with GCC 5 as well. Compiled binaries such as lxqt-panel won't even run ("address boundary error"). I'm using clang now.

**Comment by heliocastro** [comment] 2015-04-27 15:26
The issue was new gcc 5.0 + qt 5.4.0. Was Qt issue.

At least for us in Fedora all are stable now on 5.4.1

[]'s

**Closed** 2015-04-27 20:31 UTC
Labels: crash
