### ISSUE TITLE
Panel external plugin, pluginsettings.h

### ISSUE THREAD

**Issue by zjes** [lxde/lxqt#949] opened 2016-02-04 13:32 UTC
Hi, 
If it not a bug, but feature by design - close it.
Public interface of the lxqpanelplugin contains not public pluginsettings.h. Implementation of this pluginsettings in lxqt-plugin executable. So, impossible use it for external plugin without extra work.

**Comment by pmattern** [comment] 2016-02-05 01:21
Somewhat related to #162...

**Comment by palinek** [comment] 2016-02-05 07:15
> Somewhat related to #162...

Not directly... this is a "regression" introduced by lxde/lxqt-panel#244.

To allow developing of the 3rd party plugins we need to somehow publish the introduced `PluginSettings` class...

@paulolieuthier @jleclanche @luis-pereira 
Are we going to crate new `IPluginSettings` virtual class and publish that or simply publish the *pluginsettings.h* header?

**Comment by zjes** [comment] 2016-02-05 07:55
Like a workaround allow external plugin have own config (Do not use settings thru ILXQtPanelPluginStartupInfo, and PluginSettings can be just forward declaration and remove this include from lxpanelplugin header). IMHO, this is better solution.

**Comment by palinek** [comment] 2016-02-05 10:56
> Like a workaround allow external plugin have own config (Do not use settings thru ILXQtPanelPluginStartupInfo, and PluginSettings can be just as forward declaration and remove this include from lxpanelplugin header). IMHO, this is better solution.

Of course we can do the forward declaration, but normaly we would like to store configurations of all plugins into one file => the plugin need to know how to get the configuration from `PluginSettings` object => it needs to be public.

**Comment by zjes** [comment] 2016-02-05 11:13
> normaly we would like to store configurations of all plugins into one file

Hmmm, in case of external plugins too? Ok... :)

**Comment by palinek** [comment] 2016-02-05 11:15
> >normaly we would like to store configurations of all plugins into one file

> Hmmm, in case of external plugins too? Ok... :)

Why shouldn't we?

**Comment by zjes** [comment] 2016-02-05 11:22
External plugins can have same sections, can broke config, can have different format, what else... In short words - not under control of lxqt team. :)

**Comment by palinek** [comment] 2016-02-05 11:37
That is exactly what is `PluginSettings` about. It doesn't allow you to go *outside of your section*. The *section* is defined by the panel, not be the plugin itself.

**Comment by paulolieuthier** [comment] 2016-02-05 14:14
>  Are we going to crate new IPluginSettings virtual class and publish that or simply publish the pluginsettings.h header?

@palinek what's your opinion? I think exporting the header is enough, since most plugins won't need to extend it, I think.

**Comment by palinek** [comment] 2016-02-05 14:16
> @palinek what's your opinion? I think exporting the header is enough, since most plugins won't need to extend it, I think.

Agreed...

**Comment by palinek** [comment] 2016-02-05 15:17
How about the lxde/lxqt-panel#301 ?

**Comment by zjes** [comment] 2016-02-05 16:24
Forward declaration... I like it :)

**Comment by PCMan** [comment] 2016-02-05 18:01
@paulolieuthier @palinek @zjes In theory, I'd say IPluginSettings interface is better.
This piece of code is in the binary of lxqt-panel, but you intend to call it from third party external plugins. Calling a function in the executable file back from an external library is what we call "back linking". While it seems to work, this is neither portable nor standard. It just happens to be supported by GNU toolchain.
If you need to use a piece of code in the main program and another library, the standard way is to put that piece of code in a separate library, and everyone need the code should link to the library.
That exactly the reason why gnome-panel needs a separate panel applet library..
The reason why IPluginSettings interface will work is obvious. There is nothing to directly link with. Every methods is called via indirect branch and the address is provided by the vtable. So it's not handled by the dynamic linker in the same way as others (unless being optimized by the linker).
If we only want to support GNU platforms, this is no issue.
Otherwise, relying on back-linking is non-portable.

**Comment by palinek** [comment] 2016-02-08 10:04
@PCMan you're right. Could you, please, review the lxde/lxqt-panel#301. Is making all the methods virtual enough?

**Comment by PCMan** [comment] 2016-02-08 10:39
@palinek Here are some discussions on this issue.
The doc from autotools suggest avoiding back-linking.
https://www.sourceware.org/autobook/autobook/autobook_99.html
However, few platforms do not support the feature (mainly Windows and AIX, which are not our targets)
http://mdcc.cx/pub/autobook/autobook-latest/autobook.pdf
So, after some more consideration, I'd say we might not need to be so portable.
Sorry to misguide you to use virtual functions and waste your time. I just saw that ILXQtPanel and ILXQtPanelPlugin interfaces are used from the beginning of the project and they work well.
Actually, the vtable trick is not guaranteed to be portable, either.
It's not part of the standard. We just rely on the implementation detail of the compilers and luckily it works. So it's not more portable.
In addition, to avoid the linking, I believe that you have to use a abstract class which contains no implementation at all. Otherwise, some symbols may still need to be resolved by the dynamic linker.
Sorry for wasting your time. I'd say just use back-linking since we don't plan to support Windows.
If some day we need to make it more portable, let's create liblxqt-panel to solve this issue. That's the only portable way to do this.

**Comment by palinek** [comment] 2016-02-08 10:40
:smile:

**Comment by palinek** [comment] 2016-02-08 10:42
And how about hiding the c-tor? Should we leave public or hide it?

**Closed** 2016-03-07 08:30 UTC
Labels: idea/discussion, lxqt-panel
