### ISSUE TITLE
pcmanfm-qt: cannot delete to trash

### ISSUE THREAD

**Issue by hifi25nl** [lxde/lxqt#512] opened 2015-02-25 12:34 UTC
With lxqt 0.9 pcmanfm-qt is missing  "move to trash" in context menu (I can only delete), but I have trash enabled in configuration:

[Behavior]
AutoSelectionDelay=600
ConfirmDelete=true
NoUsbTrash=false
SingleClick=true
UseTrash=true

**Comment by PCMan** [comment] 2015-02-25 13:08
Maybe you forgot to install "gvfs".

**Comment by hifi25nl** [comment] 2015-02-25 13:14
No,  gvfs is installed.

**Comment by qsodev** [comment] 2015-03-07 15:38
I have a similar issue: 
"move to trash" is missing after reboot/login, only "delete is shown". 
Also the entry in "preferences->behavior->move deleted files to trash..." is missing.

When I click to "trash icon" and then right-click. pcmanfm-qt crashes and restarts.
After that I have "move to trash" again and also the entry in preferences->behavior.
Also when I killall pcmanfm-qt and restart it I have "move to trash" again.

After next reboot, "move to trash" is gone again

**Comment by hifi25nl** [comment] 2015-03-07 15:52
I don't know if this is related but directory
/home/$USER/.config/pcmanfm-qt/default 
is owned by root.

Is this normal?

**Comment by pmattern** [comment] 2015-03-12 16:00
@hifi25nl
~/.config is meant to save user settings. So no, nothing herein should be owned by root.
Note that trash "can" itself is usually handled by a folder in ~/.local/share, normally ./Trash.
More information on all those directories can be found in freedesktop.org's [Base Directory Specification](http://www.freedesktop.org/wiki/Specifications/basedir-spec/) and [Desktop Trash Can Specification](http://www.freedesktop.org/wiki/Specifications/trash-spec/).

**Comment by urbanomad64** [comment] 2015-03-13 13:31
I have this same issue and have asked on the Manjaro Forum, here https://forum.manjaro.org/index.php?topic=20698.0 I thought it had been solved by uninstalling and reinstalling pcmanfm-qt. It did work until a shutdown. Upon start up it was back to no Computer and move to Trash

**Comment by hifi25nl** [comment] 2015-03-16 11:11
What is strange is that in a system with both plasma 5 and lxqt move to trash is working.
It is not working only on two other systems lxqt only.

**Comment by Thorn-Inurcide** [comment] 2015-03-20 03:30
I have this issue if I log into Slackware with gdm using the *.desktop file, but if I startx from the command line using A slackware xinitrc that looks like this, I don't have the issue

#!/bin/sh
# $Xorg: xinitrc.cpp,v 1.3 2000/08/17 19:54:30 cpqbld Exp $

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[ -f $sysresources ] && /usr/bin/xrdb -merge $sysresources
[ -f $sysmodmap ] && /usr/bin/xmodmap $sysmodmap
[ -f $userresources ] && /usr/bin/xrdb -merge $userresources
[ -f $usermodmap ] && /usr/bin/xmodmap $usermodmap


if [ -z "$DESKTOP_SESSION" -a -x /usr/bin/ck-launch-session ]; then
  exec ck-launch-session dbus-launch --exit-with-session startlxqt
else
  exec startlxqt
fi

Don't know if that helps are not

**Comment by Thorn-Inurcide** [comment] 2015-03-20 03:55
I just set my lxqt.desktop file in /usr/share/xsessions to start from my xinitrc file and it works well. Though this is only a Slackware workaround I can easily accomplish in many ways with the build script. 

Seems like all "resources" aren't being loaded... I have no idea how to properly say that =D

**Comment by Thorn-Inurcide** [comment] 2015-03-20 03:58
hifi25nl are you using kwin as your window manager?

**Comment by hifi25nl** [comment] 2015-03-20 07:24
The same is happening on three lxqt installations using openbox.

**Comment by Thorn-Inurcide** [comment] 2015-03-20 07:34
yeah I'm using openbox as well, You said it wasnt happening on a machine with Plasma 5 i was just wondering if you were using kwin

**Comment by hifi25nl** [comment] 2015-03-20 07:45
I just checked now. In the machine with both Plasma 5 and lxqt, if I start pcmanfm from plasma or lxqt (with openbox) move to trash is there and it is working.

**Comment by Thorn-Inurcide** [comment] 2015-03-20 08:40
Do you have a .xinitrc in your home folder on the machines where it isn't letting you move to trash?
I deleted mine, rebooted then logged in with gdm and one wasn't there, I made one and simply added xrdb (This loads X system resources) and logged out and back in and now pcmanfm-qt is working right.
Wanna try and see if it works for you? if it does will be a nice easy work around. though not a solution to the actual problem.

**Comment by hifi25nl** [comment] 2015-03-20 14:07
I don't have a .xinitrc

**Comment by Thorn-Inurcide** [comment] 2015-03-20 14:58
you should try making one, then just put xrdb in it

**Comment by PCMan** [comment] 2015-03-25 04:44
Pretty weird. I can never reproduce this bug.
Would you please try the following command and see if it works?
 gvfs-info trash:///

Normally, this should ask gvfs to show the info about the trash can.
If your gvfs is working correctly, you should see some output.
Otherwise, you'll see an error message.

**Comment by hifi25nl** [comment] 2015-03-25 13:40
[audiolinux@archaudio ~]$ gvfs-info trash:///
display name: Trash
name: /
type: directory
uri: trash:///
attributes:
  standard::type: 2
  standard::name: /
  standard::display-name: Trash
  standard::icon: user-trash
  standard::content-type: inode/directory
  standard::symbolic-icon: user-trash-symbolic
  id::filesystem: trash:
  trash::item-count: 0

**Comment by qsodev** [comment] 2015-03-26 16:35
This is probably not a pcmanfm-qt bug. It could be related to login / session.
It seems that gvfs is not ready when pcmanfm-qt starts. 
When I have the problem ( after reboot ) there is also no "Computer" and "Network" shown in "Places".
When I then execute "pkill pcmanfm-qt", it restarts and then everything is working fine and also "Computer" and "Network" show up.
I use slim as login manager and I just use "exec startlxqt" in .xinitrc
The strange thing is that I have this setup on another computer and there is not problem at all... :-/
Hopefully this helps.

**Comment by PCMan** [comment] 2015-03-26 17:28
I just fixed it. Please try the latest source code in git and see if it works for you.
Thank you for help debugging.

**Comment by PCMan** [comment] 2015-03-26 17:28
If the bug is fixed, please close the issue. Thanks!

**Comment by qsodev** [comment] 2015-03-26 18:39
"move to trash" is fixed when using latest source code!
But there is still the issue that "Computer" and "Network" does not show up until pkill and restart pcmanfm-qt.

**Comment by pmattern** [comment] 2015-03-28 09:45
I can confirm both findings described by qsodev. The problem regarding trash is fixed but the one affecting items Computer and Network persists.

The latter is pretty weird to track. E. g. I can't see it any more on two virtual machines but still on my production system ("bare metal"). All up to date Arch Linux x86_64 except one of the VMs which is i686, all actually set-up the same way. In particular, latest Git code of all LXQt components was compiled yesterday on all of them.
I doesn't seem to matter whether sessions are started from virtual terminal by startx or by a display manager (SDDM Git).

Maybe PCManFM-Qt needs some other component to show these two items that's either not detected correctly or not yet available when PCManFM is launched?

**Comment by PCMan** [comment] 2015-03-29 08:30
OK I found the problem. It seems to be a bug(?) of glib/gio.
I believe that the current fix can workaround the problem.
If it does not work, please re-open the issue.
Thank you.

**Closed** 2015-03-29 08:29 UTC
Labels: pcmanfm-qt
