### ISSUE TITLE
quick launch widget (on lxqt-panel) cannot be moved

### ISSUE THREAD

**Issue by excalibur1234** [lxde/lxqt#545] opened 2015-03-14 19:59 UTC
i have created multiple quick launch widgets on my panel and i use them to start different programs. i have 3 groups of quick launch widgets on my panel (some quick launch widgets are on the left and some are on the right of the panel.

i have tested this a little bit, but not extensive: it looks like the "move left" and "move right" command in the right click menu of the quick launch widgets work only when all quick lauch widgets are next to each other. when you have multiple groups of quick lauch icons, the "move left" and "move right" command are greyed out and do not work anymore.

all other widgets (at least the widgets i use) have a nice "move <widgets name here>" option in their right click menu. this works perfectly.
please fix the "move left" and "move right" commands or add a "move quick launch widget" to the right click menu.

**Comment by pmattern** [comment] 2015-03-15 22:18
Regarding the context menus of icons added to Quick launcher I can't confirm your findings. E. g. in this Quick launcher instance
![quicklaunch - icon menu](https://cloud.githubusercontent.com/assets/9860801/6658417/f22e32f6-cb68-11e4-841f-2e208d44db4b.png)
which is the middle of three icons "Chromium" and "Firefox" can be moved to the the left and right, the one from Quassel to the right only and Thunderbird's to the left only. All this makes perfect sense as those arrows "Move left / right" are about moving *within the Quick launcher instance*.

Quick launcher does feature a context menu that affects an instance as a whole and allows for moving it within panel. Problem is that this menu is only available as long as no icons / applications have been added.
![quicklaunch - plugin menu](https://cloud.githubusercontent.com/assets/9860801/6658420/02ed7b60-cb69-11e4-881a-daf4ad5fdec9.png)
But this is actually the problem addressed in #536 (which you've already commented, too).

**Closed** 2015-03-16 06:55 UTC

**Comment by excalibur1234** [comment] 2015-03-16 15:40
there are 2 issues here: 

issue no. 1 is addressed in #536 
issue no. 2 is addressed here (but it is not as important as #536 )

1. after you have added an icon to a quick lauch widget, the "move quick launch" option is no longer available in the right click menu. thanks for telling me, i was not aware of this until now. it is really counter-intuitive to remove the icon from the quick launch widget, then move it, and add the icon again. 
this should really get improved, e.g. by removing the "move left/right" option and adding the "move quick launch" option.
i would also like a way to modify the icon directly from the right click menu of the quick launch widget (instead of modifying the .desktop file of the icon).

2. the "move right/left" right click option is mostly broken for me (i use the lastet arch packages, but i have built lxqt-common-git and lxqt-panel-git from the AUR):
i added 2 additional quick launch widgets to my panel (default panel) and i added icons to them:
http://imagizer.imageshack.com/img537/9743/TqwtTk.png
now, i have 3 quick launch widgets with icons next to each other: terminal, desktop, and pcmanfm. i cannot move any of them.

**Comment by pmattern** [comment] 2015-03-16 19:53
ad 1
> after you have added an icon to a quick lauch widget, the "move quick launch" option is no longer available in the right click menu

Strictly speaking this is wrong. Rather, *two different context menus* exist, one that belongs to eventually added icons and one that belongs to a Quick launch instance as a whole. Compare the two screenshots in my previous post. The menu corresponding to the instance as a whole isn't accessible any longer once an icon has been added.

ad 2
As said as well, those arrows "Move left / right" are to move *within a single* instance of Quick launch. So if you have one icon per instance, what do you want to move?!
One could discuss whether it should be possible to move among different instances if they're adjacent. But right now these findings are a feature, not a bug.

Aside from this mixing different versions of different components is a source of all kinds of artifacts and should be avoided.
Any means to have the icons set from this widget's context menu is a totally unrelated feature request.
