### ISSUE TITLE
pcmanfm-qt: long startup time?

### ISSUE THREAD

**Issue by excalibur1234** [lxde/lxqt#627] opened 2015-04-29 13:32 UTC
compared to pcmanfm-qt version 0.9.0, the latest build of pcmanfm-qt needs much longer to start the first time.

when i reboot my computer i see pcmanfm-qt in my task manager as a daemon running. it uses roughly 90mb. when i start pcmanfm-qt for the first time it needs about 3-5 seconds (despite the daemon running and me using a SSD). the second time i start pcmanfm-qt it needs just a second (or much less) to start. if i recall correctly, this used to be different no so long ago.

can anybody confirm these performance problems?

**Comment by MttCastelli** [comment] 2015-05-01 10:44
I can confirm the long startup time, but before my latest reinstall I used preload...

**Comment by paulolieuthier** [comment] 2015-05-01 14:02
I confirm.

**Comment by PCMan** [comment] 2015-05-01 14:33
This seems to be related to the fix to check whether gvfs is initiated.
I'll look into this. Thanks for reporting.

**Comment by PCMan** [comment] 2015-05-05 14:07
fixed in https://github.com/lxde/pcmanfm-qt/commit/ba3eb765197b52969f06e6dce23e2eeb5a1c5844

**Comment by paulolieuthier** [comment] 2015-05-23 13:36
@PCMan I think it's still very slow compared to previous builds.

**Comment by paulolieuthier** [comment] 2015-09-30 11:12
Can not reproduce it anymore.

**Closed by paulolieuthier** 2015-09-30 11:12 UTC
Labels: high-priority, pcmanfm-qt
