### ISSUE TITLE
lxqt-config: Runtime error while loading shared libraries (liblxqt-config-cursor)

### ISSUE THREAD

**Issue by luis-pereira** [lxde/lxqt#793] opened 2015-08-23 15:41 UTC
After commit  https://github.com/lxde/lxqt-config/commit/f7dd81930f389fc84b7caac94187c8487632a725 the dynamic linker (default configuration) will not find `liblxqt-config-cursor`.

**Comment by luis-pereira** [comment] 2015-08-23 17:04
@agaida Why do we need https://github.com/lxde/lxqt-config/commit/f7dd81930f389fc84b7caac94187c8487632a725 ?

**Comment by paulolieuthier** [comment] 2015-08-24 23:25
Debian policies do not allow unversioned libraries to be put in the standard library directories. We should version them, or put them somewhere else for the packages to get into Debian repositories.

**Comment by agaida** [comment] 2015-08-25 13:00
Maybe a private library (with correct settings in cmake would be a solution too - i would prefer that)

**Comment by luis-pereira** [comment] 2015-08-26 11:43
@agaida That's the best solution IMO. I can't implement it right now. If someone wants to do it, go ahead.

**Comment by paulolieuthier** [comment] 2015-08-26 13:27
@luis-pereira can you please explain how it should be done? I don't think I've ever done that. BTW, I solved the problem on my machine by adding version information to liblxqt-config-cursor. The same version as liblxqt, automatically. Looks very simple to me. What do you think?

**Comment by agaida** [comment] 2015-08-26 16:43
the question is - is the library really needed as a shared library?

**Comment by paulolieuthier** [comment] 2015-08-26 21:37
It is a shared library because both lxqt-config-appearance and lxqt-config-input uses it.

**Comment by pmattern** [comment] 2015-08-26 21:43
> because both lxqt-config-appearance and lxqt-config-input uses it.

which is a redundancy that was - IMHO rightly - criticised in #658.

**Comment by agaida** [comment] 2015-08-26 21:49
@paulolieuthier - ok, if both programs use this library and it should stay that way - the lib must have a version - solved. If we follow pmattern and #658 it should be private.

**Comment by paulolieuthier** [comment] 2015-08-27 01:42
@pmattern simply removing the cursor appearance page from lxqt-config-input (which is what #658 proposes) wouldn't solve this issue (although I agree with #658). Both lxqt-config-input and lxqt-config-appearence would continue depending on the library. What do you suggest?

@agaida I still don't know what "private" means here. Just not available in `/usr/lib` and friends (like in your last patch)? Anyway, I'd commit the version fix, but I'm waiting @luis-pereira's opinion on this.

**Comment by agaida** [comment] 2015-08-27 01:53
http://stackoverflow.com/questions/14486335/how-to-package-shared-library-in-deb-packages - if i understand this right, this is it. - but i'm ok with a versioned lib

**Comment by palinek** [comment] 2015-08-27 06:17
How about lxde/lxqt-config@0818173 ? Does it solve everything stated here?

**Comment by paulolieuthier** [comment] 2015-08-27 09:57
@palinek I can't test it now, but it looks nicer.

**Comment by agaida** [comment] 2015-08-27 17:04
@palinek - looks good and 'Works for me'™ - if no objections gtm

**Comment by paulolieuthier** [comment] 2015-08-27 19:13
@palinek ship it.

**Comment by tsujan** [comment] 2015-11-19 20:53
I'm too late here but a few minutes ago, I upgraded my installtion of lxqt-config and the same thing happened:

```
lxqt-config-appearance: error while loading shared libraries: liblxqt-config-cursor.so: cannot open shared object file: No such file or directory
```

Of course, the problem is fixed by making a symlink. I'm on 64-bit Debian and build deb packages out of LXQT sources. The library in question was inside `/usr/lib/x86_64-linux-gnu/lxqt-config/` and the symlink is inside `/usr/lib/x86_64-linux-gnu/`.

**Comment by palinek** [comment] 2015-11-20 08:02
@tsujan This is probabaly because of stripping the RPATH from binaries. Are you using using any of the CMAKE_\*_RPATH variables while building your packages/binaries? (ref. https://cmake.org/cmake/help/v3.0/command/set_target_properties.html & lxde/lxqt-config#69)

**Comment by tsujan** [comment] 2015-11-20 11:50
I always use cdbs (`dh_make -n -s -r cdbs`). debian/rules is simply:

```
#!/usr/bin/make -f

include /usr/share/cdbs/1/rules/debhelper.mk
include /usr/share/cdbs/1/class/cmake.mk
```

Then, the package is built by `dpkg-buildpackage -rfakeroot`.

**Comment by tsujan** [comment] 2015-11-20 11:55
`/usr/share/cdbs/1/class/cmake.mk` includes this line:

`DCMAKE_SKIP_RPATH=ON -DCMAKE_VERBOSE_MAKEFILE=ON `

**Comment by palinek** [comment] 2015-11-20 12:10
> `DCMAKE_SKIP_RPATH=ON -DCMAKE_VERBOSE_MAKEFILE=ON`

That's it...you need to override the CMAKE_SKIP_RPATH variable.

**Comment by tsujan** [comment] 2015-11-20 14:09
I disagree. This can be seen as an inconvenience, at least. CDBS is the standard method of making deb packages under all debian based distros and that line is there *by default*. On the other hand, this problem *only* occurs with lxqt-config. I know how the issue can be fixed in the deb package but that's just a specific workaround for this specific case.

**Comment by tsujan** [comment] 2015-11-20 14:17
In simple words, a change in lxqt-config has broken a debian standard. Of course debian is flexible but what could you say: is it debian's fault of lxqt-config's?

**Comment by doktor5000** [comment] 2015-12-08 15:36
+tsujan: +1 here, same issue. It's certainly not debian's fault, disabling RPATH is standard packaging policy also for Fedora and e.g. Mageia. lxqt-config is also broken here since 0.10. 

Is liblxqt-config-cursor.so now a shared library, hence version information should be added like @paulolieuthier did locally? Or is it a "private library", then it should stay in a subdirectory but RPATH usage needs to be fixed.

**Comment by doktor5000** [comment] 2015-12-08 17:48
Discussed briefly with @palinek and RPATH has to be enabled. RPATH is fine for "private libraries" - this is also documented at e.g. https://fedoraproject.org/wiki/Packaging:Guidelines#Rpath_for_Internal_Libraries and also referred to from https://wiki.debian.org/RpathIssue as acceptable RPATH usage.

FWIW, enabling the usage of RPATH alone is not sufficient, at least here also https://github.com/lxde/lxqt-config/commit/cd0a3ba182ae8cd03066ce7da6d7f475a72c27f5 is necessary.

The result can be verified via `readelf -d /usr/bin/lxqt-config-appearance | grep -iE "RPATH|RUNPATH"` and check if you see either RPATH or RUNPATH set to $LIBDIR/lxqt-config/ - in case it's not there lxqt-config-appearance will be broken.

Sidenote: By default we pass `-Wl,--enable-new-dtags` to the linker, which causes RPATH to be changed into RUNPATH - which effectively achieves the same goal, only difference is that it's considered after LD_LIBRARY_PATH but still before system ld.so cache

**Comment by palinek** [comment] 2016-03-07 12:28
@tsujan Do you still need this to be open?

**Closed** 2016-06-21 07:45 UTC
Labels: high-priority, lxqt-config, regression
