### ISSUE TITLE
[lxqt-config-locale] Month when 'Detailed Settings' with Germany selected, displays M11 for November

### ISSUE THREAD

**Issue by urbanomad64** [lxde/lxqt#894] opened 2015-11-14 13:48 UTC
My operating system is in English but since I live in Germany, I have selected the appropriate settings. 
* Month displays as 'Mxx' instead of the name of the month. 
* The '€' sign should be after the number and not before it. 
* Numbers should be a '.' for thousands separator and a ',' for cents.
![lxqt-locale_region_detailed_settings](https://cloud.githubusercontent.com/assets/1598573/11163836/2ce8c55c-8ade-11e5-8ad9-cfc0fbdc4d43.jpg)

**Comment by pmattern** [comment] 2015-11-14 14:06
You should be good to go if you chose `Deutschland - Deutsch (de_DE)` in `Detailed Settings` which is the regular German ("Hochdeutsch"). Locale `nds_DE` is just some local accent spoken in northern Germany only.

Basically this boils down to the list presented to yours being far from perfect, see #886.

**Comment by urbanomad64** [comment] 2015-11-14 16:04
Thank you! That's not a mess at all ;-)

**Comment by pmattern** [comment] 2015-11-14 18:55
Nice.

If I got this right and the problem is solved you may consider closing it. Button `Close and comment` below the form to file comments which may remain empty.

**Closed** 2015-11-15 16:29 UTC
