### ISSUE TITLE
LXQt locale setting forget country settings

### ISSUE THREAD

**Issue by szg0000** [lxde/lxqt#1270] opened 2017-03-12 18:34 UTC
LXQt locale setting forget the country settings or other program overwrites.

* Distribution & Version: Debian stretch (sid)
* Kernel: 4.11-rc1
* Qt Version: 5.7.1
* liblxqt Version:  0110
* Package version:

**Comment by pmattern** [comment] 2017-03-12 19:11
Please name some steps to reproduce and what exactly doesn't work.

**Comment by szg0000** [comment] 2017-03-12 19:20
I don't remember how it happened. If I can reproduce it, I will tell you.

**Comment by tsujan** [comment] 2017-03-12 19:36
If another app overwrote the setting, it wouldn't be LXQt's fault ;) The question is, "was the LXQt locale config able to correct it?" Only if the answer is "no", this could be a bug.

**Comment by tsujan** [comment] 2017-03-14 14:30
Today, I encountered a problem in Manjaro after an upgrade; `locale` gave error messages. But I've been working under KDE for a week.

I found that `en_US.UTF-8` was commented out in "/etc/locale-gen". The problem was fixed after I uncommented `en_US.UTF-8` and ran `sudo locale-gen`.

Although my problem was different, it was about locale too. I really don't think this is an LXQt issue either.

**Comment by szg0000** [comment] 2017-03-15 15:47
Before you fixed the problem, you also had the same problems with file names?
What do you think, which package is the responsible for changeing "/etc/locale-gen" without the "user/root " approval?

**Comment by tsujan** [comment] 2017-03-15 15:59
> Before you fixed the problem, you also had the same problems with file names?

No! As I said at https://github.com/lxde/lxqt/issues/1269.

> which package is the responsible for changeing "/etc/locale-gen" without the "user/root " approval?

"/etc/locale-gen" belongs to glibc. It isn't about replacing some file without permission. When you update your system, you give root permission to the package manager of your distro; that's normal

My point was just that such issues could be caused by updates,

**Comment by luis-pereira** [comment] 2017-05-03 22:35
@szg0000 If you don't know how to reproduce it, there's little we can do.
Closing. Reopen if there's new info.

**Closed by luis-pereira** 2017-05-03 22:35 UTC
