### ISSUE TITLE
"Authentication failed for some reason"

### ISSUE THREAD

**Issue by easyaspi314** [lxde/lxqt#284] opened 2014-09-16 01:00 UTC
When LXQT loads an application that asks for root, a PolicyKit dialog starts. However, I find that it instantly fails, with a message popup *behind* the window saying "**Authentication failed for some reason**," making it useless, and impossible to close. It also does not ask for the *actual account* that is logged in, rather the dialog dropdown starts with another account on my computer.

It also does not use the actual name, rather "unix-user:(username)"

I can use `gksu` or `gksudo`, but for example, launching Synaptic from ALT-F2 is impossible, unless I type `gksudo synaptic`.

Ubuntu 14.04

**Comment by jleclanche** [comment] 2015-01-12 07:49
Is this still an issue?

**Comment by easyaspi314** [comment] 2015-01-12 11:59
Oops, sorry. I have not been on my Linux laptop recently, so I couldn't
really test. I will see if I can update and try it out again. I do
sometimes tend to forget about Github issues. :(

**Comment by paulolieuthier** [comment] 2015-01-12 12:21
@easyaspi314 I suggest you to install a github notifier extension for your browser (actually, everyone should use it) if you want. Let's close this issue for now, as it has probably been fixed, works perfectly here (although the "unix-user:(username)" thing is indeed annoying).

**Closed by paulolieuthier** 2015-01-12 12:21 UTC

**Comment by nbvcxz** [comment] 2016-08-20 09:10
Please reopen the issue as it probably still exists. It occurs in 2 of distros I use (both Arch Linux - git packages and Ubuntu 16.04 - main repo packages and previously 14.04):
I noticed when I have few users added (and also added to **sudo** group if it matters) when the polkit action is being done (eg. I try to install package with pacaur in Arch Linux only pam or synaptics in Ubuntu with sssd) it starts dialog **Authentication Required** (yes - the ugly unix-user:user_name). The problem is the user_name is not your current user, but the user with lowest uid. Then after ~ 1-2 sec. it appears another dialog with **Authentication failed Authentication failed for some reason**. This makes lxqt-policykit useless for now.
Summarizing: when you use 1 user (or first added user probably) there is no problem. If you have more users and you try to use lxqt-policykit with another user (with higher uid) it uses 1st user and fails.
ps. tried with no polkit agent and legay gnome polkit agent on Arch Linux (with lxqt) and it works fine (for pacmac-instll it asks about user to select and credentials, then runs program with no issue).

**Comment by stefonarch** [comment] 2016-08-20 10:43
Same here somehow, I thought it is my problem because my system is very old and copied twice.
2 users with sudo privileges, one starting with "a" has uuid 1001 and me stefano has uuid 1000 instead, so maybe it's alfabetically?

**Comment by paulolieuthier** [comment] 2016-08-20 11:59
@nbvcxz could you please create another issue for that?
