### ISSUE TITLE
lxqt-config: icon theme not found

### ISSUE THREAD

**Issue by orschiro** [lxde/lxqt#489] opened 2015-02-09 22:58 UTC
In reference to discussion #481:

My installed icon theme cannot be found in the latest version of `lxqt-config-git 0.9.0-1`.

![](https://cloud.githubusercontent.com/assets/170947/6108629/fbc4b916-b074-11e4-90de-5f57f1269a46.png)

```
numix-icon-theme 0.r287.ad07517-1
numix-icon-theme-square 1:0.r82.bb9313e-1
attica-qt4 0.4.2-1
fcitx-qt5 1.0.0-1
lib32-qt4 4.8.6-3
libdbusmenu-qt 0.9.2-3
liblxqt-git 0.9.0-1
libqtxdg-git 1.1.0.1.ge5bc7d7-1
lxqt-config-git 0.9.0-1
lxqt-qtplugin-git 0.9.0.2.gf1a0712-1
phonon-qt4 4.8.3-1
phonon-qt4-gstreamer 4.8.2-1
polkit-qt4 0.112-2
qt4 4.8.6-4
qt5-base 5.4.0-3
qt5-declarative 5.4.0-3
qt5-location 5.4.0-3
qt5-sensors 5.4.0-3
qt5-tools 5.4.0-3
qt5-translations 5.4.0-3
qt5-webchannel 5.4.0-3
qt5-webkit 5.4.0-3
qt5-x11extras 5.4.0-3
qt5-xmlpatterns 5.4.0-3
qtchooser 48-1
qtwebkit 2.3.4-1
```

```
/usr/share/icons  
❯ l
total 1M
drwxr-xr-x  2 root root 1M 2014-06-03 14:16:48.000000000 +0200 default
drwxr-xr-x  4 root root 1M 2014-12-20 09:41:30.000000000 +0100 locolor
drwxr-xr-x 12 root root 1M 2015-01-20 08:48:02.000000000 +0100 Adwaita
drwxr-xr-x  9 root root 1M 2015-01-20 08:48:31.612549167 +0100 HighContrast
drwxr-xr-x 12 root root 1M 2015-01-20 08:49:10.592337995 +0100 gnome
drwxr-xr-x  7 root root 1M 2015-01-31 20:13:37.604399817 +0100 Numix-Square
drwxr-xr-x 12 root root 1M 2015-01-31 22:19:20.728689815 +0100 Numix
```

**Comment by paulolieuthier** [comment] 2015-02-11 11:37
It happens with Breeze theme as well (well, it's actually worse, some components crash when selecting Breeze), I don't know why. You can use Elementary or Oxygen for now while the problem is being investigated.

**Comment by luis-pereira** [comment] 2015-02-11 15:39
We are not handling "Icon Theme/Inherits".

@paulolieuthier The fix for the crash is part of the sync-qiconloader libqtxdg branch (https://github.com/lxde/libqtxdg/commit/3b2b71bef46d3565db921c6a943c83ac0e8926b0). It landed on master today. Running the latest libqtxdg master should fix it. Confirm it, pls.

@orschiro @paulolieuthier This issue happens to a theme that inherit other/others themes. Although the theme icon preview not being shown, everything else works, i.e, if the user selects the theme, the icons should be properly loaded (with the exception of the icon preview, that doesn't use ```QIcon``` or ```Xdg::fromTheme()```). lxqt-config-appearance doesn't takes in account that a theme might be inheriting other theme and the icons might be located in the parent theme.

I'm taking this one.

**Comment by paulolieuthier** [comment] 2015-02-11 15:55
@luis-pereira very nice! Thanks. I'll confirm the crash fix.

**Comment by luis-pereira** [comment] 2015-02-11 17:09
@paulolieuthier It's not a *real crash*, actually, it's an assertion. If libqtxg is compiled on non debug mode it doesn't crash, but it doesn't load any icons. That's what @orschiro is getting. Running the latests libqtxdg one sould get something like this:
![screen-2015-02-11-08-35-27](https://cloud.githubusercontent.com/assets/62877/6151224/423dc158-b1c9-11e4-9149-15fbe81a3466.png)

The preview issue in the above shot, I'm fixing it today.

**Comment by luis-pereira** [comment] 2015-02-12 01:08
make it tomorrow. family life in the way.

**Comment by orschiro** [comment] 2015-02-12 08:14
@luis-pereira 

Thank you very much for your time looking into this issue!

**Comment by luis-pereira** [comment] 2015-02-13 22:21
@paulolieuthier Do you have some info on the crash ?

Update:
![screen-2015-02-12-16-19-17](https://cloud.githubusercontent.com/assets/62877/6196100/18f9ae5c-b38a-11e4-99f1-3b13f7483b74.png)
The preview icons we are using don't show the differences between base and derived themes. Doing some research to see if can come up with sensible ones before pushing.

![screen-2015-02-12-16-58-34](https://cloud.githubusercontent.com/assets/62877/6196205/3119b346-b38b-11e4-88f1-0cde86cd16d1.png)

**Comment by paulolieuthier** [comment] 2015-02-13 22:40
Just updated lxqt here. What crashes is PCManFM-Qt. And the only icon theme it doesn't crash when changing to is Oxygen. However changing icon themes now work, including Breeze. And the screenshot:

![screen](https://cloud.githubusercontent.com/assets/1238157/6196564/1505689e-b3b8-11e4-8635-6d21e01ad27c.png)

**Comment by luis-pereira** [comment] 2015-02-13 22:51
@paulolieuthier I'm also getting pcmanfm-qt crashes. But changing the Widget Style **not** the icon theme. Initially I thought it only happened when changing to the Breeze Widget Style.... but I just got one pcmanfm-qt crash changing to the qtcurve.

**Comment by paulolieuthier** [comment] 2015-02-14 09:18
I'd like to be more helpful but I'll be afk in the next few days.

**Comment by luis-pereira** [comment] 2015-03-03 17:29
https://github.com/lxde/lxqt-config/tree/icon-theme-preview
It uses QtXdg::QIconLoader at https://github.com/lxde/libqtxdg/pull/47

**Comment by paulolieuthier** [comment] 2015-03-03 17:30
I'll test it today.

**Comment by paulolieuthier** [comment] 2015-03-03 17:46
Working great, just some missing icons (like klipper's and panel's mount plugin's) with some themes, like Breeze, Adwaita and Faenza.

![screen](https://cloud.githubusercontent.com/assets/1238157/6468438/d2cdd2d6-c1b3-11e4-99a6-8e0d290e207c.png)

**Comment by luis-pereira** [comment] 2015-03-04 17:14
@paulolieuthier I don't know about klipper. But I do know about the mount-plugin icon. That's an known issue. That's the result of: ```setIcon(XdgIcon::fromTheme(QStringList() << "device-notifier" << "drive-removable-media-usb" << "drive-removable-media"));```. ```XdgIcon:fromTheme()``` will iterate over the icons names until it finds a one that exists (in the current icon theme). QIconLoaderEngine will store the icon name. When the icon theme changes QIconLoaderEngine will search for the icon name in the new theme. It will not search the three icons we passed to ```XdgIcon::fromTheme()```.
Example:
If one starts the panel with the oxygen theme set the device-notifier icon will be used. If them we select Faenza..... we will get no icon. But if we start the panel with the Faenza the drive-removable-media-usb icon will be used, that doesn't exist on the Adwaita theme.

**Closed** 2015-03-09 21:43 UTC
Labels: lxqt-config, qss/themes

**Comment by luis-pereira** [comment] 2015-03-09 22:26
@orschiro it landed on master today. Pls update libqtxdg and of course lxqt-config

**Comment by orschiro** [comment] 2015-03-10 07:37
@luis-pereira 

Thanks very much for updating!
