### ISSUE TITLE
Application menu not updating?

### ISSUE THREAD

**Issue by Soukyuu** [lxde/lxqt#809] opened 2015-09-05 13:13 UTC
I'm running lxqt 0.9.1 on arch linux x64. I'm using KDE's dolphin as my file manager, and it was updated from the KDE4 version to the kf5 version. The application menu still lists the old KDE4 version, however, even after a reboot. The result is that I can no longer start dolphin from the menu, nor pin it to the quick launch. Looking at the error message ("File/URL '/usr/share/applications/kde4/dolphin.desktop' cannot be embedded into QuickLaunch for now"), it seems to be still thinking dolphin4 is installed, but it is not.

**Comment by pmattern** [comment] 2015-09-05 14:16
Duplicate of #65.

Btw. an *LXQt* version 0.9.1 doesn't exist. You may want to clarify what you're running, e. g. release 0.9 from the official repos or the VCS packages from the AUR.

**Closed by pmattern** 2015-09-05 14:16 UTC

**Comment by Soukyuu** [comment] 2015-09-05 14:29
For some reason lxqt-common has the version of 0.9.1, while the others are 0.9.0:

![lxqt](https://cloud.githubusercontent.com/assets/2095054/9699647/3376662e-53eb-11e5-9601-01ff1aaa53e7.jpg)

As you can see, I'm using the official repos.

**Comment by pmattern** [comment] 2015-09-05 14:37
> For some reason lxqt-common has the version of 0.9.1, while the others are 0.9.0.

Sure, I know. And it's not a problem and I didn't mean to criticise. It's just good to know the exact version a user is running in many respects.
