### ISSUE TITLE
lxqt-leave dialog choosing option using keyboard does not work

### ISSUE THREAD

**Issue by renegat** [lxde/lxqt#1332] opened 2017-08-05 18:07 UTC
Environment:
Arch Linux 
Kernel: 4.12.4-1-ARCH #1 SMP PREEMPT Fri Jul 28 18:54:18 UTC 2017 x86_64 GNU/Linux
openbox 3.6.1-3
qt5-base 5.9.1-3
liblxqt 0.11.1-1

Packages affected:
LXQt Leave Session Module: lxqt-session 0.11.1-1

General summary of the issue:
When choosing an option by using keyboard cursor keys and than press 'enter' the highlighted option does not work.
Choosing the option with the mouse cursor and klicking left mouse button does work.

What it should do:
lxqt-leave dialog should also be usable with keyboard.

How to reproduce:
Open the lxqt-leave dialog, navigate to one option wit the cursor keys, hit enter.
The dialog box closes but nothing happens.

**Comment by palinek** [comment] 2017-08-08 08:23
Duplicate of #1183

**Closed by palinek** 2017-08-08 08:23 UTC
