### ISSUE TITLE
Missing keyboard layout icon

### ISSUE THREAD

**Issue by postadelmaga** [lxde/lxqt#628] opened 2015-04-30 08:04 UTC
I'm not sure where to open this request/bug so I'm opening it here.

1. 
I feel this feature is a must in any modern desktop: having an icon on the panel that shows the current keyboard layout and allows to switch between the ones available.

2.
I'm not sure who is to blame but `fbxkb` looks to not work properly with the lxqt-panel tray icons

**Comment by pmattern** [comment] 2015-04-30 12:37
Duplicate of #602.

**Comment by postadelmaga** [comment] 2015-04-30 14:16
Alright you can close this issue: 

- fbxkb looks to work ( if I load it on startup it )
- on #602 I can see the qxkb is a better alternative while this feature is implemented in lxqt

thanks

**Comment by pmattern** [comment] 2015-04-30 14:31
> Alright you can close this issue.

No, I can't - I'm not a developer :-) But you can by clicking "Close" somewhere under the comment field.

**Comment by paulolieuthier** [comment] 2015-04-30 14:34
Closing as duplicate, as @pmattern very well said.

**Closed** 2015-04-30 14:34 UTC
Labels: invalid/dup/rejected
