### ISSUE TITLE
LXQt runner: don't show both binary and corresponding desktop entry by default

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#478] opened 2015-02-05 15:44 UTC
Those proposals generated automatically upon typing in text box are by default comprising both binaries and corresponding desktop entry files if applicable, e. g.
![lxqt runner - binary plus desktop entry](https://cloud.githubusercontent.com/assets/9860801/6063182/8b2065ba-ad55-11e4-8441-32d5512b12ca.png)

I think this is no problem at all or even helpful in some situations for experienced users but may be confusing the less experienced.
So I'd suggest to make this configurable in some way, probably within item "Configure" in runner's menu, and not have it enabled by default.

**Comment by jleclanche** [comment] 2015-02-05 15:45
Yeah I thought we already had an issue for that.

**Comment by Vladimir-csp** [comment] 2015-02-19 12:13
Maybe just prioritize application over binary in the list?

**Comment by jleclanche** [comment] 2015-02-19 12:27
Yes. But for that we need to know an app's exec is equivalent to the binary in the list. Ill look into it.

**Comment by paulolieuthier** [comment] 2015-03-02 15:00
Yeah, this is a duplicate of #476.

**Comment by paulolieuthier** [comment] 2015-03-03 17:17
Reopening as it's not exactly a duplicate.

**Comment by jubalh** [comment] 2015-06-17 09:59
Yeah would be a lot nicer.
@jleclanche *Yes. But for that we need to know an app's exec is equivalent to the binary in the list. Ill look into it.* <- any update yet?

**Comment by jleclanche** [comment] 2015-06-20 13:49
No update, this is open for PRs.

**Closed** 2015-10-14 06:38 UTC
Labels: lxqt-runner, polish

**Comment by stefonarch** [comment] 2015-10-14 08:51
I'm not sure where the problem lies, just I've jsut recompiled
lxqt-runner, -common, -config and -panel as they had updates and it
broke my desktop: panel was not responsive, runner, switcher and
shortcuts not working at all.
Recompiled globalkeys and other stuff, panel is working ow but
globalkeys and runner not all .


Il 14/10/2015 08:39, palinek ha scritto:

**Comment by palinek** [comment] 2015-10-14 08:54
> I'm not sure where the problem lies, just I've jsut recompiled
lxqt-runner, -common, -config and -panel as they had updates and it
broke my desktop: panel was not responsive, runner, switcher and
shortcuts not working at all.
Recompiled globalkeys and other stuff, panel is working ow but
globalkeys and runner not all .

IMO the lxde/lxqt-runner#32 has definitely nothing to do with this kind of problem.

**Comment by stefonarch** [comment] 2015-10-14 09:51
I agree, I guess the problem  is here:
$ globalkeysd [Critical] Cannot register service 'org.lxqt.global_key_shortcuts' [Notice] Stopped

**Comment by pmattern** [comment] 2015-10-14 12:27
Re-installing a fraction of LXQt components from AUR can cause trouble easily as AUR isn't aware of changed dependencies. E. g. those four components you re-installed right now may very well have been compiled against later versions of some components from the official repos than the other LXQt components which in turn may cause the trouble you ran into.
Cannot reproduce this problem on up-to-date Arch Linux systems with *all* LXQt components compiled from today's VCS checkouts so I'm assuming re-compiling LXQt as a whole will solve the problem at your side, too.

That aside any further discussion of this particular problem should take place elsewhere as it's certainly not related to this issue's actual topic. This is to avoid clutter if additional comments about the latter should get submitted, e. g. if some problems arise that haven't been seen so far.

**Comment by jleclanche** [comment] 2015-10-17 13:51
@palinek I'm still seeing this issue with items in the history, FYI.

**Comment by jleclanche** [comment] 2015-10-17 13:56
Unless it can be simply fixed on top of this, I'll file another issue for the history item, milestoned next release.

**Comment by pmattern** [comment] 2015-10-18 14:17
@palinek
As of lxde/lxqt-runner@df339f2 I can confirm two entries corresponding to one binary may come up, e. g. like this
![lxqt-runner_duplicate-binary-entry](https://cloud.githubusercontent.com/assets/9860801/10564400/f0980b52-75b2-11e5-937a-8abc5d9c4b69.png)
when one invocation got already saved in `.cache/lxqt-runner.history`.
But actually I'm pretty sure this couldn't be seen when I was posting that [comment](https://github.com/lxde/lxqt-runner/pull/32#issuecomment-147885709) in lxde/lxqt-runner#32. So did you by any chance commit some more changes thereafter which should eventually get reverted (difficult to check right now as the branch got deleted in the meantime)?

**Comment by palinek** [comment] 2015-10-18 19:13
Hm... I didn't make any changes in filtering the history items (not that I'm aware of). Personaly I think they shouldn't get filtered in any way...
