### ISSUE TITLE
Replacement for "lxqt-power" dialog?

### ISSUE THREAD

**Issue by antis81** [lxde/lxqt#425] opened 2015-01-07 12:17 UTC
This question concerns the recently removed `lxqt-power` module. The submodule was removed, stating it is integrated into `lxqt-powermanagement`. So, how can I start the "shutdown dialog"?

The reason I'm asking is, because I'm using a panel replacement (cairo-dock). There's no shutdown option from the menu and currently I'm using `lxqt-runner` as a workaround. Apart from that I really like the dialog and want to have it back. Hope it did not get lost on the way ...

**Comment by jubalh** [comment] 2015-01-07 15:12
lxqt-power was marked deprecated without a working replacement AFAIK.
it is still available here http://git.lxde.org/gitweb/?p=lxde/lxqt-power.git
But not ported to Qt5. I think they want to create a plugin for lxqt-panel with that functionality.
If I understand your use case correctly you want to have in in cairo-dock, so the lxqt-panel plugin won't work for you.
Actually, since this is the second time I hear need for lxqt-power. I think I will try to port it and bring it back to live when I find some time.

**Comment by antis81** [comment] 2015-01-07 16:20
Thanks, I was really hoping for a more optimistic answer though :smile:.

Hm ... I'm having Qt5 running anyways ... plus, a little time. I'm just compiling and see how it goes ... I'll try to get it running this evening. Anything against putting an inofficial, synchronized fork on Github? Or other question: Can I quickly setup and contribute on lxde.org?

**Comment by antis81** [comment] 2015-01-07 22:58
First steps done. Joined with another fork and re-pushed to my personal repo here: 

PR is here: https://github.com/antis81/lxqt-power/pull/1

@jubalh Changes are "blind" so far. Need some help to compile the required lxqt libs. Do I need to compile the whole thing?

**Comment by antis81** [comment] 2015-01-11 15:09
@surlykke Maybe you could help out with this. Think it is a good idea to completely integrate the dialog into lxqt-powermanagement.

**Comment by surlykke** [comment] 2015-01-11 15:29
2015-01-11 16:09 GMT+01:00 Nils Fenner <notifications@github.com>:

> @surlykke <https://github.com/surlykke> Maybe you could help out with
> this. Think it is a good idea to completely integrate the dialog into
> lxqt-powermanagement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt/issues/425#issuecomment-69497532>.
>
I don't really like the idea of this in lxqt-powermanagement. I think it
should be an independent application, but there are varying views on this.
See the discussion in  https://github.com/lxde/lxqt/issues/319 and
https://github.com/lxde/liblxqt/pull/22

It seemed to me that the conclusion on those discussions was either
resurrecting the old lxqt-power or creating a new lxqt-leave. Not quite
sure which... I favor lxqt-power. We had that, it worked.

br. Chr.

**Comment by jleclanche** [comment] 2015-01-11 15:43
Closing as dupe of #319 where we already had discussion about this.

**Closed by jleclanche** 2015-01-11 15:43 UTC

**Comment by antis81** [comment] 2015-01-11 16:00
Well, I also really like `lxqt-power`. It's simple and does its job pretty well. I could live with an lxqt-leave, also I don't get why reimplementing such a small piece of code would be necessary. 

What we currently have, is no solution at all! And that's really bad, because it's such a small thingy.

**Comment by antis81** [comment] 2015-01-11 16:33
Sorry guys. I just saw the `lxqt-leave` solution, realized in [PR 22](https://github.com/lxde/liblxqt/pull/22) is not merged yet. Just waiting for that ...

I took a short look at the code and to me it seems for the better. Unfortunately, the deprecated `lxqt-power` module was removed too early, thus the feature got lost temporarily.
