### ISSUE TITLE
lxqt-config: adoption of key Enter upon exiting terminal emulator on same virtual desktop

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#965] opened 2016-02-24 17:17 UTC
Leaving a terminal emulator that's running on the same virtual desktop as `lxqt-config` can make the latter adopt key `Enter` and hence launch the dialogue that was selected before.

Steps to reproduce
- Open `lxqt-config` and a terminal emulator on the same virtual desktop. Additional windows may or may not be present.
- If the terminal emulator features tabs make sure a single one is opened only so that exiting the shell will close the window. Bear in mind which topic is selected (highlighted text) in `lxqt-config`.
- Focus the window of `lxqt-config` no matter how, e. g. via plugin-taskbar, clicking or hovering the mouse or using an application switcher. Focus the terminal emulator window the same way. Close the terminal emulator window by filing `exit` in the shell and hitting `Enter`.  
  The highlighted item in `lxqt-config` will now get launched.

Problem is manifest in LXQt sessions using Openbox, KWin or Xfwm as window manager as well as in Openbox sessions without desktop environment, in particular without PCManFM-Qt handling the desktop.
It can be seen with terminal emulators QTerminal, xterm, Konsole, LXTerminal and Xfce4 Terminal Emulator.
So far I couldn't trigger something similar with an application other than `lxqt-config`. In particular the dialogues it typically provides like the various `lxqt-config-*` don't seem to be affected. (Samples which basically respond to hitting `Enter` are `lxqt-config-monitor` and `obconf-qt`.)
So besides I'm not 100% who's to blame here it looks like it's `lxqt-config`.

Seen with today's VCS checkout of LXQt on Arch Linux, so among other lxqt-config lxde/lxqt-config@cfb3f5f, and LXQt 0.10 on Debian stretch (testing).

[Edit: forgot to mention KWin and Xfwm as stated above]

**Comment by Vladimir-csp** [comment] 2016-02-24 17:26
Confirming.

**Comment by tsujan** [comment] 2016-02-24 18:21
Confirming and more than that:

Just open lxqt-config and highlight an item that can have multiple instances (like Print Settings). Press Enter and hold it for a few seconds. Then several instances will be launched -- in my case, more than 30 windows of Print Settings!

The correct behavior would be for lxqt-config to launch only one instance and that only after the Enter key is released.

**Comment by palinek** [comment] 2016-02-24 22:19
Can you, guys, confirm correctness of lxde/lxqt-config@8487f6a ?

**Comment by tsujan** [comment] 2016-02-25 12:39
@palinek 
Yes, it fixes both issues.

**Comment by pmattern** [comment] 2016-02-28 14:11
Running lxde/lxqt-config@8487f6a or lxde/lxqt-config@336f28d on Arch Linux the problem of launched items upon exiting a terminal emulator is fixed but the incorrect behaviour of key `Enter` persists.

Still a multitude of instances comes up if `Enter` is held some time. Seen with `lxqt-config-appswitcher` of [LXQt Application Switcher](https://github.com/zjes/lxqt-appswitcher) (in case anybody wants to verify, the prerequisites stated on the homepage aren't correct, see `CMakeLists.txt`).
Also, when hitting `Enter` has an effect in the application that was launched from within `lxqt-config` as usual, this effect is triggered when `Enter` gets held a bit too long in `lxqt-config`. This can e. g. be seen with `lxqt-config-monitor` where button `Apply` seems to get triggered or in `obconf-qt` where it's button `Install a new theme` from section "Theme" (left pane).

**Comment by palinek** [comment] 2016-02-28 18:46
> but the incorrect behaviour of key Enter persists. Still a multitude of instances comes up if Enter is held some time.

And why shouldn't they? It's a normal way how keyboard events are generated (I don't know what are the default settings of keyboard repeat rate & delay).

E.g. if you keep holding enter key in a text editor, you keep entering new lines, not?

**Comment by pmattern** [comment] 2016-02-29 11:12
> > but the incorrect behaviour of key Enter persists. Still a multitude of instances comes up if Enter is held some time.

> And why shouldn't they?

I was actually only referring to
> Then several instances will be launched  [...] The correct behavior would be for lxqt-config to launch only one instance [...]

Nobody contradicted so I thought there was a kind of agreement that opening several instances is no expected behaviour.
Personally, I'm not sure at all whether or not opening several instances that way is desirable.

What on the other hand do you think about the behaviour regarding `lxqt-config-monitor` and `obconf-qt` as depicted in my previous comment which is something related but slightly different?

**Comment by palinek** [comment] 2016-02-29 11:45
> Personally, I'm not sure at all whether or not opening several instances that way is desirable.

I also tend to say it is useless... but it's the user's responsibility & configuration if his/her system.

> What on the other hand do you think about the behaviour regarding lxqt-config-monitor and obconf-qt as depicted in my previous comment which is something related but slightly different?

Here I think the same way... if the user will hold the enter key he/she should know the consequencies. Here we have absolutely no control what events are propagated to the newly created window, as it doesn't not belong to our app (lxqt-config).

All in all I think we should not try to do any workarounds for this and keep system/X/WM/Qt handle it the standard way.

**Comment by tsujan** [comment] 2016-02-29 12:08
@palinek
Pressing Enter inside a text editor can't be compared with pressing it to launch an app. Yes, they're `Enter` and it being pressed but with very different meanings and consequences. In the latter case, a key release can be expected after the key press; hence what I wrote about "the correct behavior".

> if the user will hold the enter key he/she should know the consequencies

Should he?! The consequences could be grave (as in the case of 30-40 instances, which was fixed by your commit) and a good design would be the one that saves users from such hassles.

> Here we have absolutely no control what events are propagated to the newly created window

This is a technical obstacle. As you surely know, there's always a way ;) What's impossible is impossibility itself.

**Comment by palinek** [comment] 2016-02-29 12:38
> as in the case of 30-40 instances, which was fixed by your commit

I just removed the home made "activate" logic which I believe was there only because of another hidden bug in lxqt-qt-plugin. So what we are observing now is the default Qt behaviour (activation). There is the logic implemented in `void QAbstractItemView::keyPressEvent(QKeyEvent *event)` => so the `activated` signal is emitted upon keyPress not keyRelease.... @tsujan do you think, it is a Qt bug?

**Comment by pmattern** [comment] 2016-02-29 13:12
Please let me briefly repeat that the bug / feature that plenty of instances of applications provided by `lxqt-config` come up when holding key `Enter` is *not* fixed / removed in lxde/lxqt-config@336f28d.
This issue's primary problem, the launch of an application provided by `lxqt-config` upon exiting a terminal emulator, is fixed, though.

**Comment by tsujan** [comment] 2016-02-29 14:07
> I just removed the home made "activate" logic

Yes, I saw that and it did the job.

> do you think, it is a Qt bug?

I'll look into it as soon as I have time. Right now I'm busy with an exciting workaround for another hidden Qt5 bug (for inclusion in Kvantum).

**Comment by palinek** [comment] 2016-02-29 14:15
@paulolieuthier @tsujan Although I don't like such workarounds (it can break whenever Qt guys change their internal logic), I've created one in lxde/lxqt-config#77. Please have a look on that.

**Comment by tsujan** [comment] 2016-03-01 12:44
@palinek I think about QCategorizedView.

**Comment by tsujan** [comment] 2016-03-01 13:07
In QAbstractItemView, `activated()` is emitted on `mouseReleaseEvent()` for mouse but on `keyPressEvent()` for keyboard. I can't call it a bug but I think we could do something here.

**Comment by palinek** [comment] 2016-03-01 13:11
> I can't call it a bug but I think we could do something here.

Is there something I've missed in lxde/lxqt-config#77?

**Comment by tsujan** [comment] 2016-03-01 13:15
> Is there something I've missed in  lxde/lxqt-config#77?

No, I don't think so; I'm just working on another approach, now that I have time.

**Comment by tsujan** [comment] 2016-03-01 13:37
I did this and it worked:

In QCategorizedView, I added `keyPressEvent()` and `keyReleaseEvent()`. In `keyPressEvent()`, I just ignored `Key_Enter` and `Key_Return` and let QAbstractItemView do the rest. In `keyReleaseEvent()`, I emitted `activated()` for the same keys in the same way QAbstractItemView did it under `keyPressEvent()`.

Would you want me to make a PR or you'll try that yourself? (I'm not familiar with your coding style and don't want to change it.)

**Comment by palinek** [comment] 2016-03-01 13:40
> Would you want me to make a PR or you'll try that yourself? (I'm not familiar with your coding style and don't want to change it.)

Make your proposal. It's neither my application nor my code in `QCategorizedView`... actualy the whole categorized view seems to be taken from KDE (based on the license comments).

**Comment by tsujan** [comment] 2016-03-01 15:19
@pmattern
After https://github.com/lxde/lxqt-config/commit/8487f6a, do you see the mutiple instance problem with any item other than `lxqt-config-appswitcher` (which I don't have)?

**Comment by tsujan** [comment] 2016-03-01 17:31
@pmattern Ignore my last comment! Would you please test https://github.com/lxde/lxqt-config/pull/78 and see if fixes all issues (including the one you mentioned about transference of Enter to the launched app)?

**Comment by pmattern** [comment] 2016-03-01 22:38
Unfortunately both problems can still be seen with tsujan/lxqt-config@eeea902 on Arch Linux. Still several instances of e. g. `obconf-qt` come up when `Enter` gets hold a bit, still `Enter` gets handed to the application started from `lxqt-config`.
Regarding the latter, I realized two more aspects. First, it seems to be a matter of timing as sometimes none of the several instances of `obconf-qt` had the dialogue opened and sometimes a fraction of the instances did and the rest didn't. Second, the handing seems to take place at several layers so to say. E. g. as for `lxqt-config-monitor` it could be seen that holding `Enter` doesn't just launch dialogue "Settings are changed" but also closes the dialog by selecting "Yes". So it triggers the same behaviour as selecting "Monitor settings" in `lxqt-config` and hitting `Enter` the usual way ("short") three times.
Running lxde/lxqt-config@90930e3 several instances are launched upon holding `Enter` as well but I couldn't see that handing of `Enter` to the application that was launched any more.

Meanwhile and unlike I wrote [earlier](https://github.com/lxde/lxqt/issues/965#issuecomment-190159605) I think it would be better if both features did not exist. I mean holding a key a bit longer than intended is something that happens easily and both getting several instances of one of those configuration tools let alone a dialogue belonging to one of them is probably confusing for users.
On the other hand it's pretty obvious for users what just happened, the results are easy to mitigate (close a bunch of windows...) and easy to avoid (pay some attention next time).
So I suggest not spending too much effort into this.

@tsujan 
There's one other thing I've been wanting to ask you since long time.
Could you eventually open your test branches in the project's repositories like github.com/lxde/foo instead of your own forks? This allows for checkout out master and testing branches from the same repository which in turn makes testing on Arch Linux a bit easier and quicker. AFAIK there are no downsides due to this, e. g. palinek is creating branches in the project repositories all the time as well.

**Comment by tsujan** [comment] 2016-03-01 22:53
@pmattern 
Strange! I can't reproduce your results here. Always only one instance is launched and that's after `Enter` is released. The interval between pressing and releasing doesn't have any effect. I especially tried obconf-qt: just one instance and no transference of `Enter`.

> Could you eventually open your test branches in the project's repositories

OK. I just didn't know about that.

**Comment by tsujan** [comment] 2016-03-01 23:30
@pmattern
Are you sure you tested https://github.com/tsujan/lxqt-config/commit/eeea902? Both theoretically and practically, your results are improbable with it. Or I may be totally lost?

> ... So I suggest not spending too much effort into this.

IMO, it would be worth the effort (although I consider it done).

**Comment by tsujan** [comment] 2016-03-02 01:33
BTW, I started my older computer with its updated Manjaro+KDE and saw that systemsettings had similar problems, namely, the "terminal" issue and the auto-repeated `Enter`. For the latter, highlight Personalization -> Applications, hold `Enter` for a few moments, and then release it. No excuse for us, of course. QCategorizedView wasn't tailored to our needs/expectations; I hope it is now.

**Comment by palinek** [comment] 2016-03-02 07:37
@pmattern
Just tested also the lxde/lxqt-config#78 and it doesn't suffer from any problem reported here (multi instance enter, terminal enter, enter to spawned window)... just the same as in the lxde/lxqt-config#77.

So that's realy weird... it's working for both of us (tsujan & me) and not for you.

@paulolieuthier can you, please, test the PRs? (as you are on arch also)

**Comment by tsujan** [comment] 2016-03-02 11:03
@palinek Yes, both work. IMO, it's better to keep `mainwindow.cpp` uncluttered, while the new QCategorizedView can show the root of a problem and be used elsewhere (maybe you'd want to enhance it), but the decision is yours.

**Comment by tsujan** [comment] 2016-03-02 19:51
@pmattern
The doc (https://github.com/lxde/lxqt/wiki/Contributing-code) explicitly says that the repositries should be forked first. I might make PR's for *any* LXQT component and, as I'm not (and *won't be*) a GitHub expert, I don't want to cause any mess inadvertently. So, isn't it better for me to continue working on my own forks? After all, it's so easy to test a branch by downloading its zip file.

**Comment by pmattern** [comment] 2016-03-02 20:09
@tsujan 
Well, I guess the advice to fork first is written with non-team members in mind. These have to fork as they don't have permissions to write to the project's repository and hence can't upload their contributions without a fork.
Working with the project's repositories is actually not that difficult. Checkout the project repository, create your own branch `git checkout -b somenewbranch`, make your commits as usual, upload to the repository creating the remote branch `git push --set-upstream origin somenewbranch:somenewbranch`.
But if you don't feel comfortable with this it's absolutely okay to go on using your forks. The advantage with regards to tests mentioned above is mainly about re-using existing checkouts in a quicker way. So it's more convenient and quicker but not essential in any way.

**Comment by tsujan** [comment] 2016-03-02 20:53
OK! I'll do as you told. Thanks!

**Comment by paulolieuthier** [comment] 2016-03-03 01:42
I hold Enter for a couple of seconds, and that opened 45 instances of "Print Settings", leaving the system unresponsive for a few more seconds. We need the workaround. I tested @tsujan PR, it works well here.

**Comment by pmattern** [comment] 2016-03-03 13:40
In the meantime I had another look at the commits proposed both in lxde/lxqt-config#77 and lxde/lxqt-config#78 after re-compiling a checkout of all other LXQt components.
Running either commit both launching several instances and handing key `Enter` to the launched application ceased - but most of the time only.
Sometimes both problems could still be seen but so far I failed to reproduce when exactly this takes place. Starting several applications from `lxqt-config` one after another seems to be involved somehow. That is, launch `lxqt-config` and launch another application, say `obconf-qt` → all fine. But select some other applications by arrow keys and launch them → both problems can be seen sporadically.

**Comment by tsujan** [comment] 2016-03-03 22:16
@pmattern 
This might sound strange at first but do you have another keyboard to test with? My reason is that:

(1) The logic of both commits seems sound;
(2) @palinek, @paulolieuthier and I see one and the same result, which is the opposite of yours.

BTW, I played with the arrow keys and saw no difference.

**Comment by palinek** [comment] 2016-03-04 06:59
...or could potetialy the bare metal vs. virtualization testing make a difference?

**Comment by tsujan** [comment] 2016-03-04 13:46
> ...or could potetialy the bare metal vs. virtualization testing make a difference?

That's a possibility I hadn't thought of.

**Comment by pmattern** [comment] 2016-03-06 19:48
Sure enough my own tests regarding this issue were all "bare metal" already...

After compiling lxde/lxqt-config@90930e3 and tsujan/lxqt-config@ba81d35 another time against yesterday's checkout of all LXQt components the results remain the same as depicted in my previous comment.
Of course it's strange when I'm the only one seeing this but on the other hand I can't real figure what should be particular at my side. Just some regular Arch Linux system plus the whole LXQt stuff from the AUR. No particular tweaking, no other frills.

In an attempt to figure out whether something is eventually wrong with my keyboard I fiddled a little bit with `xset` and `xev` which left me confused:
While it's possible to disable autorepeat on key `Enter` only this will hardly ever happen  in practice. If autorepeat is enabled and `Enter` gets held a while all the key press and release events due to autorepeat are the very same as the press event at the beginning and the release event at the end.
So I for one don't understand how it's possible to figure out whether or not some key press / release event is due to autorepeat and hence how the problem of several instances can get solved in the first place.

**Comment by palinek** [comment] 2016-03-06 20:36
> If autorepeat is enabled and Enter gets held a while all the key press and release events due to autorepeat are the very same as the press event at the beginning and the release event at the end.

Well, qt knows :smile: -> http://doc.qt.io/qt-5/qkeyevent.html#isAutoRepeat

**Comment by tsujan** [comment] 2016-03-06 20:46
I quote from the same place: "Note that if the event is a *multiple-key compressed* event that is partly due to auto-repeat, this function could return either true or false indeterminately." (Italics are mine.)

**Comment by paulolieuthier** [comment] 2016-04-25 23:14
@pmattern can you still reproduce that, using both Openbox and KWin? I think we should merge @tsujan's PR, but I'd like to see confirmation from you.

**Comment by palinek** [comment] 2016-04-26 06:26
>  IMO, it's better to keep mainwindow.cpp uncluttered, while the new QCategorizedView can show the root of a problem and be used elsewhere

The `QCategorizedView` is universal view and as so can be used in scenarios where the user wants the default (multi-activate `Enter`) behaviour. In our specific usage we want to avoid this... so I thing the fix should go into mainwindow.cpp (or in some QCategorizedView derived class).

Of course currently the QCategorizedView isn't used anywhere else in LXQt, but who knows what the furure may carry.

**Comment by pmattern** [comment] 2016-04-26 23:32
Results after compiling the commits proposed in lxde/lxqt-config#77 and lxde/lxqt-config#78 against latest VCS checkouts of all other LXQt components on Arch Linux:
Both remaining problems can still be seen, that is pressing and holding `Enter` in `lxqt-config` may launch several instances of an application, e. g. `obconf-qt`, and a button in the UI of the application launched that way may get triggered, e. g. `Install a new theme` of `obconf-qt`.
The period `Enter` has to be held in order to trigger any of the two effects is much longer than in current `master` and longer than what can be expected to happen per incident. In lxde/lxqt-config@90930e3 only one of the two effects can be seen at a time, in tsujan/lxqt-config@ba81d35 both can happen in parallel but the period to trigger seems even longer.

Thoughts:
Both effects may be nasty but are easy to workaround and `lxqt-config` isn't an application needed too frequently, normally users will make the desired settings once and modify them rather rarely.
As I understand it, both commits / PRs may eventually cause regressions should the Qt components involved get changed.
If the latter is not too likely one of the commits could very well be merged, I for one cannot tell which one is better. But if the risk of regressions is rather high we could leave things like they are right now, too. Note the main problem addressed in this issue was a different one and has been fixed long ago anyway.

**Comment by palinek** [comment] 2016-04-28 10:22
> The period Enter has to be held in order to trigger any of the two effects is much longer than in current master and longer than what can be expected to happen per incident.

Hm... can it be that your keyboard (or firmware, driver etc..) is re-sending the keydow/keyup events in case the key is hold down too long? Can you check that with the `xev`?

**Closed** 2016-11-20 15:20 UTC
Labels: lxqt-config, polish
