### ISSUE TITLE
Problem WIth PulseAudio Startup

### ISSUE THREAD

**Issue by tsujan** [lxde/lxqt#1258] opened 2017-02-14 14:14 UTC
##### Expected Behavior
pulseaudio should start with LXQt session, regardless of how many logous/logins are done.

##### Current Behavior
With the first logout-login after system start-up, pulseaudio starts correctly but the second time, it doesn't start and an error icon appears on the Volume Control plugin:

![error](https://cloud.githubusercontent.com/assets/981076/22931971/ead53eb8-f2db-11e6-8cc7-eb0885b646ae.png)

In such cases, I have to do `pulseaudio --start` manually. I've also seen that if I do `pulseaudio --kill` *before* the second and subsequent logouts, the problem won't happen.

I've customized `/etc/pulse/default.pa` and `/etc/pulse/daemon.conf` to have "echo cancellation" but the problem started to happen only recently (LXQt's starting pulseaudio worked for more than a year) and, more importantly, this doesn't happen when I use KDE.

##### System Information

* Distribution & Version: Manjaro Testing (up-to-date)
* Kernel: 
* Qt Version: 5.8 (also happened with 5.7)
* liblxqt Version:  latest git
* Package version:  latest git
* Display manager: sddm.

**Comment by agaida** [comment] 2017-02-15 00:03
so we should have a look at our session and some systemd settings

**Comment by tsujan** [comment] 2017-02-15 00:07
But it needs confirmation. Does it happen to you too?

**Comment by agaida** [comment] 2017-02-15 00:08
aka: who is starting pulse - and why the hell nobody stop it on logout. The second one might be simple. It might be that systemd don't kill user processes on logout. (And i really hate this behaviour wholehearted - and switch it off in siduction after a lenghty talk with the other devs)

**Comment by agaida** [comment] 2017-02-15 00:10
^^ so i can't reproduce it with siduction, but it should be reproducible with pure debian

**Comment by tsujan** [comment] 2017-02-15 00:12
>  It might be that systemd don't kill user processes on logout

Oh, you mean this may be similar to https://github.com/lxde/pcmanfm-qt/issues/445: a systemd problem! However, if that's the case, we can compare LXQt to KDE now: why doesn't it happen with KDE?

**Comment by agaida** [comment] 2017-02-15 00:17
processes not killed after logout i wouldn't call a systemd problem to be true - in case it would be a configuration descision. And after the great init war we had a second war about this.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825394 and others

**Comment by tsujan** [comment] 2017-02-15 00:27
@agaida Thanks! I didn't know about that.

**Comment by agaida** [comment] 2017-02-15 12:27
only for the records - 'our' logind.conf
/etc/systemd/logind.conf
```
[Login]
#NAutoVTs=6
#ReserveVT=6
 KillUserProcesses=yes
```

**Comment by tsujan** [comment] 2017-02-15 12:44
In both Debian and Manjaro it's
````
[Login]
#NAutoVTs=6
#ReserveVT=6
#KillUserProcesses=no
````

**Comment by tsujan** [comment] 2017-02-15 12:59
@agaida 
I set `KillUserProcesses` to `yes` and the problem is fixed at last!

In such cases (which aren't rare, unfortunately), I have a gut feeling that some developers don't use what they develop.

**Comment by tsujan** [comment] 2017-02-15 13:16
`man logind.conf` says `KillUserProcesses` defaults to "yes" but the default was "no" here. It seems there's a conflict about it.

**Comment by pmattern** [comment] 2017-02-15 13:56
> `man logind.conf` says `KillUserProcesses` defaults to "yes" but the default was "no" here. It seems there's a conflict about it.

The value of that directive in `/etc/systemd/logind.conf` is reflecting the setting at compile time. This defaults to "yes" as of systemd 230 but is subject to changes downstream. E. g. both on current Arch Linux and Debian testing it's "no".

A binary not being terminated upon exiting an LXQt session does not necessarily mean there has to be a malfunction the next LXQt session. So I'm not sure that kill-on-exit thing really is the reason of this issue's initial problem, and wonder whether a crash could be involved.
Server binary `pulseaudio` is among the large number of binaries which happen to crash upon exiting LXQt sessions. So far I failed to figure out when exactly these crashes take place. One condition seems to be that PulseAudio had to take some action and play some sounds during the session. Also, the crashes do not seem to appear when `pulseaudio --kill` is invoked right before exiting the session which in fact triggers a relaunch as long as the global user unit `/usr/lib/systemd/user/pulseaudio.socket` is involved. The only adjustment of configuration files at my side is `load-module module-native-protocol-tcp auth-ip-acl=::1` in `~/.config/pulse/default.pa` in order to play sound by a system MPD instance.
These findings could basically explain some of yours as well so you may want to look through the logs whether crashes are involved.

They do not explain why the server is not restarted the next LXQt session, so it would indeed be interesting to know how it is launched on Manjaro.
(Default on Arch Linux: `/usr/lib/systemd/user/pulseaudio.socket` is enabled by an [install scriptlet](https://git.archlinux.org/svntogit/packages.git/tree/trunk/pulseaudio.install?h=packages/pulseaudio). File `/etc/xdg/autostart/pulseaudio.desktop` is just adopting the server to X sessions by some invocations of `pactl`, but rather not involved in what we're discussing here as it does not launch the server, IMHO.)

FWIW some discussion about those crashes upon exit has already taken place in https://github.com/pvanek/qlipper/issues/34#issuecomment-248427555 and following comments as well as https://github.com/lxde/lxqt-session/pull/88#issuecomment-265817823.

**Comment by tsujan** [comment] 2017-02-15 14:10
@pmattern 
There was never a pulseaudio coredump (I always check '/var/lib/systemd/coredump') but, when `KillUserProcesses` was `no`, pulseaudio didn't start on the second and subsequent logout-logins. Now, with `KillUserProcesses` set to `yes`, it starts correctly on every logout-login.

**Comment by tsujan** [comment] 2017-02-15 14:13
> This defaults to "yes" as of systemd 230 but is subject to changes downstream. E. g. both on current Arch Linux and Debian testing it's "no".

Hence the conflict ;)

**Comment by pmattern** [comment] 2017-02-15 14:31
> when KillUserProcesses was no, pulseaudio didn't start on the second and subsequent logout-logins.

And you don't find this strange? Aside from those crashes the PulseAudio server is working as expected no matter how many times I log out and in again on Arch Linux besides `KillUserProcesses=no` is active.
This makes the problem rather look like a downstream (Manjaro) one to me.

**Comment by tsujan** [comment] 2017-02-15 14:38
> And you don't find this strange?

Yes, I do but I'm not an expert in such matters. No crash and yet no pulseaudio!

> This makes the problem rather look like a downstream (Manjaro) one to me.

But Manjaro takes pulseaudio from AUR.

However:
(1) @agaida's comments saved me a headache. I'd tested many things except for `KillUserProcesses`.
(2) https://github.com/lxde/pcmanfm-qt/issues/445 is as strange as this to me. I think systemd has a bug that shows up *randomly*.

**Comment by tsujan** [comment] 2017-02-15 14:51
@pmattern 
`pulseaudio-10.0-2-x86_64.pkg.tar.xz` and `systemd-232-8-x86_64.pkg.tar.xz` have exactly the same sizes in Arch and Manjaro so there's no chance that Manjaro has changed anything in them.

**Comment by agaida** [comment] 2017-02-15 16:22
@tsujan @pmattern - i might sound a little bit stubborn, but ..
* it seems that pulse is a long running process that stops not with the session - as long it is a user process it should imho
* it might be related to dbus-user-sessions - dunno if the dbus-session talks with pulse. it might be that pulse try to listen to the wrong session (wild guess, no clue about)
* as i wrote - i really hate it if programms run under a user without session - there might be corner cases where this was ok, imho it should be handled otherwise today - imho if a real user end his session his processes has to die too.

I don't know the current state of implementation and the behaviour that is discussed in the debian but (processes started with nohup, terminating sessions with sighup or so) - not really my business. And I'm out of ideas with this kind of behaviour - we solved it in siduction with hard killing the remaining processes - and imho that is the behaviour what i expect as a typical desktop user.

**Comment by tsujan** [comment] 2017-02-15 23:01
Just for the record: I had some work under KDE so I tested `KillUserProcesses=yes` with it too and saw there was no side effect.

**Comment by palinek** [comment] 2017-06-16 06:45
Can we close this?

**Closed** 2017-06-16 08:06 UTC
Labels: upstream
