### ISSUE TITLE
Create a modern menu

### ISSUE THREAD

**Issue by alfredobonino** [lxde/lxqt#902] opened 2015-11-21 18:02 UTC
Why not create a modern menu like whisker menu for xfce, the cinnamon menu, the KDE menu or budgie desktop menu???

**Comment by Esclapion** [comment] 2015-11-21 21:27
With a command search window :-) A lot of users ask for that.

**Comment by intialonso** [comment] 2015-11-21 22:07
Someone tried to do it in #101 but it seems dead. Maybe this is a duplicate of the same issue.

**Comment by jleclanche** [comment] 2015-11-22 09:26
dup

**Closed by jleclanche** 2015-11-22 09:26 UTC
