### ISSUE TITLE
Registering lxqt-globalkey shortcuts slows down the startup of lxqt-panel.

### ISSUE THREAD

**Issue by PCMan** [lxde/lxqt#505] opened 2015-02-18 12:06 UTC
Just some simple benchmark by calculating the time used to load each plugin.
Before launching lxqt-panel, I did echo 3 > /proc/sys/vm/drop_caches to clear all cache.
load  "mainmenu" : time:  321  ms
load  "desktopswitch" : time:  498  ms
load  "showdesktop" : time:  452  ms
load  "quicklaunch" : time:  629  ms
load  "taskbar" : time:  68  ms
load  "tray" : time:  40  ms
load  "mount" : time:  110  ms
load  "worldclock" : time:  93  ms
load  "volume" : time:  579  ms
Apparently, the volume plugin and all plugins using lxqt-globalkeys are slowest.
I tried to disable shortcut key registration and every plugin using it can get about 100ms reduction.
So, there must be some performance issue related to the global shortcuts.

**Comment by PCMan** [comment] 2015-02-18 12:07
@kuzmas do you have any idea about how to speed up global shortcut registration?

**Comment by PCMan** [comment] 2015-02-18 12:21
The plugins using globalkeys are mainmenu, desktopswitch, screensaver, showdesktop, and volume, all of which are slow on startup.

**Comment by PCMan** [comment] 2015-02-18 12:29
@kuzmas there is a blocking dbus call inside ClientImpl::addClientAction().
Would it be better if we change this to an async call instead?
This requires some change in globalkey APIs, though.

**Comment by PCMan** [comment] 2015-02-18 16:18
I did some experiments in the "delay-shortcut" branch of lxqt-panel.
Removing all of the global shorcut registration code can reduce the startup time of lxqt-panel by nearly 2 seconds on my machine. This is quite significant. So, the best way should be offering a set of asynchronous APIs for lxqt-globalkeys.
@luis-pereira @paulolieuthier @jleclanche this is something worth a proper fix since it can greatly speed up the startup. Also, it's the main cause of slowness of volume plugin since it registers "three" global shortcut keys. By disabling them, volume plugin starts immediately.

**Comment by jleclanche** [comment] 2015-02-18 22:23
@PCMan Did you look at how kglobalaccel does it? We're probably going to end up moving to that anyway.

BTW, kglobalaccel split their daemon away from plasma a few weeks back so in KF5 5.7.0 we have kglobalaccel containing both the runtime and the lib. Maybe now is the time, instead of investing into this fix...

**Comment by paulolieuthier** [comment] 2015-02-18 22:27
> BTW, kglobalaccel split their daemon away from plasma a few weeks back so in KF5 5.7.0 we have kglobalaccel containing both the runtime and the lib. Maybe now is the time, instead of investing into this fix...

I was not aware of that, that's very good news. @PCMan what's your opinion on that?

**Comment by kuzmas** [comment] 2015-02-18 22:27
@PCMan Of course I'll look at it. Just after work

@jleclanche AFAIK kglobalaccel has less features than lxqt-globalkeys

**Comment by jleclanche** [comment] 2015-02-18 22:29
@kuzmas what features would you specifically miss?

**Comment by kuzmas** [comment] 2015-02-18 22:32
@jleclanche:
1. making an arbitrary DBus call as an action
2. handling of multiple actions assotiated with one shortcut

**Comment by jleclanche** [comment] 2015-02-18 22:39
The KDE devs are usually open to improvements and new features so we can look into porting that functionality there.

We're thin on manpower and there is no real reason to maintain two different components that do the exact same thing, so Im honestly not keen on keeping globalkeys around when it hasn't received any real attention other than basic maintenance since the merge with Razor-qt. We can easily retain compatibility with globalkeysd in our other components for some time, though, if needs be.

**Comment by jleclanche** [comment] 2015-02-19 09:50
@kuzmas good work!

**Comment by PCMan** [comment] 2015-02-19 10:07
The same test after the fix in global keys. It's much faster now.
[pcman@7lab-desktop build]$ ./panel/lxqt-panel 
load  "mainmenu" : time:  111  ms
load  "desktopswitch" : time:  11  ms
load  "showdesktop" : time:  569  ms
load  "quicklaunch" : time:  476  ms
load  "taskbar" : time:  15  ms
load  "tray" : time:  2  ms
load  "mount" : time:  73  ms
load  "worldclock" : time:  65  ms
load  "volume" : time:  203  ms

**Comment by PCMan** [comment] 2015-02-19 10:09
Though the fix solves the blocking problem, it breaks lxqt-panel.
After the fix done by @kuzmas, my lxqt-panel fail to register shorcuts for "showdesktop" and "volume" plugins. I keep getting error notifications telling me they could not register global shortcuts.
So, I re-open this issue.

**Comment by jleclanche** [comment] 2015-02-19 10:18
@PCMan can we have another issue for this please?

**Comment by kuzmas** [comment] 2015-02-19 19:23
@PCMan sorry, it was late night when I finished the fix and I didn't notice this side effect. Will look at it this evening.

**Comment by kuzmas** [comment] 2015-02-20 07:20
I've updated, recompiled everything, rebooted and everything started to work fine except for the volume shortcuts.
I use LXQt in the VirtualBox, so the issue can be caused by it: I cannot get events from multimedia keys at all: in lxqt-globalkeys UI, in KDE's UI for kglobalaccel and even in xev.
If someone can check whether the issue is valid in the environment where multimedia keys work in KDE and xev, that would be awesome.

**Comment by palinek** [comment] 2015-03-26 15:00
@PCMan, @kuzmas I made a few commits (https://github.com/lxde/lxqt-globalkeys/commit/8d70f7e55338c600686c39260e116796b785fca7, lxde/lxqt-panel@6969028043d069680dee1ddc1d7b6c786899f252, lxde/lxqt-panel@f8fc3b64d89f250c39b595af97b590b79586b13c, lxde/lxqt-panel@cf15609d08b02ac61fdc775b9a37a6f42b168d69) today whose solve also this issue (i hope)...

**Comment by ypnos** [comment] 2015-03-27 12:24
I have this problem for a long time that might be related:
lxqt-globalkeysd blocks on startup, the panel does not appear for a long time. Killing lxqt-globalkeysd (and restarting it) solves the problem.
It seems that the hanging is related to this error message from lxqt-globalkeysd:

    setNativeLocks failed: Resource temporarily unavailable

In this case I am using lxqt 0.9 from ArchLinux community repository. If the issue is already fixed please excuse my redundant report.

**Comment by paulolieuthier** [comment] 2015-05-01 16:33
I just reinstalled LXQt, all fresh. Not seeing this bug anymore.

**Comment by palinek** [comment] 2015-05-04 12:11
IMHO ... all here is fixed, currently i see following times (same plugins as @PCMan used in previous comments):
```
load plugin "mainmenu" takes 8 ms
load plugin "desktopswitch" takes 7 ms
load plugin "showdesktop" takes 7 ms
load plugin "quicklaunch" takes 3 ms
load plugin "taskbar" takes 3 ms
load plugin "mount" takes 11 ms
load plugin "worldclock" takes 6 ms
settingsChanged "Alsa"
load plugin "volume" takes 14 ms
```

... but I don't know about the @ypnos comment.

**Comment by paulolieuthier** [comment] 2015-05-04 17:22
@palinek awesome! I've seen what @ypnos was talking about, but I'm sure it's fixed.

**Closed by paulolieuthier** 2015-05-04 17:22 UTC
Labels: lxqt-globalkeys, lxqt-panel, performance
