### ISSUE TITLE
[lxqt-panel] The worldclock plugin is too small and text is cropped.

### ISSUE THREAD

**Issue by PCMan** [lxde/lxqt#842] opened 2015-10-04 02:10 UTC
![worldclock](https://cloud.githubusercontent.com/assets/46543/10266095/c286b1b6-6a7f-11e5-9618-730059c00f59.png)
Please see the screenshot.
The widget of worldclock plugin is too small and part of the text becomes invisible.
I use default "Custom" format and does not change any settings of the plugin.

**Comment by pmattern** [comment] 2015-10-04 09:02
Duplicate of #632.

**Closed by pmattern** 2015-10-04 09:02 UTC
Labels: high-priority, lxqt-panel
