### ISSUE TITLE
Cannot set shortcut key to super key alone

### ISSUE THREAD

**Issue by EinarMostad** [lxde/lxqt#1387] opened 2017-11-10 19:42 UTC
I want to set the shortcut key for the menu to the super (windows) key. I cannot do it because the program expects a key combination of a modifier key (super, ctrl, alt) and at least one other key.

![cannot set shortcut key to super key alone](https://user-images.githubusercontent.com/33556631/32675593-ae09ba04-c657-11e7-8ea2-ace965ad9507.png)

##### Expected Behavior
Super key alone should be able to be used as a shortcut for the menu.

##### Current Behavior
I have to use the super key + another key.

##### Steps to Reproduce (for bugs)
Open Global Actions Manager and double click the shortcut to open the menu.

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 
* Qt Version: 
* liblxqt Version:  0.12.0-1
* Package version: 0.12.0-1

**Comment by tsujan** [comment] 2017-11-10 19:53
Duplicate of https://github.com/lxde/lxqt/issues/1259.

**Closed by tsujan** 2017-11-10 19:53 UTC
Labels: invalid/dup/rejected
