### ISSUE TITLE
Feature request: Show application menu on desktop right click; show workspaces on desktop middle click

### ISSUE THREAD

**Issue by alexrichert** [lxde/lxqt#606] opened 2015-04-19 06:30 UTC
In XFCE, there are checkbox options (under Desktop Settings) for showing the application menu on right click on the desktop, as well as for showing a list of workspaces (and windows within those workspaces) on middle click on the desktop. XFCE also provides the option to hide desktop icons, which hides the entries in the normal desktop right-click menu, leaving only the application menu (if that option is enabled). Any chance of something along these lines in LXQt?

**Comment by pmattern** [comment] 2015-04-19 09:42
Accessing Application menu per right-click on desktop is discussed in #464, displaying a list comprising workspaces and applications per middle-click in #469.

**Comment by ianorlin** [comment] 2015-05-01 18:56
Although the two features are combined together into one button. In the gtk lxde you can have the middle click for all workspaces and have the right click for working on the desktop. Of course there is the easy workaround of adding a menu entry of pcmanfm-qt --desktop-pref to the openbox menu. Also your window manager needs to support these menus. Openbox does but kwin does I believe.

**Comment by pmattern** [comment] 2015-05-05 10:02
All in all this is a duplicate of the issues stated above hence closing it as such.

Please feel free to add your thoughts to #464 and #469.

**Closed by pmattern** 2015-05-05 10:02 UTC
Labels: pcmanfm-qt
