### ISSUE TITLE
Pcmanfm-qt crashing when cycling through folders

### ISSUE THREAD

**Issue by stefonarch** [lxde/lxqt#1410] opened 2017-11-20 17:53 UTC
Pcmanfm-qt windows crashes randomly showing  cursor type "spinning wheel" while opening folders

##### Expected Behavior

No crash opening folders.

##### Current Behavior

Sometimes crashing.
@tsujan : once you told me what to do for debug these crash, I cannot find it anymore.

##### Steps to Reproduce (for bugs)

1. Navigate fastly through folders for- and backwards.

##### System Information

* Distribution & Version: arcl & latest git.

**Comment by tsujan** [comment] 2017-11-20 18:55
@stefonarch When a crash can't be reproduced, a backtrace is a must. Please attach one! (first `coredumpctl gdb pcmanfm-qt` and then `where` -- attach what's after `where`).

I can't make pcmanfm-qt crash in anyway. My patches are either merged or PR'ed

**Comment by tsujan** [comment] 2017-11-20 19:01
@stefonarch An example of a backtrace with the above-mentioned method:
```
#1  0x00007f68311876b5 in g_object_unref () at /usr/lib/libgobject-2.0.so.0                                    
#2  0x00007f683051d7f2 in __cxa_finalize () at /usr/lib/libc.so.6                                              
#3  0x00007f68332b2d04 in  () at /usr/lib/libfm-qt.so.3                                                             
#4  0x00007ffff26dc2d0 in  ()                                                                                       
#5  0x00007f6833815b93 in _dl_fini () at /lib64/ld-linux-x86-64.so.2 
```

**Comment by stefonarch** [comment] 2017-11-21 08:21
Thanks, here is one:

```
[Current thread is 1 (Thread 0x7f737d0246c0 (LWP 24279))]
(gdb) where
#0  0x00007f737b1d3fa8 in QObjectPrivate::~QObjectPrivate() () at /usr/lib/libQt5Core.so.5
#1  0x00007f737af9f29a in  () at /usr/lib/libQt5Core.so.5
#2  0x00007f737b1dc3e6 in QObject::~QObject() () at /usr/lib/libQt5Core.so.5
#3  0x00007f736d28b924 in  () at /usr/lib/qt/plugins/styles/breeze.so
#4  0x00007f737b1d275d in QObjectPrivate::deleteChildren() () at /usr/lib/libQt5Core.so.5
#5  0x00007f737b1dc39c in QObject::~QObject() () at /usr/lib/libQt5Core.so.5
#6  0x00007f736d28cd35 in  () at /usr/lib/qt/plugins/styles/breeze.so
#7  0x00007f737b1d5681 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#8  0x00007f737bec2f2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#9  0x00007f737becaa06 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#10 0x00007f737b1a5060 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#11 0x00007f737b1a78b6 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /usr/lib/libQt5Core.so.5
#12 0x00007f737b2006e4 in  () at /usr/lib/libQt5Core.so.5
#13 0x00007f737a222270 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#14 0x00007f737a223f69 in  () at /usr/lib/libglib-2.0.so.0
#15 0x00007f737a223fae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#16 0x00007f737b1ffcd1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#17 0x00007f737b1a348b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#18 0x00007f737b1ac4d8 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#19 0x000055c5b81f628d in PCManFM::Application::exec() (this=0x7ffd1d3be830)
    at /home/stef/git/pcmanfm-qt/pcmanfm/application.cpp:334
#20 0x000055c5b8200b26 in main(int, char**) (argc=3, argv=0x7ffd1d3beb28)
    at /home/stef/git/pcmanfm-qt/pcmanfm/pcmanfm.cpp:14
(gdb) 

```

**Comment by stefonarch** [comment] 2017-11-21 08:28
PS: why does it refer the git folder? This evening I will rebuild it from a clean git clone.

**Comment by tsujan** [comment] 2017-11-21 12:13
@stefonarch This crash is about Breeze, not pcmanfm-qt. Please test with another style engine --  Fusion, for example. Here, I can't see a crash with Kvantum.

**Comment by tsujan** [comment] 2017-11-21 12:53
Can it be the case that your installed Qt5 is updated but Breeze isn't? A test with Fusion would be informative.

**Comment by stefonarch** [comment] 2017-11-21 17:18
Just activated fusion, maybe it's harder to provocate the crash but it did it twice:
```

(gdb) where
#0  0x00007ff303835fd1 in free () at /usr/lib/libc.so.6
#1  0x00007ff305ae609e in QObjectPrivate::Connection::~Connection() () at /usr/lib/libQt5Core.so.5
#2  0x00007ff305af0210 in QObject::~QObject() () at /usr/lib/libQt5Core.so.5
#3  0x00007ff3068125c6 in QWidget::~QWidget() () at /usr/lib/libQt5Widgets.so.5
#4  0x00007ff307203413 in Fm::FolderViewTreeView::~FolderViewTreeView() (this=0x55988fb4c180, __in_chrg=<optimized out>)
    at /home/stef/git/libfm-qt/src/folderview.cpp:251
#5  0x00007ff307203438 in Fm::FolderViewTreeView::~FolderViewTreeView() (this=0x55988fb4c180, __in_chrg=<optimized out>)
    at /home/stef/git/libfm-qt/src/folderview.cpp:255
#6  0x00007ff307204bd5 in Fm::FolderView::setViewMode(Fm::FolderView::ViewMode) (this=0x55988fb842a0, _mode=Fm::FolderView::FirstViewMode) at /home/stef/git/libfm-qt/src/folderview.cpp:576
#7  0x000055988ea7c955 in PCManFM::TabPage::chdir(Fm::FilePath, bool) (this=0x55988fdb0960, newPath=..., addHistory=true) at /home/stef/git/pcmanfm-qt/pcmanfm/tabpage.cpp:429
#8  0x000055988ea7d4ee in PCManFM::TabPage::up() (this=0x55988fdb0960)
    at /home/stef/git/pcmanfm-qt/pcmanfm/tabpage.cpp:557
#9  0x000055988ea60bfa in PCManFM::MainWindow::on_actionGoUp_triggered() (this=0x55988fdde840)
    at /home/stef/git/pcmanfm-qt/pcmanfm/mainwindow.cpp:382
#10 0x000055988eabf3e1 in PCManFM::MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x55988fdde840, _c=QMetaObject::InvokeMetaMethod, _id=21, _a=0x7ffc70a10c40)
    at /home/stef/git/pcmanfm-qt/build/pcmanfm/pcmanfm-qt_autogen/EWIEGA46WW/moc_mainwindow.cpp:433
#11 0x000055988eabfdb0 in PCManFM::MainWindow::qt_metacall(QMetaObject::Call, int, void**) (this=0x55988fdde840, _c=QMetaObject::InvokeMetaMethod, _id=21, _a=0x7ffc70a10c40)
    at /home/stef/git/pcmanfm-qt/build/pcmanfm/pcmanfm-qt_autogen/EWIEGA46WW/moc_mainwindow.cpp:588
#12 0x00007ff305ae8ce2 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#13 0x00007ff3067d0623 in QAction::triggered(bool) () at /usr/lib/libQt5Widgets.so.5
#14 0x00007ff3067d2e46 in QAction::activate(QAction::ActionEvent) () at /usr/lib/libQt5Widgets.so.5
#15 0x00007ff3068cd5dc in  () at /usr/lib/libQt5Widgets.so.5
#16 0x00007ff3068cd845 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#17 0x00007ff3069b13fb in QToolButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#18 0x00007ff306816a08 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#19 0x00007ff3069b1495 in QToolButton::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#20 0x00007ff3067d6f2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#21 0x00007ff3067def81 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#22 0x00007ff305ab9060 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#23 0x00007ff3067ddf0a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/libQt5Widgets.so.5
#24 0x00007ff306831d81 in  () at /usr/lib/libQt5Widgets.so.5

```

**Comment by tsujan** [comment] 2017-11-21 17:41
The backtrace i better this time.

Strange that I can't reproduce it! I hope you would try probable fixes.

**Comment by tsujan** [comment] 2017-11-21 17:42
Oh, you use the detailed list view; don't you? Does the crash happen in the icon view too?

**Comment by tsujan** [comment] 2017-11-21 18:04
Ah, this is getting more and more tricky. I could reproduce the crash twice, in the detailed list mode. However, the traces are slightly different. For the record:

The first crash:
```
#0  0x00007f0d91f478a0 in raise () at /usr/lib/libc.so.6
#1  0x00007f0d91f48f09 in abort () at /usr/lib/libc.so.6
#2  0x00007f0d91f8a517 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007f0d91f90c84 in malloc_printerr () at /usr/lib/libc.so.6
#4  0x00007f0d91f9112a in malloc_consolidate () at /usr/lib/libc.so.6
#5  0x00007f0d91f93f52 in _int_malloc () at /usr/lib/libc.so.6
#6  0x00007f0d91f95af4 in malloc () at /usr/lib/libc.so.6
#7  0x00007f0d8e238298 in  () at /usr/lib/libX11.so.6
#8  0x00007f0d8e23879b in _XmbTextListToTextProperty () at /usr/lib/libX11.so.6
#9  0x00007f0d8a4e7447 in QXcbWindow::setWindowTitle(QString const&) () at /usr/lib/libQt5XcbQpa.so.5
#10 0x00007f0d93bca3d4 in QWindow::setTitle(QString const&) () at /usr/lib/libQt5Gui.so.5
#11 0x00007f0d943af0b5 in QWidgetPrivate::setWindowTitle_helper(QString const&) () at /usr/lib/libQt5Widgets.so.5
#12 0x00007f0d943b4e3a in QWidget::setWindowTitle(QString const&) () at /usr/lib/libQt5Widgets.so.5
#13 0x00005623c9eaa73f in  ()
#14 0x00005623c9eb01d9 in  ()
#15 0x00007f0d93695d3f in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#16 0x00005623c9eea3b6 in  ()
#17 0x00005623c9eb9afe in  ()
#18 0x00007f0d93695d3f in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#19 0x00007f0d94ce8905 in Fm::Folder::onDirListFinished() () at /usr/lib/libfm-qt.so.3
#20 0x00007f0d93696662 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#21 0x00007f0d94383f2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#22 0x00007f0d9438ba06 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#23 0x00007f0d93666060 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#24 0x00007f0d936688b6 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /usr/lib/libQt5Core.so.5
#25 0x00007f0d936c16e4 in  () at /usr/lib/libQt5Core.so.5
#26 0x00007f0d928e6270 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#27 0x00007f0d928e7f69 in  () at /usr/lib/libglib-2.0.so.0
#28 0x00007f0d928e7fae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#29 0x00007f0d936c0cd1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#30 0x00007f0d9366448b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#31 0x00007f0d9366d4d8 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#32 0x00005623c9e9c848 in  ()
#33 0x00007f0d91f33f6a in __libc_start_main () at /usr/lib/libc.so.6
#34 0x00005623c9e9c8aa in _start ()
```

The second crash:
```
#0  0x00007f6999fdb8a0 in raise () at /usr/lib/libc.so.6
#1  0x00007f6999fdcf09 in abort () at /usr/lib/libc.so.6
#2  0x00007f699a01e517 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007f699a024c84 in malloc_printerr () at /usr/lib/libc.so.6
#4  0x00007f699a02867f in _int_malloc () at /usr/lib/libc.so.6
#5  0x00007f699a029af4 in malloc () at /usr/lib/libc.so.6
#6  0x00007f699b517794 in QArrayData::allocate(unsigned long, unsigned long, unsigned long, QFlags<QArrayData::AllocationOption>) () at /usr/lib/libQt5Core.so.5
#7  0x00007f699cda00a1 in  () at /usr/lib/libfm-qt.so.3
#8  0x00007f699cda1083 in Fm::FolderModelItem::FolderModelItem(std::shared_ptr<Fm::FileInfo const> const&) ()
    at /usr/lib/libfm-qt.so.3
#9  0x00007f699cd9d9b8 in Fm::FolderModel::onFilesAdded(Fm::FileInfoList const&) () at /usr/lib/libfm-qt.so.3
#10 0x00007f699b729d3f in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#11 0x00007f699cdfdb76 in Fm::Folder::filesAdded(Fm::FileInfoList&) () at /usr/lib/libfm-qt.so.3
#12 0x00007f699cd7c8da in Fm::Folder::onDirListFinished() () at /usr/lib/libfm-qt.so.3
#13 0x00007f699b72a662 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#14 0x00007f699c417f2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#15 0x00007f699c41fa06 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#16 0x00007f699b6fa060 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#17 0x00007f699b6fc8b6 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /usr/lib/libQt5Core.so.5
#18 0x00007f699b7556e4 in  () at /usr/lib/libQt5Core.so.5
#19 0x00007f699a97a270 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#20 0x00007f699a97bf69 in  () at /usr/lib/libglib-2.0.so.0
#21 0x00007f699a97bfae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#22 0x00007f699b754cd1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#23 0x00007f699b6f848b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#24 0x00007f699b7014d8 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#25 0x000055dd38234848 in  ()
#26 0x00007f6999fc7f6a in __libc_start_main () at /usr/lib/libc.so.6
#27 0x000055dd382348aa in _start ()
```

**Comment by tsujan** [comment] 2017-11-21 18:08
Got a third crash, whose trace is like the last one above; will give priority to that trace for now.

**Comment by stefonarch** [comment] 2017-11-21 18:08
Yes, detailed list view is default in preferences, and single click is on too.
It seems related to this, with all other view mode I cannot produce a crash.

**Comment by tsujan** [comment] 2017-11-21 18:10
@stefonarch Yes, there's definitely a problem in the detailed list view. There may even be more than one problem -- because of different backtraces.

**Comment by tsujan** [comment] 2017-11-21 18:20
Sorry for so many comments but it might help focusing on the problem later.

It seem that Qt doesn't wait for GLib when the directory is changed fast. Why only with the detailed list mode, I don't know yet.

**Comment by tsujan** [comment] 2017-11-21 20:04
By setting a folder in the detailed mode and leaving other folders in the icon mode, I'm getting 6 different backtraces!

Something's very wrong. I'd encountered a similar situation (with all kinds of backtraces) only once and in another app but the fix was so easy there.

**Comment by stefonarch** [comment] 2017-11-21 20:57
Those crashes appeared first time end of August, I don't exactly remember what was new then unfortunately (native file dialog?).
Maybe related: https://github.com/lxde/pcmanfm-qt/issues/458

**Comment by tsujan** [comment] 2017-11-21 21:02
@stefonarch Could you test https://github.com/lxde/pcmanfm-qt/pull/601?

**Comment by stefonarch** [comment] 2017-11-21 21:08
Looks good, could not provocate any crash anymore.

**Comment by tsujan** [comment] 2017-11-21 21:20
> Looks good, could not provocate any crash anymore.

Thanks! That's good news. I can't produce any crash either, even when I use the arrow shortcuts like a samurai uses his sword.

**Comment by tsujan** [comment] 2017-11-22 13:27
> Maybe related: lxde/pcmanfm-qt#458

Most probably but, in that case, the problem description was too unclear there. Anyhow, its "fix" was quite harmless even if it wasn't a fix.

**Closed** 2017-12-02 20:16 UTC
Labels: crash
